// gen-art.mjs — prove "draw anything" with code → committed SVG (no deps).
//
// Mermaid draws *diagrams*. For arbitrary pixels/vectors, SVG is the universal
// canvas: paths, gradients, filters, text, even base64-embedded raster — all in
// one committed file that renders via ![](art.svg). This script draws a
// deterministic generative composition (a seeded flow field of strokes) in the
// AC palette, so the same input always yields the same diff.
//
//   node gen-art.mjs > art.svg

const W = 720, H = 360;

// Tiny deterministic PRNG (mulberry32) — reproducible art, stable diffs.
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(0xACE5);

// A flow field: angle = f(x,y); trace polylines that follow it.
function angle(x, y) {
  return (
    Math.sin(x * 0.012) * 1.7 +
    Math.cos(y * 0.013) * 1.7 +
    Math.sin((x + y) * 0.006) * 0.9
  );
}

const palette = ["#9bd64a", "#e8ff8a", "#5fae3a", "#cdef7a", "#7f9a5e"];
const strokes = [];
const N = 240;
for (let i = 0; i < N; i++) {
  let x = rand() * W, y = rand() * H;
  const pts = [[x, y]];
  const steps = 40 + Math.floor(rand() * 40);
  for (let s = 0; s < steps; s++) {
    const a = angle(x, y);
    x += Math.cos(a) * 4;
    y += Math.sin(a) * 4;
    if (x < 0 || x > W || y < 0 || y > H) break;
    pts.push([x, y]);
  }
  if (pts.length < 4) continue;
  const col = palette[Math.floor(rand() * palette.length)];
  const d = pts.map((p, i) => (i ? "L" : "M") + p[0].toFixed(1) + " " + p[1].toFixed(1)).join(" ");
  strokes.push(
    `<path d="${d}" fill="none" stroke="${col}" stroke-width="${(0.6 + rand() * 1.6).toFixed(2)}" stroke-opacity="${(0.25 + rand() * 0.5).toFixed(2)}" stroke-linecap="round"/>`
  );
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="generative flow field">
  <rect width="${W}" height="${H}" fill="#0b0f0a"/>
  ${strokes.join("\n  ")}
  <text x="16" y="${H - 14}" font-family="ui-monospace, Menlo, monospace" font-size="11" fill="#7f9a5e">flow field · seed 0xACE5 · generated by gen-art.mjs</text>
</svg>`;

process.stdout.write(svg + "\n");
