// factory-chart.h — GENERATED by bin/chart.py; do not edit.
// The v3 beat chart: per phrase, its lead-in (consonant runway before
// beat 0), length in beats, and per word unit its slot, length, and
// semitone above TONIC (148.73 Hz — HER D, measured off the take's
// sustained frames) — so any instrument reading this plays the
// chant's own melody, flips and all.
#pragma once

#define CHART_BPM 100.0
#define CHART_TONIC 148.73

typedef struct { double beat, dur; int st; } ChartNote;
typedef struct { const char *name; double leadIn; double beats;
                 int n; const ChartNote *notes; } ChartPhrase;

static const ChartNote f_whole_poem_notes[] = {
    { 0.00, 0.50, -2 },
    { 0.50, 0.50, 0 },
    { 1.00, 0.50, 12 },
    { 1.50, 0.50, 0 },
    { 2.00, 0.50, 10 },
    { 2.50, 0.50, 8 },
    { 3.00, 0.50, 10 },
    { 3.50, 3.00, 0 },
    { 8.00, 1.00, -2 },
    { 9.00, 1.50, 7 },
    { 10.50, 1.00, 0 },
    { 11.50, 1.00, 0 },
    { 12.50, 1.00, -4 },
    { 13.50, 0.50, 10 },
    { 14.00, 1.00, 7 },
    { 15.00, 0.50, 7 },
    { 15.50, 0.50, 5 },
    { 16.00, 2.00, 3 },
    { 20.00, 1.00, 2 },
    { 21.00, 1.00, 5 },
    { 22.00, 2.00, 0 },
    { 24.00, 2.00, 7 },
    { 26.00, 1.50, 12 },
    { 27.50, 1.50, 8 },
    { 29.00, 2.50, -4 },
};

static const ChartPhrase CHART[] = {
    { "f-whole-poem", 0.090, 31.50, 25, f_whole_poem_notes },
};
#define CHART_N 1
