#!/usr/bin/env bash

# boot up the platform in a terminal
# running emacs inside

echo -e "\n\033[1;37m*** Booting the Aesthetic Computer Platform ***\033[0m\n"
cd micro

# clear out everything inside .emacs.d except the .gitignore
cd machine/.emacs.d
# shopt -s extglob
# rm -rf !(.gitignore)
find . -mindepth 1 -maxdepth 1 -not -name '.gitignore' -not -name '.' -not -name '..' | xargs rm -rf > /dev/null 2>&1 
cd ../..

if grep -q docker /proc/1/cgroup; then
  echo "Running inside Docker."
  ./code.sh
else
  echo "Not running inside Docker."
  cd ..
  npm run reset
  npm run build-boot-and-edit
fi


cd -
echo -e "\n\033[1;35m*** Goodbye ***\033[0m\n"

# todo boot up the platform in a
# hosted emacs session
