#!/usr/bin/env node
// bake-c.mjs — render Amazing Grace verse-1 with the C engine
// (pop/big-pictures/c/amazing) as the accompaniment, layered with the
// existing jeffrey-pvc dry vocal stem (amazing-pitched-stretched.mp3)
// and the cached AC signoff stamp. Mirrors pop/hellsine/c/bake-c.mjs
// in spirit: build engine if stale → render → finalize chain → mp3.
//
// Pipeline:
//   1 · build C engine if missing/stale
//   2 · render organ+piano bed   → .amazinhym-c-bed.wav     (84 s)
//   3 · mix bed + vocal (delayed +12 s) + AC stamp tail  → pre.wav
//   4 · brightening master chain → MASTER.wav + .mp3
//
// Durable home is ~/Documents/Shelf/amazing-grace/ ([[feedback_desktop_autocleaned]]).
//
// Usage:  node pop/big-pictures/c/bake-c.mjs [outDir]
//         [-- <extra engine flags, e.g. --bpm 70 --intro 12>]

import { spawnSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import { existsSync, statSync, mkdirSync } from "node:fs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "../../..");
const POP = resolve(REPO, "pop");

let args = process.argv.slice(2);
const sep = args.indexOf("--");
const engineExtra = sep >= 0 ? args.slice(sep + 1) : [];
let positional = sep >= 0 ? args.slice(0, sep) : args.slice();

// --voice <stem|realigned> — picks which jeffrey-pvc stem to mix in.
//   stem      = pop/big-pictures/out/amazing-pitched-stretched.mp3
//               (cli.mjs rubberband 8× output — known broken alignment)
//   realigned = pop/big-pictures/out/amazing-realigned.wav
//               (force-aligned per-syllable to the 70 BPM 3/4 score grid;
//                generated by bin/realign-amazing.mjs)
let VOICE_MODE = "realigned";
const voiceIdx = positional.indexOf("--voice");
if (voiceIdx >= 0) {
  VOICE_MODE = positional[voiceIdx + 1];
  positional.splice(voiceIdx, 2);
}
const outDir = positional[0] ||
  `${homedir()}/Documents/Shelf/amazing-grace`;
mkdirSync(outDir, { recursive: true });

const ENGINE   = `${HERE}/amazinhym`;
const ENGINE_C = `${HERE}/amazinhym.c`;
const BED_WAV  = `${outDir}/.amazinhym-c-bed.wav`;
const PRE_WAV  = `${outDir}/.amazinhym-c-pre.wav`;
const FINAL_WAV = `${outDir}/amazinhym-c-MASTER.wav`;
const FINAL_MP3 = `${outDir}/amazinhym-c.mp3`;
const PRE_BRIGHT_WAV = `${outDir}/amazinhym-c-MASTER-preBright.wav`;

// Vocal + stamp come from the existing big-pictures cli.mjs pipeline.
//   stem       = the broken cli output (rubberband 8× ceiling, misaligned)
//   realigned  = force-aligned-to-grid jeffrey-pvc stem (realign-amazing.mjs)
//   wavewizard = jeffrey's own per-note takes stitched to the grid
//                (assemble-wavewizard.mjs)
const VOCAL = {
  stem:       `${POP}/big-pictures/out/amazing-pitched-stretched.mp3`,
  realigned:  `${POP}/big-pictures/out/amazing-realigned.wav`,
  wavewizard: `${POP}/big-pictures/out/amazing-wavewizard.wav`,
}[VOICE_MODE] ?? `${POP}/big-pictures/out/amazing-realigned.wav`;
const STAMP = `${POP}/big-pictures/out/ac-stamp-crunched.mp3`;
if (!existsSync(VOCAL)) {
  console.error(`[bake-c] missing vocal stem: ${VOCAL}`);
  if (VOICE_MODE === "wavewizard") {
    console.error(`         run: node pop/big-pictures/bin/assemble-wavewizard.mjs`);
    console.error(`         (after recording takes via WaveWizard amazing-grace spec)`);
  } else if (VOICE_MODE === "realigned") {
    console.error(`         run: node pop/big-pictures/bin/realign-amazing.mjs`);
  } else {
    console.error(`         run: node pop/big-pictures/cli.mjs amazing --force`);
  }
  process.exit(1);
}
console.log(`[bake-c] voice = ${VOICE_MODE} (${VOCAL.replace(POP + "/", "pop/")})`);
if (!existsSync(STAMP)) {
  console.error(`[bake-c] missing AC stamp:  ${STAMP}`);
  console.error(`         run: node pop/big-pictures/cli.mjs amazing --force`);
  process.exit(1);
}

const run = (cmd, a, label, opts = {}) => {
  console.log(`\n[bake-c] ${label}`);
  const r = spawnSync(cmd, a, { stdio: "inherit", ...opts });
  if (r.status !== 0) { console.error(`[bake-c] FAILED: ${label}`); process.exit(1); }
};

// 1 — build C engine if missing or stale
const needsBuild = !existsSync(ENGINE) ||
  statSync(ENGINE_C).mtimeMs > statSync(ENGINE).mtimeMs;
if (needsBuild) run("bash", [`${HERE}/build.sh`], "build C engine");

// 2 — render organ+piano bed via C engine
run(ENGINE, ["--out", BED_WAV, ...engineExtra], "C engine render (organ + piano)");

// 3 — mix bed + delayed vocal + tail-appended AC stamp
//
// The C bed is exactly 84.00 s. We delay the vocal by 12.0 s (the
// INTRO_SEC in amazing.c) so the vocal enters AT the start of the waltz
// accompaniment. The AC stamp gets concatenated after a 0.5 s pad past
// the end of the vocal phrase (the stamp itself is ~1.5 s).
//
// Vocal: amazing-pitched-stretched.mp3 (53.82 s dry pitched stretched
//        jeffrey-pvc — score-aligned to 70 BPM 3/4 in G).
// Bed:   amazing-c-bed.wav, full 68 s (intro 2 bars + 21 bars verse +
//        2 bars V→I cadence + ~3 s ring + fade).
//
// Mix balance — bed is busier (drums + 8th hats + shaker + dual sine
// pads + melody sine lead), so vocal stays at 2.4× to win.
const VOCAL_DELAY_MS = 0;       // INTRO_SEC = 0; sing right away
const BED_GAIN  = 0.65;
const VOX_GAIN  = 2.4;
const STAMP_GAIN = 1.0;
const TOTAL_SEC = 62.0;         // matches C engine TOTAL_SEC

// Plagal cadence resolves on bar 23 at ACC_END + BAR = 21*2.571 + 2.571
// = 56.56 s. The stamp lands ~1.5 s into the ring-out so it's heard
// over the chord decay tail.
const STAMP_AT_S = 58.0;

const mixChain = [
  // [0] = bed wav, [1] = vocal mp3, [2] = stamp mp3
  `[0:a]volume=${BED_GAIN}[bed]`,
  `[1:a]adelay=${VOCAL_DELAY_MS}|${VOCAL_DELAY_MS},volume=${VOX_GAIN}[vox]`,
  `[2:a]adelay=${STAMP_AT_S * 1000}|${STAMP_AT_S * 1000},volume=${STAMP_GAIN}[stm]`,
  `[bed][vox][stm]amix=inputs=3:duration=longest:dropout_transition=0:weights='1 1 1':normalize=0,` +
    `atrim=duration=${TOTAL_SEC},afade=t=out:st=${TOTAL_SEC - 2}:d=2[out]`,
].join(";");
run("ffmpeg", ["-y", "-i", BED_WAV, "-i", VOCAL, "-i", STAMP,
               "-filter_complex", mixChain, "-map", "[out]",
               "-ar", "48000", "-c:a", "pcm_f32le", PRE_WAV],
    "mix bed + vocal + stamp (vox forward, bed warm)");

// 4 — pre-bright stash (for A/B against the brightened master)
run("ffmpeg", ["-y", "-i", PRE_WAV,
               "-ar", "44100", "-sample_fmt", "s16",
               PRE_BRIGHT_WAV],
    "pre-bright stash (44.1k 16-bit reference)");

// 5 — BRIGHTENING POLISH CHAIN
//   Static EQ + gentle limiter only. Dropped the dynamic loudnorm
//   single-pass + tight alimiter (limit=0.92 attack=5ms release=80ms)
//   that the previous pass used — that chain pumped on the kick/piano
//   transients and produced audible "silencing" of the vocal between
//   hits. Static gain + a softer limiter (0.97, slow release) gives
//   the same brightness without dynamic side-effects.
const brightChain = [
  "equalizer=f=190:t=q:w=1.0:g=-1",
  "equalizer=f=4200:t=q:w=1.2:g=2.0",
  "highshelf=f=8500:g=3.5",
  "highshelf=f=12500:g=1.8",
  // gentle make-up — bring the mix up without limiter pumping
  "volume=2.5dB",
  // catch peaks only; long release so the limiter doesn't ride on transients
  "alimiter=limit=0.97:attack=8:release=240:level=disabled",
].join(",");
run("ffmpeg", ["-y", "-i", PRE_WAV, "-af", brightChain,
               "-ar", "44100", "-sample_fmt", "s16",
               FINAL_WAV], "brightening polish → -14 LUFS master");

run("ffmpeg", ["-y", "-i", FINAL_WAV, "-codec:a", "libmp3lame", "-b:a", "320k",
               FINAL_MP3], "320k mp3");

spawnSync("open", ["-a", "QuickTime Player", FINAL_MP3]);
console.log(`\n[bake-c] done`);
console.log(`         master: ${FINAL_WAV}`);
console.log(`         mp3:    ${FINAL_MP3}`);
console.log(`         A/B:    ${PRE_BRIGHT_WAV}  (pre-bright reference)`);
