// build-plugin.mjs — wrap refresh.css + refresh.js into the tl-design-refresh plugin + zip.
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const version = process.argv[2] || "1.0.0";
const css = await readFile(resolve(here, "refresh.css"), "utf8");
const js = await readFile(resolve(here, "refresh.js"), "utf8");
const fonts = "https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,400..600;1,14..32,400..600&family=Newsreader:ital,opsz,wght@0,6..72,400..600;1,6..72,400..600&display=swap";

const php = `<?php
/**
 * Plugin Name: TL — Design refresh
 * Description: One design language over thomaslawson.com — two loaded typefaces (Inter + Newsreader), a five-step type scale, one section-header grammar, flat artwork presentation. Layers on top of the TL Fía polish mu-plugin; deactivate to return to it exactly.
 * Version: ${version}
 * Author: Aesthetic Computer
 *
 * Source: gigs/thomaslawson.com/work-fia-edits/refresh-2026-09-27/ (refresh.css, refresh.js, build-plugin.mjs).
 * Do not edit this file by hand; rebuild it.
 */

if (!defined('ABSPATH')) exit;

add_filter('body_class', 'tl_refresh_body_class');
add_action('wp_head',   'tl_refresh_fonts', 1);
add_action('wp_head',   'tl_refresh_css',   PHP_INT_MAX);
add_action('wp_footer', 'tl_refresh_js',    PHP_INT_MAX);

function tl_refresh_body_class($classes) {
    $classes[] = 'tl-refresh';
    global $post;
    if ($post && isset($post->post_name) && strpos($post->post_name, 'beyond-the-studio-') === 0) {
        $classes[] = 'tl-project-detail';
    }
    return $classes;
}

function tl_refresh_fonts() {
    echo '<link rel="preconnect" href="https://fonts.googleapis.com">' . "\\n";
    echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' . "\\n";
    echo '<link rel="stylesheet" id="tl-refresh-fonts" href="${fonts.replace(/&/g, "&amp;")}">' . "\\n";
}

function tl_refresh_css() {
    ?>
<style id="tl-refresh">
${css}
</style>
    <?php
}

function tl_refresh_js() {
    ?>
<script id="tl-refresh-js">
${js}
</script>
    <?php
}
`;
const out = resolve(here, "plugin", "tl-design-refresh");
await rm(resolve(here, "plugin"), { recursive: true, force: true });
await mkdir(out, { recursive: true });
await writeFile(resolve(out, "tl-design-refresh.php"), php);
execFileSync("zip", ["-qr", "tl-design-refresh.zip", "tl-design-refresh"], { cwd: resolve(here, "plugin") });
console.log(resolve(here, "plugin", "tl-design-refresh.zip"));
