// build-plugin.mjs — wrap refresh.css + refresh.js into the tl-design-refresh plugin + zip.
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildCv, summaryJs } from "./build-cv.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const version = process.argv[2] || "1.0.0";
const css = await readFile(resolve(here, "refresh.css"), "utf8");
const cv = await buildCv();
const js = (await readFile(resolve(here, "refresh-data.js"), "utf8")) + summaryJs(cv.summary) + (await readFile(resolve(here, "refresh.js"), "utf8"));
/* Nowdoc bodies for the two server-rendered pages (no PHP interpolation). */
const cvPhp = Object.entries(cv.pages).map(([slug, p]) => {
    if (p.html.includes("\nTLCV")) throw new Error("fragment contains the nowdoc marker");
    return `        '${slug}' => array('title' => '${p.title.replace(/'/g, "\\'")}', 'html' => <<<'TLCV'\n${p.html}\nTLCV\n        ),`;
}).join("\n");
const fonts = "https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,400..600;1,14..32,400..600&family=Newsreader:ital,opsz,wght@0,6..72,400..600;1,6..72,400..600&display=swap";

const php = `<?php
/**
 * Plugin Name: TL — Design refresh
 * Description: One design language over thomaslawson.com — two loaded typefaces (Inter + Newsreader), a five-step type scale, one section-header grammar (image left, text right), flat artwork presentation, and the Curatorial Projects + Exhibitions pages from Tom's CV. Layers on top of the TL Fía polish mu-plugin; deactivate to return to it exactly.
 * Version: ${version}
 * Author: Aesthetic Computer
 *
 * Source: gigs/thomaslawson.com/work-fia-edits/refresh-2026-09-27/ (refresh.css, refresh.js, build-cv.mjs, build-plugin.mjs).
 * Do not edit this file by hand; rebuild it.
 */

if (!defined('ABSPATH')) exit;

add_filter('body_class', 'tl_refresh_body_class');
add_action('wp_head',   'tl_refresh_fonts', 1);
add_action('wp_head',   'tl_refresh_css',   PHP_INT_MAX);
add_action('wp_footer', 'tl_refresh_js',    PHP_INT_MAX);
add_action('template_redirect', 'tl_refresh_cv_route', 0);

/* Curatorial Projects + Exhibitions (Fía, 2026-09-28): two pages built
   from Tom's CV sheet by build-cv.mjs and printed inside the theme. They
   answer only where WordPress has nothing — a real page with the same
   slug always wins. */
function tl_refresh_cv_pages() {
    return array(
${cvPhp}
    );
}
function tl_refresh_cv_slug() {
    $path = isset($_SERVER['REQUEST_URI']) ? (string) parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) : '';
    $slug = trim($path, '/');
    $pages = tl_refresh_cv_pages();
    return isset($pages[$slug]) ? $slug : null;
}
function tl_refresh_cv_route() {
    $slug = tl_refresh_cv_slug();
    if (!$slug || !is_404()) { return; }
    $pages = tl_refresh_cv_pages();
    $page = $pages[$slug];
    global $wp_query;
    $wp_query->is_404 = false;
    status_header(200);
    add_filter('pre_get_document_title', function () use ($page) {
        return $page['title'] . ' – ' . get_bloginfo('name');
    }, 99);
    add_filter('body_class', function ($classes) use ($slug) {
        $classes = array_values(array_diff($classes, array('error404', 'ast-separate-container', 'ast-two-container')));
        $classes[] = 'page';
        $classes[] = 'ast-page-builder-template';
        $classes[] = 'tl-cv-page';
        $classes[] = 'tl-cv-' . $slug;
        return $classes;
    }, 99);
    get_header();
    echo '<div id="primary" class="content-area primary"><main id="main" class="site-main"><article class="page type-page tl-cv-article"><div class="entry-content clear">';
    echo $page['html'];
    echo '</div></article></main></div>';
    get_footer();
    exit;
}

function tl_refresh_body_class($classes) {
    $classes[] = 'tl-refresh';
    global $post;
    if ($post && isset($post->post_name) && strpos($post->post_name, 'beyond-the-studio-') === 0) {
        $classes[] = 'tl-project-detail';
    }
    if ($post && isset($post->post_name) && $post->post_name === 'elementor-428') {
        $classes[] = 'tl-studio-detail';
    }
    return $classes;
}

function tl_refresh_fonts() {
    echo '<link rel="preconnect" href="https://fonts.googleapis.com">' . "\\n";
    echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' . "\\n";
    echo '<link rel="stylesheet" id="tl-refresh-fonts" href="${fonts.replace(/&/g, "&amp;")}">' . "\\n";
}

function tl_refresh_css() {
    ?>
<style id="tl-refresh">
${css}
</style>
    <?php
}

/* Studio periods: Tom's Valise vault as [title, year, medium, dimensions],
   so captions can carry materials. Server-side via the TL Valise plugin's
   stored key (never sent to the browser); cached 12h. */
function tl_refresh_valise_works() {
    if (!function_exists('tl_valise_api_key') || !tl_valise_api_key()) { return array(); }
    $cached = get_transient('tl_refresh_valise_v1');
    if ($cached !== false && !(current_user_can('manage_options') && isset($_GET['valise_refresh']))) { return $cached; }
    $out = array(); $url = TL_VALISE_API_BASE . '/artworks?limit=100'; $guard = 0;
    while ($url && $guard < 40) {
        $resp = wp_remote_get($url, array('headers' => array('Authorization' => 'Bearer ' . tl_valise_api_key(), 'Accept' => 'application/json'), 'timeout' => 20));
        if (is_wp_error($resp) || wp_remote_retrieve_response_code($resp) !== 200) { break; }
        $body = json_decode(wp_remote_retrieve_body($resp), true);
        if (empty($body['data']) || !is_array($body['data'])) { break; }
        foreach ($body['data'] as $w) {
            $t = isset($w['title']) ? trim((string) $w['title']) : '';
            if ($t === '') { continue; }
            $out[] = array($t, isset($w['year']) ? (string) $w['year'] : '', isset($w['medium']) ? trim((string) $w['medium']) : '', isset($w['dimensions']) ? trim((string) $w['dimensions']) : '');
        }
        $url = isset($body['page']['next']) ? $body['page']['next'] : null;
        $guard++;
    }
    set_transient('tl_refresh_valise_v1', $out, $out ? 12 * HOUR_IN_SECONDS : 10 * MINUTE_IN_SECONDS);
    return $out;
}

function tl_refresh_js() {
    if (in_array('tl-studio-detail', get_body_class(), true)) {
        $works = tl_refresh_valise_works();
        echo '<script id="tl-refresh-valise">window.TL_VALISE = ' . wp_json_encode($works) . ";</script>\n";
        echo '<!-- tl-refresh-valise: ' . count($works) . " works -->\n";
    }
    ?>
<script id="tl-refresh-js">
${js}
</script>
    <?php
}
`;
const out = resolve(here, "plugin", "tl-design-refresh");
await rm(resolve(here, "plugin"), { recursive: true, force: true });
await mkdir(out, { recursive: true });
await writeFile(resolve(out, "tl-design-refresh.php"), php);
execFileSync("zip", ["-qr", "tl-design-refresh.zip", "tl-design-refresh"], { cwd: resolve(here, "plugin") });
console.log(resolve(here, "plugin", "tl-design-refresh.zip"));
