name: Spider Lily Daily Build

on:
  # Run daily at 2 AM UTC (adjust timezone as needed)
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual trigger from GitHub UI
  workflow_dispatch:
    inputs:
      package:
        description: 'Package for distribution'
        required: false
        type: boolean
        default: false
      upload:
        description: 'Upload to cloud storage'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build Spider Lily
    runs-on: self-hosted  # Uses the VM we set up
    
    steps:
      - name: Load secrets
        shell: pwsh
        run: |
          # Load Perforce credentials from environment
          $env:P4PORT = "${{ secrets.P4_SERVER }}"
          $env:P4USER = "${{ secrets.P4_USER }}"
          $env:P4PASSWD = "${{ secrets.P4_PASSWORD }}"
          $env:P4CLIENT = "${{ secrets.P4_WORKSPACE }}"
          
          # Verify connection
          p4 info
      
      - name: Run daily build
        shell: pwsh
        run: |
          $packageFlag = if ("${{ github.event.inputs.package }}" -eq "true") { "-Package" } else { "" }
          $uploadFlag = if ("${{ github.event.inputs.upload }}" -eq "true") { "-Upload" } else { "" }
          
          & "C:\scripts\daily-build.ps1" $packageFlag $uploadFlag
      
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: spiderlily-build-${{ github.run_number }}
          path: C:\Builds\*\BUILD_INFO.txt
          retention-days: 30
      
      - name: Notify on failure
        if: failure()
        shell: pwsh
        run: |
          Write-Host "Build failed! Check the logs for details."
          # TODO: Add notification to Discord/Slack/email
