# build-shelf-data.py — Bookshelf item captions from Tom's CV (Fía, 2026-09-27).
# Match only through an item's primary (cover) link; a link shared by several
# items on one page (a copy-paste leftover) matches nothing. A secondary link
# that points at a *different* CV entry is a wrong link and is dropped. Generic
# CV titles ("Thomas Lawson") never replace the site's own. Writes
# refresh-data.js + a review CSV for Fía.
import csv, json, re
d = json.load(open("fia-2026-09-27/shelves.json"))
cv = list(csv.DictReader(open("fia-2026-09-27/tl-cv.csv")))
def norm(u): return re.sub(r"[?#].*$","",(u or "").strip()).rstrip("/").replace("http://","https://").replace("://www.","://").lower()
byurl = {}
for r in cv:
    for k in ("Page on TL site (sometimes PDF)","Website(s)"):
        for u in re.split(r"\s+", r[k] or ""):
            if u.startswith("http"): byurl.setdefault(norm(u), []).append(r)
KEEP = {"REALLIFE","MOCA","LACE","LAXART","CAE","PS1","USA","UK","LA","NY","TV","BBC","CCA","SVA","ICA","II","III","IV","MIT","NJ","MA","CA"}
def uncap_words(s):
    return re.sub(r"\b[A-Z][A-Z'’.-]{2,}\b", lambda m: m.group(0) if m.group(0).strip(".") in KEEP else m.group(0).capitalize(), s)
def clean(s): return re.sub(r"\s+", " ", (s or "").replace(" ,", ",")).strip().strip(",").strip()
STOP = set("the and with for from about thomas lawson review interview profile cover".split())
def words(s): return {w for w in re.findall(r"[a-z]{4,}", s.lower()) if w not in STOP}
def key(src): return re.sub(r"-\d+x\d+(?=\.\w+$)", "", src.split("/")[-1]).lower()
out, review = {}, []
MONTH = r"(January|February|March|April|May|June|July|August|September|October|November|December)"
for slug, items in d.items():
    shared = {}
    for it in items:
        if it["links"]: shared[norm(it["links"][0])] = shared.get(norm(it["links"][0]), 0) + 1
    for n, it in enumerate(items):
        heads = [h for h in it["heads"] if h.strip("-– ")]
        title0 = heads[0] if heads else ""
        meta0 = heads[1] if len(heads) > 1 else ""
        primary = it["links"][0] if it["links"] else ""
        rows = byurl.get(norm(primary), [])
        row = rows[0] if len(rows) == 1 and shared.get(norm(primary), 0) == 1 else None
        suspect = [l for l in it["links"][1:]
                   if norm(l) != norm(primary) and byurl.get(norm(l))
                   and all(r is not row for r in byurl[norm(l)])]
        if shared.get(norm(primary), 0) > 1: suspect.append(primary + "  (shared by several items)")
        if row:
            loc = clean(uncap_words(row["Location/Publication"]))
            date = clean(("" if row["Month"].lower() == "current" else row["Month"]) + " " + ("" if row["Year"] == "current" else row["Year"]))
            title = clean(uncap_words(row["Title"])) if words(row["Title"]) else title0
            if re.search(MONTH + r" \d{1,2}, \d{4}", meta0):   # keep an exact day date
                meta = f"{loc}, {meta0}" if loc.lower() not in meta0.lower() else meta0
            else:
                meta = f"{loc}, {date}" if date and date not in loc else loc
        else:
            title, meta = title0, meta0
        k = key(it["img"])
        out[k] = {"s": slug, "t": title, "m": meta, "h": primary, "fix": bool(suspect)}
        review.append([slug, n + 1, title0, meta0, title, meta, "CV" if row else "", primary, "; ".join(suspect)])
open("refresh-data.js", "w").write("/* Bookshelf captions from Tom's CV — generated by fia-2026-09-27/build-shelf-data.py */\nwindow.TL_SHELVES = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n")
with open("fia-2026-09-27/bookshelf-captions-review.csv", "w", newline="") as f:
    w = csv.writer(f); w.writerow(["page","#","title (site)","caption (site)","title (new)","caption (new)","source","link","other links dropped (wrong target)"]); w.writerows(review)
print(len(out), "items;", sum(1 for r in review if r[6]), "from CV;", sum(1 for r in review if r[8]), "with wrong extra links")
for r in review[:3] + [x for x in review if x[0]=="bookshelf_writingsabouttl"][:3] + [x for x in review if x[0]=="elementor-395"][:2] + [x for x in review if x[8]][:3]:
    print(" ", r[0][:18], "|", r[4][:60], "|", r[5][:70], "| drop:", r[8].split("/")[-1][:40])
