// score.h — generated by c/bake.mjs from melody.json. do not hand-edit.
#define SCORE_BPM 112
#define N_WORDS 3
#define N_VARIANTS 7
#define MAX_ROSTER 1

static const int BPW[N_WORDS] = {4, 2, 2};
static const int VARIANT_NOTES[N_VARIANTS][N_WORDS] = {
  {62, 69, 66}, // rise-rest
  {64, 69, 62}, // step-home
  {66, 71, 69}, // lift
  {71, 69, 66}, // bach-circle
  {66, 69, 74}, // bach-arc
  {74, 71, 62}, // bach-fall
  {69, 74, 71}, // climax
};

typedef struct { const char *section; int bars; int reps; const char *feel; } Sec;
static const Sec STRUCTURE[] = {
  {"intro", 10, 1, "soft"},
  {"hook", 4, 4, "full"},
  {"verse", 8, 1, "thin"},
  {"hook", 4, 4, "full"},
  {"verse", 8, 1, "sparse"},
  {"bridge", 4, 1, "breakdown"},
  {"stop", 1, 1, "claps-only"},
  {"hook", 4, 4, "full"},
  {"outro", 8, 1, "fade"},
};
#define N_SECS 9

typedef struct { int bars; int root; int minor; } ChordDef;
static const ChordDef PROG[] = {
  {2, 62, 0},
  {2, 69, 0},
  {2, 71, 1},
  {2, 67, 0},
};
#define N_PROG 4
#define PROG_BARS 8

static const int ROSTER_N[N_WORDS] = {1, 1, 1};
// raw tier — the utterance itself, untouched ("by the book" stitch)
static const char *VOC_RAW[N_WORDS][MAX_ROSTER] = {
  {"vocals/america-0-raw.wav"},
  {"vocals/computer-0-raw.wav"},
  {"vocals/dora-0-raw.wav"},
};
// plain tier — autotuned to the variant note, nothing else
static const char *VOC_PLAIN[N_WORDS][MAX_ROSTER][N_VARIANTS] = {
  {
    {"vocals/america-0-v0-plain.wav", "vocals/america-0-v1-plain.wav", "vocals/america-0-v2-plain.wav", "vocals/america-0-v3-plain.wav", "vocals/america-0-v4-plain.wav", "vocals/america-0-v5-plain.wav", "vocals/america-0-v6-plain.wav"},
  },
  {
    {"vocals/computer-0-v0-plain.wav", "vocals/computer-0-v1-plain.wav", "vocals/computer-0-v2-plain.wav", "vocals/computer-0-v3-plain.wav", "vocals/computer-0-v4-plain.wav", "vocals/computer-0-v5-plain.wav", "vocals/computer-0-v6-plain.wav"},
  },
  {
    {"vocals/dora-0-v0-plain.wav", "vocals/dora-0-v1-plain.wav", "vocals/dora-0-v2-plain.wav", "vocals/dora-0-v3-plain.wav", "vocals/dora-0-v4-plain.wav", "vocals/dora-0-v5-plain.wav", "vocals/dora-0-v6-plain.wav"},
  },
};
// full tier — stretch + decap + whisper, the canonical character
static const char *VOC_FULL[N_WORDS][MAX_ROSTER][N_VARIANTS] = {
  {
    {"vocals/america-0-v0.wav", "vocals/america-0-v1.wav", "vocals/america-0-v2.wav", "vocals/america-0-v3.wav", "vocals/america-0-v4.wav", "vocals/america-0-v5.wav", "vocals/america-0-v6.wav"},
  },
  {
    {"vocals/computer-0-v0.wav", "vocals/computer-0-v1.wav", "vocals/computer-0-v2.wav", "vocals/computer-0-v3.wav", "vocals/computer-0-v4.wav", "vocals/computer-0-v5.wav", "vocals/computer-0-v6.wav"},
  },
  {
    {"vocals/dora-0-v0.wav", "vocals/dora-0-v1.wav", "vocals/dora-0-v2.wav", "vocals/dora-0-v3.wav", "vocals/dora-0-v4.wav", "vocals/dora-0-v5.wav", "vocals/dora-0-v6.wav"},
  },
};

// jeffrey syllable chant (verse layer)
#define N_SYL 8
#define N_SYLT 12
static const int SYL_NOTES[N_SYLT] = {62, 66, 67, 69, 71, 73, 74, 76, 78, 79, 81, 83};
static const char *SYL_PATHS[N_SYL ? N_SYL : 1][N_SYLT] = {
  {"vocals/syl-a-t62.wav", "vocals/syl-a-t66.wav", "vocals/syl-a-t67.wav", "vocals/syl-a-t69.wav", "vocals/syl-a-t71.wav", "vocals/syl-a-t73.wav", "vocals/syl-a-t74.wav", "vocals/syl-a-t76.wav", "vocals/syl-a-t78.wav", "vocals/syl-a-t79.wav", "vocals/syl-a-t81.wav", "vocals/syl-a-t83.wav"},
  {"vocals/syl-me-t62.wav", "vocals/syl-me-t66.wav", "vocals/syl-me-t67.wav", "vocals/syl-me-t69.wav", "vocals/syl-me-t71.wav", "vocals/syl-me-t73.wav", "vocals/syl-me-t74.wav", "vocals/syl-me-t76.wav", "vocals/syl-me-t78.wav", "vocals/syl-me-t79.wav", "vocals/syl-me-t81.wav", "vocals/syl-me-t83.wav"},
  {"vocals/syl-ri-t62.wav", "vocals/syl-ri-t66.wav", "vocals/syl-ri-t67.wav", "vocals/syl-ri-t69.wav", "vocals/syl-ri-t71.wav", "vocals/syl-ri-t73.wav", "vocals/syl-ri-t74.wav", "vocals/syl-ri-t76.wav", "vocals/syl-ri-t78.wav", "vocals/syl-ri-t79.wav", "vocals/syl-ri-t81.wav", "vocals/syl-ri-t83.wav"},
  {"vocals/syl-com-t62.wav", "vocals/syl-com-t66.wav", "vocals/syl-com-t67.wav", "vocals/syl-com-t69.wav", "vocals/syl-com-t71.wav", "vocals/syl-com-t73.wav", "vocals/syl-com-t74.wav", "vocals/syl-com-t76.wav", "vocals/syl-com-t78.wav", "vocals/syl-com-t79.wav", "vocals/syl-com-t81.wav", "vocals/syl-com-t83.wav"},
  {"vocals/syl-pu-t62.wav", "vocals/syl-pu-t66.wav", "vocals/syl-pu-t67.wav", "vocals/syl-pu-t69.wav", "vocals/syl-pu-t71.wav", "vocals/syl-pu-t73.wav", "vocals/syl-pu-t74.wav", "vocals/syl-pu-t76.wav", "vocals/syl-pu-t78.wav", "vocals/syl-pu-t79.wav", "vocals/syl-pu-t81.wav", "vocals/syl-pu-t83.wav"},
  {"vocals/syl-ta-t62.wav", "vocals/syl-ta-t66.wav", "vocals/syl-ta-t67.wav", "vocals/syl-ta-t69.wav", "vocals/syl-ta-t71.wav", "vocals/syl-ta-t73.wav", "vocals/syl-ta-t74.wav", "vocals/syl-ta-t76.wav", "vocals/syl-ta-t78.wav", "vocals/syl-ta-t79.wav", "vocals/syl-ta-t81.wav", "vocals/syl-ta-t83.wav"},
  {"vocals/syl-do-t62.wav", "vocals/syl-do-t66.wav", "vocals/syl-do-t67.wav", "vocals/syl-do-t69.wav", "vocals/syl-do-t71.wav", "vocals/syl-do-t73.wav", "vocals/syl-do-t74.wav", "vocals/syl-do-t76.wav", "vocals/syl-do-t78.wav", "vocals/syl-do-t79.wav", "vocals/syl-do-t81.wav", "vocals/syl-do-t83.wav"},
  {"vocals/syl-ra-t62.wav", "vocals/syl-ra-t66.wav", "vocals/syl-ra-t67.wav", "vocals/syl-ra-t69.wav", "vocals/syl-ra-t71.wav", "vocals/syl-ra-t73.wav", "vocals/syl-ra-t74.wav", "vocals/syl-ra-t76.wav", "vocals/syl-ra-t78.wav", "vocals/syl-ra-t79.wav", "vocals/syl-ra-t81.wav", "vocals/syl-ra-t83.wav"},
};
// second voice (computer) chanting the same syllables, same notes
static const char *SYL_PATHS_C[N_SYL ? N_SYL : 1][N_SYLT] = {
  {"vocals/sylc-a-t62.wav", "vocals/sylc-a-t66.wav", "vocals/sylc-a-t67.wav", "vocals/sylc-a-t69.wav", "vocals/sylc-a-t71.wav", "vocals/sylc-a-t73.wav", "vocals/sylc-a-t74.wav", "vocals/sylc-a-t76.wav", "vocals/sylc-a-t78.wav", "vocals/sylc-a-t79.wav", "vocals/sylc-a-t81.wav", "vocals/sylc-a-t83.wav"},
  {"vocals/sylc-me-t62.wav", "vocals/sylc-me-t66.wav", "vocals/sylc-me-t67.wav", "vocals/sylc-me-t69.wav", "vocals/sylc-me-t71.wav", "vocals/sylc-me-t73.wav", "vocals/sylc-me-t74.wav", "vocals/sylc-me-t76.wav", "vocals/sylc-me-t78.wav", "vocals/sylc-me-t79.wav", "vocals/sylc-me-t81.wav", "vocals/sylc-me-t83.wav"},
  {"vocals/sylc-ri-t62.wav", "vocals/sylc-ri-t66.wav", "vocals/sylc-ri-t67.wav", "vocals/sylc-ri-t69.wav", "vocals/sylc-ri-t71.wav", "vocals/sylc-ri-t73.wav", "vocals/sylc-ri-t74.wav", "vocals/sylc-ri-t76.wav", "vocals/sylc-ri-t78.wav", "vocals/sylc-ri-t79.wav", "vocals/sylc-ri-t81.wav", "vocals/sylc-ri-t83.wav"},
  {"vocals/sylc-com-t62.wav", "vocals/sylc-com-t66.wav", "vocals/sylc-com-t67.wav", "vocals/sylc-com-t69.wav", "vocals/sylc-com-t71.wav", "vocals/sylc-com-t73.wav", "vocals/sylc-com-t74.wav", "vocals/sylc-com-t76.wav", "vocals/sylc-com-t78.wav", "vocals/sylc-com-t79.wav", "vocals/sylc-com-t81.wav", "vocals/sylc-com-t83.wav"},
  {"vocals/sylc-pu-t62.wav", "vocals/sylc-pu-t66.wav", "vocals/sylc-pu-t67.wav", "vocals/sylc-pu-t69.wav", "vocals/sylc-pu-t71.wav", "vocals/sylc-pu-t73.wav", "vocals/sylc-pu-t74.wav", "vocals/sylc-pu-t76.wav", "vocals/sylc-pu-t78.wav", "vocals/sylc-pu-t79.wav", "vocals/sylc-pu-t81.wav", "vocals/sylc-pu-t83.wav"},
  {"vocals/sylc-ta-t62.wav", "vocals/sylc-ta-t66.wav", "vocals/sylc-ta-t67.wav", "vocals/sylc-ta-t69.wav", "vocals/sylc-ta-t71.wav", "vocals/sylc-ta-t73.wav", "vocals/sylc-ta-t74.wav", "vocals/sylc-ta-t76.wav", "vocals/sylc-ta-t78.wav", "vocals/sylc-ta-t79.wav", "vocals/sylc-ta-t81.wav", "vocals/sylc-ta-t83.wav"},
  {"vocals/sylc-do-t62.wav", "vocals/sylc-do-t66.wav", "vocals/sylc-do-t67.wav", "vocals/sylc-do-t69.wav", "vocals/sylc-do-t71.wav", "vocals/sylc-do-t73.wav", "vocals/sylc-do-t74.wav", "vocals/sylc-do-t76.wav", "vocals/sylc-do-t78.wav", "vocals/sylc-do-t79.wav", "vocals/sylc-do-t81.wav", "vocals/sylc-do-t83.wav"},
  {"vocals/sylc-ra-t62.wav", "vocals/sylc-ra-t66.wav", "vocals/sylc-ra-t67.wav", "vocals/sylc-ra-t69.wav", "vocals/sylc-ra-t71.wav", "vocals/sylc-ra-t73.wav", "vocals/sylc-ra-t74.wav", "vocals/sylc-ra-t76.wav", "vocals/sylc-ra-t78.wav", "vocals/sylc-ra-t79.wav", "vocals/sylc-ra-t81.wav", "vocals/sylc-ra-t83.wav"},
};
