// score.h — generated by c/bake.mjs from melody.json. do not hand-edit.
#define SCORE_BPM 112
#define N_WORDS 3
#define N_VARIANTS 7
#define MAX_ROSTER 1

static const int BPW[N_WORDS] = {4, 2, 2};
static const int VARIANT_NOTES[N_VARIANTS][N_WORDS] = {
  {62, 69, 66}, // rise-rest
  {64, 69, 62}, // step-home
  {66, 71, 69}, // lift
  {71, 69, 66}, // bach-circle
  {66, 69, 74}, // bach-arc
  {74, 71, 62}, // bach-fall
  {69, 74, 71}, // climax
};

typedef struct { const char *section; int bars; int reps; const char *feel; } Sec;
static const Sec STRUCTURE[] = {
  {"intro", 10, 1, "soft"},
  {"hook", 4, 4, "full"},
  {"verse", 8, 1, "thin"},
  {"hook", 4, 4, "full"},
  {"verse", 8, 1, "sparse"},
  {"bridge", 4, 1, "breakdown"},
  {"stop", 1, 1, "claps-only"},
  {"hook", 4, 4, "full"},
  {"outro", 8, 1, "fade"},
};
#define N_SECS 9

typedef struct { int bars; int root; int minor; } ChordDef;
static const ChordDef PROG[] = {
  {2, 62, 0},
  {2, 69, 0},
  {2, 71, 1},
  {2, 67, 0},
};
#define N_PROG 4
#define PROG_BARS 8

static const int ROSTER_N[N_WORDS] = {1, 1, 1};
// raw tier — the utterance itself, untouched ("by the book" stitch)
static const char *VOC_RAW[N_WORDS][MAX_ROSTER] = {
  {"vocals/america-0-raw.wav"},
  {"vocals/computer-0-raw.wav"},
  {"vocals/dora-0-raw.wav"},
};
// plain tier — autotuned to the variant note, nothing else
static const char *VOC_PLAIN[N_WORDS][MAX_ROSTER][N_VARIANTS] = {
  {
    {"vocals/america-0-v0-plain.wav", "vocals/america-0-v1-plain.wav", "vocals/america-0-v2-plain.wav", "vocals/america-0-v3-plain.wav", "vocals/america-0-v4-plain.wav", "vocals/america-0-v5-plain.wav", "vocals/america-0-v6-plain.wav"},
  },
  {
    {"vocals/computer-0-v0-plain.wav", "vocals/computer-0-v1-plain.wav", "vocals/computer-0-v2-plain.wav", "vocals/computer-0-v3-plain.wav", "vocals/computer-0-v4-plain.wav", "vocals/computer-0-v5-plain.wav", "vocals/computer-0-v6-plain.wav"},
  },
  {
    {"vocals/dora-0-v0-plain.wav", "vocals/dora-0-v1-plain.wav", "vocals/dora-0-v2-plain.wav", "vocals/dora-0-v3-plain.wav", "vocals/dora-0-v4-plain.wav", "vocals/dora-0-v5-plain.wav", "vocals/dora-0-v6-plain.wav"},
  },
};
// full tier — stretch + decap + whisper, the canonical character
static const char *VOC_FULL[N_WORDS][MAX_ROSTER][N_VARIANTS] = {
  {
    {"vocals/america-0-v0.wav", "vocals/america-0-v1.wav", "vocals/america-0-v2.wav", "vocals/america-0-v3.wav", "vocals/america-0-v4.wav", "vocals/america-0-v5.wav", "vocals/america-0-v6.wav"},
  },
  {
    {"vocals/computer-0-v0.wav", "vocals/computer-0-v1.wav", "vocals/computer-0-v2.wav", "vocals/computer-0-v3.wav", "vocals/computer-0-v4.wav", "vocals/computer-0-v5.wav", "vocals/computer-0-v6.wav"},
  },
  {
    {"vocals/dora-0-v0.wav", "vocals/dora-0-v1.wav", "vocals/dora-0-v2.wav", "vocals/dora-0-v3.wav", "vocals/dora-0-v4.wav", "vocals/dora-0-v5.wav", "vocals/dora-0-v6.wav"},
  },
};

// jeffrey syllable chant (verse layer)
#define N_SYL 7
#define N_SYLT 12
static const int SYL_NOTES[N_SYLT] = {62, 66, 67, 69, 71, 73, 74, 76, 78, 79, 81, 83};
static const char *SYL_PATHS[N_SYL ? N_SYL : 1][N_SYLT] = {
  {"vocals/syl-ah-t62.wav", "vocals/syl-ah-t66.wav", "vocals/syl-ah-t67.wav", "vocals/syl-ah-t69.wav", "vocals/syl-ah-t71.wav", "vocals/syl-ah-t73.wav", "vocals/syl-ah-t74.wav", "vocals/syl-ah-t76.wav", "vocals/syl-ah-t78.wav", "vocals/syl-ah-t79.wav", "vocals/syl-ah-t81.wav", "vocals/syl-ah-t83.wav"},
  {"vocals/syl-mer-t62.wav", "vocals/syl-mer-t66.wav", "vocals/syl-mer-t67.wav", "vocals/syl-mer-t69.wav", "vocals/syl-mer-t71.wav", "vocals/syl-mer-t73.wav", "vocals/syl-mer-t74.wav", "vocals/syl-mer-t76.wav", "vocals/syl-mer-t78.wav", "vocals/syl-mer-t79.wav", "vocals/syl-mer-t81.wav", "vocals/syl-mer-t83.wav"},
  {"vocals/syl-ick-t62.wav", "vocals/syl-ick-t66.wav", "vocals/syl-ick-t67.wav", "vocals/syl-ick-t69.wav", "vocals/syl-ick-t71.wav", "vocals/syl-ick-t73.wav", "vocals/syl-ick-t74.wav", "vocals/syl-ick-t76.wav", "vocals/syl-ick-t78.wav", "vocals/syl-ick-t79.wav", "vocals/syl-ick-t81.wav", "vocals/syl-ick-t83.wav"},
  {"vocals/syl-ahmp-t62.wav", "vocals/syl-ahmp-t66.wav", "vocals/syl-ahmp-t67.wav", "vocals/syl-ahmp-t69.wav", "vocals/syl-ahmp-t71.wav", "vocals/syl-ahmp-t73.wav", "vocals/syl-ahmp-t74.wav", "vocals/syl-ahmp-t76.wav", "vocals/syl-ahmp-t78.wav", "vocals/syl-ahmp-t79.wav", "vocals/syl-ahmp-t81.wav", "vocals/syl-ahmp-t83.wav"},
  {"vocals/syl-uter-t62.wav", "vocals/syl-uter-t66.wav", "vocals/syl-uter-t67.wav", "vocals/syl-uter-t69.wav", "vocals/syl-uter-t71.wav", "vocals/syl-uter-t73.wav", "vocals/syl-uter-t74.wav", "vocals/syl-uter-t76.wav", "vocals/syl-uter-t78.wav", "vocals/syl-uter-t79.wav", "vocals/syl-uter-t81.wav", "vocals/syl-uter-t83.wav"},
  {"vocals/syl-do-t62.wav", "vocals/syl-do-t66.wav", "vocals/syl-do-t67.wav", "vocals/syl-do-t69.wav", "vocals/syl-do-t71.wav", "vocals/syl-do-t73.wav", "vocals/syl-do-t74.wav", "vocals/syl-do-t76.wav", "vocals/syl-do-t78.wav", "vocals/syl-do-t79.wav", "vocals/syl-do-t81.wav", "vocals/syl-do-t83.wav"},
  {"vocals/syl-rah-t62.wav", "vocals/syl-rah-t66.wav", "vocals/syl-rah-t67.wav", "vocals/syl-rah-t69.wav", "vocals/syl-rah-t71.wav", "vocals/syl-rah-t73.wav", "vocals/syl-rah-t74.wav", "vocals/syl-rah-t76.wav", "vocals/syl-rah-t78.wav", "vocals/syl-rah-t79.wav", "vocals/syl-rah-t81.wav", "vocals/syl-rah-t83.wav"},
};
// second voice (computer) chanting the same syllables, same notes
static const char *SYL_PATHS_C[N_SYL ? N_SYL : 1][N_SYLT] = {
  {"vocals/sylc-ah-t62.wav", "vocals/sylc-ah-t66.wav", "vocals/sylc-ah-t67.wav", "vocals/sylc-ah-t69.wav", "vocals/sylc-ah-t71.wav", "vocals/sylc-ah-t73.wav", "vocals/sylc-ah-t74.wav", "vocals/sylc-ah-t76.wav", "vocals/sylc-ah-t78.wav", "vocals/sylc-ah-t79.wav", "vocals/sylc-ah-t81.wav", "vocals/sylc-ah-t83.wav"},
  {"vocals/sylc-mer-t62.wav", "vocals/sylc-mer-t66.wav", "vocals/sylc-mer-t67.wav", "vocals/sylc-mer-t69.wav", "vocals/sylc-mer-t71.wav", "vocals/sylc-mer-t73.wav", "vocals/sylc-mer-t74.wav", "vocals/sylc-mer-t76.wav", "vocals/sylc-mer-t78.wav", "vocals/sylc-mer-t79.wav", "vocals/sylc-mer-t81.wav", "vocals/sylc-mer-t83.wav"},
  {"vocals/sylc-ick-t62.wav", "vocals/sylc-ick-t66.wav", "vocals/sylc-ick-t67.wav", "vocals/sylc-ick-t69.wav", "vocals/sylc-ick-t71.wav", "vocals/sylc-ick-t73.wav", "vocals/sylc-ick-t74.wav", "vocals/sylc-ick-t76.wav", "vocals/sylc-ick-t78.wav", "vocals/sylc-ick-t79.wav", "vocals/sylc-ick-t81.wav", "vocals/sylc-ick-t83.wav"},
  {"vocals/sylc-ahmp-t62.wav", "vocals/sylc-ahmp-t66.wav", "vocals/sylc-ahmp-t67.wav", "vocals/sylc-ahmp-t69.wav", "vocals/sylc-ahmp-t71.wav", "vocals/sylc-ahmp-t73.wav", "vocals/sylc-ahmp-t74.wav", "vocals/sylc-ahmp-t76.wav", "vocals/sylc-ahmp-t78.wav", "vocals/sylc-ahmp-t79.wav", "vocals/sylc-ahmp-t81.wav", "vocals/sylc-ahmp-t83.wav"},
  {"vocals/sylc-uter-t62.wav", "vocals/sylc-uter-t66.wav", "vocals/sylc-uter-t67.wav", "vocals/sylc-uter-t69.wav", "vocals/sylc-uter-t71.wav", "vocals/sylc-uter-t73.wav", "vocals/sylc-uter-t74.wav", "vocals/sylc-uter-t76.wav", "vocals/sylc-uter-t78.wav", "vocals/sylc-uter-t79.wav", "vocals/sylc-uter-t81.wav", "vocals/sylc-uter-t83.wav"},
  {"vocals/sylc-do-t62.wav", "vocals/sylc-do-t66.wav", "vocals/sylc-do-t67.wav", "vocals/sylc-do-t69.wav", "vocals/sylc-do-t71.wav", "vocals/sylc-do-t73.wav", "vocals/sylc-do-t74.wav", "vocals/sylc-do-t76.wav", "vocals/sylc-do-t78.wav", "vocals/sylc-do-t79.wav", "vocals/sylc-do-t81.wav", "vocals/sylc-do-t83.wav"},
  {"vocals/sylc-rah-t62.wav", "vocals/sylc-rah-t66.wav", "vocals/sylc-rah-t67.wav", "vocals/sylc-rah-t69.wav", "vocals/sylc-rah-t71.wav", "vocals/sylc-rah-t73.wav", "vocals/sylc-rah-t74.wav", "vocals/sylc-rah-t76.wav", "vocals/sylc-rah-t78.wav", "vocals/sylc-rah-t79.wav", "vocals/sylc-rah-t81.wav", "vocals/sylc-rah-t83.wav"},
};
