<?php
/**
 * Plugin Name: TL — Design refresh
 * Description: One design language over thomaslawson.com — two loaded typefaces (Inter + Newsreader), a five-step type scale, one section-header grammar, flat artwork presentation. Layers on top of the TL Fía polish mu-plugin; deactivate to return to it exactly.
 * Version: 1.0.0
 * Author: Aesthetic Computer
 *
 * Source: gigs/thomaslawson.com/work-fia-edits/refresh-2026-09-27/ (refresh.css, refresh.js, build-plugin.mjs).
 * Do not edit this file by hand; rebuild it.
 */

if (!defined('ABSPATH')) exit;

add_filter('body_class', 'tl_refresh_body_class');
add_action('wp_head',   'tl_refresh_fonts', 1);
add_action('wp_head',   'tl_refresh_css',   PHP_INT_MAX);
add_action('wp_footer', 'tl_refresh_js',    PHP_INT_MAX);

function tl_refresh_body_class($classes) {
    $classes[] = 'tl-refresh';
    global $post;
    if ($post && isset($post->post_name) && strpos($post->post_name, 'beyond-the-studio-') === 0) {
        $classes[] = 'tl-project-detail';
    }
    if ($post && isset($post->post_name) && $post->post_name === 'elementor-428') {
        $classes[] = 'tl-studio-detail';
    }
    return $classes;
}

function tl_refresh_fonts() {
    echo '<link rel="preconnect" href="https://fonts.googleapis.com">' . "\n";
    echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>' . "\n";
    echo '<link rel="stylesheet" id="tl-refresh-fonts" href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,400..600;1,14..32,400..600&amp;family=Newsreader:ital,opsz,wght@0,6..72,400..600;1,6..72,400..600&amp;display=swap">' . "\n";
}

function tl_refresh_css() {
    ?>
<style id="tl-refresh">
/* ================================================================== *
 * TL design refresh — 2026-09-27
 *
 * One design language over the whole site, layered on top of the Fía
 * polish plugin (which stays as-is). The polish work fixed things page
 * by page; this layer sets the system those fixes should have shared:
 *
 *   - Two typefaces, both actually loaded as web fonts:
 *       Inter       — titles, navigation, captions, labels
 *       Newsreader  — reading text
 *     (Gotham + Felix Titling were named but never loaded, so every
 *     visitor saw whatever happened to be installed; Poppins, Roboto
 *     and Adobe Jenson filled the gaps page by page.)
 *   - A five-step type scale; refresh.js snaps every Elementor heading
 *     onto it by role (data-tl-role) instead of 45 ad-hoc sizes.
 *   - One section header: image band, then title, then intro, all on
 *     the same measure — no type sitting on photographs.
 *   - Flat artwork presentation: no drop-shadow frames, quiet rules.
 *
 * Every selector is prefixed with body.tl-refresh:not(#tl) — the
 * :not(#id) lifts it to ID specificity so it outranks the polish
 * plugin's page-id rules without an arms race of longer selectors.
 * ================================================================== */

body.tl-refresh:not(#tl) {
    --tl-paper: #fff9ef;
    --tl-ink: #1d1c1a;
    --tl-muted: #6c665d;
    --tl-rule: #ddd4c4;
    --tl-accent: #9b2f5f;
    --tl-sans: "Inter", "Helvetica Neue", Arial, sans-serif;
    --tl-serif: "Newsreader", Georgia, "Times New Roman", serif;
    --tl-measure: 40rem;
    --tl-wide: 68rem;
    --tl-gutter: clamp(1.25rem, 5vw, 3rem);

    /* Retarget the polish plugin's own variables at the new faces. */
    --tl-display-face: var(--tl-sans);
    --tl-body-face: var(--tl-serif);

    background: var(--tl-paper) !important;
    color: var(--tl-ink) !important;
    font-family: var(--tl-sans) !important;
    font-feature-settings: "kern", "liga", "calt";
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-rendering: optimizeLegibility;
}

/* ------------------------------------------------------------------ *
 * 1. Faces — everything is Inter unless it is reading text.
 * ------------------------------------------------------------------ */
body.tl-refresh:not(#tl) :is(h1, h2, h3, h4, h5, h6, .elementor-heading-title,
    .elementor-heading-title a, .elementor-image-box-title, .elementor-image-box-description,
    figcaption, .wp-caption-text, .main-header-menu, .main-header-menu a, .menu-link,
    .ast-builder-menu, .site-footer, .site-footer *, sup, sub, button, input, label,
    .tl-shelf-more, .tl-shelf-title, .tl-home-titles *, .tl-lightbox-caption) {
    font-family: var(--tl-sans) !important;
    text-transform: none !important;
    text-shadow: none !important;
}
body.tl-refresh:not(#tl) :is(.elementor-widget-text-editor, .elementor-widget-text-editor :is(p, li, span, div, blockquote)) {
    font-family: var(--tl-serif) !important;
    font-optical-sizing: auto;
    font-size: clamp(1.03rem, 0.98rem + 0.3vw, 1.14rem) !important;
    font-weight: 400 !important;
    font-style: normal !important;
    line-height: 1.62 !important;
    letter-spacing: 0 !important;
    color: var(--tl-ink) !important;
}
body.tl-refresh:not(#tl) .elementor-widget-text-editor :is(i, em, cite) { font-style: italic !important; }
body.tl-refresh:not(#tl) .elementor-widget-text-editor :is(b, strong) { font-weight: 600 !important; }
body.tl-refresh:not(#tl) .elementor-widget-text-editor p { margin: 0 0 1em !important; }
body.tl-refresh:not(#tl) .elementor-widget-text-editor p:last-child { margin-bottom: 0 !important; }
body.tl-refresh:not(#tl) .elementor-widget-text-editor sup { font-size: 0.7em !important; }

/* Reading text never runs wider than a comfortable line. */
body.tl-refresh:not(#tl) .elementor-widget-text-editor {
    width: 100% !important;
    max-width: var(--tl-measure) !important;
    flex-shrink: 1 !important;
}
/* Elementor sized these paddings in em, so they grew with the type and
   crushed the column (About's decades went one word per line). The
   measure above governs width; text starts on the same edge as its title. */
body.tl-refresh:not(#tl) .elementor-widget-text-editor > .elementor-widget-container {
    margin-left: 0 !important;
    margin-right: 0 !important;
    padding-left: 0 !important;
    padding-right: 0 !important;
}

/* ------------------------------------------------------------------ *
 * 2. The scale. refresh.js assigns each heading one role.
 * ------------------------------------------------------------------ */
body.tl-refresh:not(#tl) [data-tl-role] {
    font-style: normal !important;
    margin-top: 0 !important;
    color: var(--tl-ink) !important;
}
body.tl-refresh:not(#tl) [data-tl-role="display"] {
    font-size: clamp(2rem, 1.35rem + 2.2vw, 2.9rem) !important;
    font-weight: 500 !important;
    line-height: 1.08 !important;
    letter-spacing: -0.028em !important;
}
body.tl-refresh:not(#tl) [data-tl-role="title"] {
    font-size: clamp(1.45rem, 1.15rem + 1vw, 1.85rem) !important;
    font-weight: 500 !important;
    line-height: 1.18 !important;
    letter-spacing: -0.018em !important;
}
body.tl-refresh:not(#tl) [data-tl-role="subhead"] {
    font-size: clamp(1.1rem, 1rem + 0.35vw, 1.25rem) !important;
    font-weight: 500 !important;
    line-height: 1.3 !important;
    letter-spacing: -0.01em !important;
}
body.tl-refresh:not(#tl) [data-tl-role="label"] {
    font-size: 0.95rem !important;
    font-weight: 500 !important;
    line-height: 1.35 !important;
    letter-spacing: -0.004em !important;
}
body.tl-refresh:not(#tl) [data-tl-role="caption"] {
    font-size: 0.8125rem !important;
    font-weight: 500 !important;
    line-height: 1.4 !important;
    letter-spacing: 0 !important;
}
body.tl-refresh:not(#tl) [data-tl-role="meta"] {
    font-size: 0.8125rem !important;
    font-weight: 400 !important;
    line-height: 1.4 !important;
    letter-spacing: 0 !important;
    color: var(--tl-muted) !important;
    font-variant-numeric: tabular-nums;
}
body.tl-refresh:not(#tl) [data-tl-role] :is(i, em) { font-style: italic !important; }
body.tl-refresh:not(#tl) [data-tl-role="caption"] + *,
body.tl-refresh:not(#tl) .elementor-widget-heading:has([data-tl-role="caption"]) + .elementor-widget-heading:has([data-tl-role="meta"]) {
    margin-top: 0.1rem !important;
}
/* A caption belongs to the image above it. */
body.tl-refresh:not(#tl) .elementor-widget-image + .elementor-widget-heading:has(:is([data-tl-role="caption"], [data-tl-role="meta"])) > .elementor-widget-container {
    margin-top: 0.6rem !important;
}
/* Headings share the text's left edge (Elementor indented some in em). */
body.tl-refresh:not(#tl):not(.page-id-10) main .elementor-widget-heading > .elementor-widget-container {
    margin-left: 0 !important;
    margin-right: 0 !important;
    padding-left: 0 !important;
    padding-right: 0 !important;
}
/* Titles get room above and hold their text close. */
body.tl-refresh:not(#tl) .elementor-widget-heading:has(:is([data-tl-role="title"], [data-tl-role="display"])) > .elementor-widget-container {
    margin-bottom: 0.35rem !important;
}
body.tl-refresh:not(#tl) .elementor-widget-heading:has([data-tl-role]) + .elementor-widget-text-editor > .elementor-widget-container {
    margin-top: 0.75rem !important;
}

/* ------------------------------------------------------------------ *
 * 3. Links, rules, images.
 * ------------------------------------------------------------------ */
body.tl-refresh:not(#tl) :is(main, .site-content) a,
body.tl-refresh:not(#tl) :is(main, .site-content) a:visited {
    color: inherit !important;
    text-decoration: none !important;
}
body.tl-refresh:not(#tl) .elementor-widget-text-editor a,
body.tl-refresh:not(#tl) .elementor-widget-text-editor a:visited {
    text-decoration: underline !important;
    text-decoration-thickness: 1px !important;
    text-underline-offset: 0.18em !important;
    text-decoration-color: var(--tl-rule) !important;
}
body.tl-refresh:not(#tl) :is(main, .site-content) a:hover { color: var(--tl-accent) !important; }
body.tl-refresh:not(#tl) :is(main, .site-content) a:focus-visible {
    outline: 2px solid var(--tl-accent) !important;
    outline-offset: 3px;
}

body.tl-refresh:not(#tl) .elementor-divider-separator {
    border-top-color: var(--tl-rule) !important;
    border-top-width: 1px !important;
}
body.tl-refresh:not(#tl) hr { border-color: var(--tl-rule) !important; }

/* Artwork sits flat on the paper — the drop-shadow frames read as
   pasted-on prints, which is most of the "collage" feeling. */
body.tl-refresh:not(#tl) :is(main, .site-content) :is(img, .elementor-widget-image .elementor-widget-container, .elementor-widget-image a) {
    box-shadow: none !important;
    border-radius: 0 !important;
}
body.tl-refresh:not(#tl) .elementor-widget-image img { transition: opacity 0.2s ease !important; }
body.tl-refresh:not(#tl) .elementor-widget-image a:hover img { opacity: 0.88; }

/* ------------------------------------------------------------------ *
 * 4. Header + footer.
 * ------------------------------------------------------------------ */
body.tl-refresh:not(#tl) :is(.main-header-menu .menu-link, .ast-builder-menu .menu-link) {
    font-size: 1rem !important;
    font-weight: 400 !important;
    letter-spacing: -0.005em !important;
    color: var(--tl-ink) !important;
}
body.tl-refresh:not(#tl) :is(.main-header-menu .menu-link, .ast-builder-menu .menu-link):hover,
body.tl-refresh:not(#tl) .current-menu-item > .menu-link {
    color: var(--tl-accent) !important;
}
body.tl-refresh:not(#tl) .site-footer,
body.tl-refresh:not(#tl) .site-footer * {
    font-size: 0.8125rem !important;
    line-height: 1.55 !important;
    font-weight: 400 !important;
    color: var(--tl-muted) !important;
}
body.tl-refresh:not(#tl) .site-footer :is(strong, b) { font-weight: 500 !important; color: var(--tl-ink) !important; }
body.tl-refresh:not(#tl) .site-footer :is(.ast-builder-grid-row, .site-footer-section) {
    border-color: var(--tl-rule) !important;
}
body.tl-refresh:not(#tl) .site-above-footer-wrap,
body.tl-refresh:not(#tl) .site-primary-footer-wrap,
body.tl-refresh:not(#tl) .site-below-footer-wrap {
    border-top-color: var(--tl-rule) !important;
}

/* ------------------------------------------------------------------ *
 * 5. Section headers ("doorways"): image band → title → intro.
 *    Same place on every section; nothing printed over a photograph.
 * ------------------------------------------------------------------ */
body.tl-refresh:not(#tl) .tl-archive-doorway .elementor-widget-image img {
    height: clamp(240px, 34vw, 460px) !important;
    object-fit: cover !important;
}
body.tl-refresh:not(#tl) .tl-archive-doorway .tl-doorway-sign {
    position: static !important;
    transform: none !important;
    left: auto !important;
    bottom: auto !important;
    display: block !important;
    width: min(var(--tl-measure), 100vw - 2 * var(--tl-gutter)) !important;
    max-width: none !important;
    margin: clamp(1.75rem, 3.5vw, 2.75rem) auto 0 !important;
    padding: 0 !important;
    box-sizing: border-box !important;
    color: var(--tl-ink) !important;
    text-align: left !important;
    font-size: clamp(2rem, 1.35rem + 2.2vw, 2.9rem) !important;
    font-weight: 500 !important;
    line-height: 1.08 !important;
    letter-spacing: -0.028em !important;
}
body.tl-refresh:not(#tl) .tl-archive-doorway :is(.elementor-widget-text-editor, .elementor-widget-divider) > .elementor-widget-container,
body.tl-refresh:not(#tl) .tl-section-intro > .elementor-widget-container {
    width: min(var(--tl-measure), 100vw - 2 * var(--tl-gutter)) !important;
    max-width: none !important;
    margin-left: auto !important;
    margin-right: auto !important;
    padding-left: 0 !important;
    padding-right: 0 !important;
    box-sizing: border-box !important;
}
body.tl-refresh:not(#tl) .tl-archive-doorway .elementor-widget-text-editor { max-width: none !important; }
body.tl-refresh:not(#tl) .tl-archive-doorway :is(.elementor-widget-wrap, .elementor-element-populated, .elementor-column-gap-default > .elementor-column > .elementor-element-populated) {
    padding-left: 0 !important;
    padding-right: 0 !important;
    margin-left: 0 !important;
    margin-right: 0 !important;
}
body.tl-refresh:not(#tl) .tl-archive-doorway .elementor-widget-divider { display: none !important; }
body.tl-refresh:not(#tl) .tl-archive-doorway .elementor-widget-text-editor > .elementor-widget-container {
    margin-top: 1rem !important;
    margin-bottom: clamp(2.5rem, 5vw, 4rem) !important;
    color: var(--tl-ink) !important;
}

/* In the Studio paints its band as a ::before on the section; let the
   band occupy its own space and flow the title + intro beneath it. */
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa {
    display: block !important;
    min-height: 0 !important;
    padding: 0 !important;
    background: none !important;
}
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa::before {
    content: "" !important;
    display: block !important;
    position: relative !important;
    inset: auto !important;
    margin: 0 !important;
    aspect-ratio: auto !important;
    width: 100% !important;
    height: clamp(240px, 34vw, 460px) !important;
    background-size: cover !important;
    background-position: center 38% !important;
    opacity: 1 !important;
}
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa .elementor-background-overlay { display: none !important; }
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa > .elementor-container {
    display: block !important;
    width: min(var(--tl-measure), 100vw - 2 * var(--tl-gutter)) !important;
    max-width: none !important;
    margin: 0 auto !important;
    padding: 0 !important;
}
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa :is(.elementor-column, .elementor-widget-wrap) {
    width: 100% !important;
    display: block !important;
    padding: 0 !important;
    background: none !important;
}
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa .elementor-widget > .elementor-widget-container {
    margin-left: 0 !important;
    margin-right: 0 !important;
    padding-left: 0 !important;
    padding-right: 0 !important;
}
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa .elementor-heading-title {
    width: auto !important;
    max-width: none !important;
    margin: clamp(1.75rem, 3.5vw, 2.75rem) 0 0 !important;
    text-align: left !important;
    color: var(--tl-ink) !important;
}
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa .elementor-widget-divider { display: none !important; }
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa .elementor-widget-text-editor { max-width: none !important; }
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa .elementor-widget-text-editor > .elementor-widget-container {
    margin: 1rem 0 clamp(2.5rem, 5vw, 4rem) !important;
    padding: 0 !important;
    background: none !important;
    color: var(--tl-ink) !important;
}
body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa .elementor-widget-text-editor * {
    color: var(--tl-ink) !important;
    text-shadow: none !important;
    background: none !important;
}

/* In the Studio overview: period labels sit on a hairline, tabular. */
body.tl-refresh:not(#tl).page-id-140 .elementor-top-section:not(.elementor-element-71fa6aa) .elementor-heading-title {
    font-size: 1rem !important;
    font-weight: 500 !important;
    letter-spacing: 0 !important;
    font-variant-numeric: tabular-nums;
    color: var(--tl-ink) !important;
}

/* ------------------------------------------------------------------ *
 * 6. Studio period pages — "1987 – 1990" as one title, not three
 *    columns with a gap in the middle.
 * ------------------------------------------------------------------ */
body.tl-refresh:not(#tl).tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child > .elementor-container {
    display: flex !important;
    flex-wrap: wrap !important;
    align-items: baseline !important;
    justify-content: flex-start !important;
    gap: 0 !important;
    max-width: var(--tl-wide) !important;
    margin: clamp(1.5rem, 4vw, 3rem) auto clamp(1.5rem, 3vw, 2.5rem) !important;
    padding: 0 var(--tl-gutter) !important;
}
body.tl-refresh:not(#tl).tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child .elementor-column {
    width: auto !important;
    flex: 0 0 auto !important;
    min-height: 0 !important;
}
body.tl-refresh:not(#tl).tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child .elementor-column:has(.elementor-widget-divider) {
    display: none !important;
}
body.tl-refresh:not(#tl).tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child :is(.elementor-widget-wrap, .elementor-element-populated) {
    padding: 0 !important;
}
body.tl-refresh:not(#tl).tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child .elementor-heading-title {
    font-size: clamp(2rem, 1.35rem + 2.2vw, 2.9rem) !important;
    font-weight: 500 !important;
    line-height: 1.08 !important;
    letter-spacing: -0.028em !important;
    font-variant-numeric: tabular-nums;
    color: var(--tl-ink) !important;
}
body.tl-refresh:not(#tl).tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child .elementor-heading-title::before,
body.tl-refresh:not(#tl).tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child .elementor-heading-title::after {
    content: none !important;
}
body.tl-refresh:not(#tl).tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child .elementor-column:last-child .elementor-heading-title::before {
    content: "\2013" !important;
    margin: 0 0.28em !important;
    color: var(--tl-muted);
}
/* "In the Studio" eyebrow above the period, linking back. */
body.tl-refresh:not(#tl) .tl-eyebrow {
    display: block;
    flex: 0 0 100%;
    margin-bottom: 0.5rem;
    font-family: var(--tl-sans);
    font-size: 0.8125rem;
    font-weight: 500;
    letter-spacing: 0;
    color: var(--tl-muted) !important;
    text-decoration: none !important;
}
body.tl-refresh:not(#tl) .tl-eyebrow:hover { color: var(--tl-accent) !important; }

/* ------------------------------------------------------------------ *
 * 7. Home — the menu speaks the same language.
 * ------------------------------------------------------------------ */
body.tl-refresh:not(#tl).page-id-10 .tl-home-titles .elementor-heading-title {
    font-size: clamp(1.3rem, 1.05rem + 0.8vw, 1.7rem) !important;
    font-weight: 500 !important;
    letter-spacing: -0.02em !important;
    line-height: 1.15 !important;
}
body.tl-refresh:not(#tl).page-id-10 .tl-home-titles .elementor-heading-title::after {
    font-family: var(--tl-sans) !important;
    font-size: 0.8125rem !important;
    font-weight: 400 !important;
    letter-spacing: 0 !important;
    color: var(--tl-muted) !important;
    margin-top: 0.3rem !important;
}
body.tl-refresh:not(#tl).page-id-10 .tl-home-titles .elementor-widget-heading + .elementor-widget-heading {
    margin-top: 1.1rem !important;
}
body.tl-refresh:not(#tl).page-id-10 .tl-home-tile-link:hover { opacity: 1 !important; color: var(--tl-accent) !important; }

/* ------------------------------------------------------------------ *
 * 8. Contact.
 * ------------------------------------------------------------------ */
body.tl-refresh:not(#tl).page-id-1527 [data-elementor-type="wp-page"] :is(a, .elementor-heading-title) {
    font-family: var(--tl-sans) !important;
    font-size: clamp(1.45rem, 1.15rem + 1vw, 1.85rem) !important;
    font-weight: 500 !important;
    letter-spacing: -0.018em !important;
}
body.tl-refresh:not(#tl).page-id-1527 [data-elementor-type="wp-page"] a {
    border-bottom: 1px solid var(--tl-rule) !important;
    padding-bottom: 0.15em;
}

/* ------------------------------------------------------------------ *
 * 9. Mobile.
 * ------------------------------------------------------------------ */
@media (max-width: 767px) {
    body.tl-refresh:not(#tl) .elementor-widget-text-editor {
        max-width: none !important;
    }
    body.tl-refresh:not(#tl) .tl-archive-doorway .elementor-widget-image img,
    body.tl-refresh:not(#tl).page-id-140 .elementor-element-71fa6aa::before {
        height: 56vw !important;
    }
}

</style>
    <?php
}

function tl_refresh_js() {
    ?>
<script id="tl-refresh-js">
/* TL design refresh — 2026-09-27. See refresh.css for the system. */
(function () {
    var body = document.body;
    body.classList.add('tl-refresh');
    var path = location.pathname.replace(/\/+$/, '');
    if (/^\/beyond-the-studio-/.test(path)) body.classList.add('tl-project-detail');
    /* 1983–1987 was built as elementor-428, so the polish slug test missed it. */
    if (path === '/elementor-428') body.classList.add('tl-studio-detail');

    function clean(value) {
        return (value || '').replace(/[​-‍﻿]/g, '').replace(/\s+/g, ' ').trim();
    }

    /* ---- 1. All-caps labels → title case (authored caps, not CSS). ---- */
    var KEEP = /^(REALLIFE|MOCA|LACE|LAXART|CAE|PS1|P\.S\.1|USA|UK|US|LA|NY|NYC|TV|BBC|CCA|SVA|UCLA|ICA|II|III|IV|VI|VII|VIII|IX|XI|XII|TL|DJ)$/;
    var SMALL = /^(a|an|and|as|at|by|for|from|in|into|of|on|or|the|to|with)$/;
    function titleCase(text) {
        var index = 0;
        return text.replace(/[A-Z0-9][A-Z0-9.'’&-]*/g, function (word) {
            var first = index++ === 0;
            if (KEEP.test(word.replace(/[.,;:]+$/, ''))) return word;
            var lower = word.toLowerCase();
            if (!first && SMALL.test(lower)) return lower;
            return lower.replace(/(^|[-'’.])([a-z])/g, function (m, sep, ch) {
                return sep + ch.toUpperCase();
            });
        });
    }
    function uncap(node) {
        var text = clean(node.textContent);
        if (text.length < 4 || /[a-z]/.test(text) || !/[A-Z]{3}/.test(text)) return;
        if (KEEP.test(text)) return;
        var walker = document.createTreeWalker(node, NodeFilter.SHOW_TEXT);
        var first = true;
        while (walker.nextNode()) {
            var t = walker.currentNode;
            if (!clean(t.nodeValue)) continue;
            var out = titleCase(t.nodeValue);
            if (!first) out = out.replace(/^(\s*)([a-z])/, function (m, s, c) { return s + c; });
            t.nodeValue = out;
            first = false;
        }
    }
    document.querySelectorAll('.elementor-heading-title, figcaption, .wp-caption-text').forEach(uncap);

    /* ---- 2. Bookshelf detail headers: one title, no echo. ---- */
    if (body.classList.contains('tl-bookshelf-detail')) {
        var head = document.querySelector('[data-elementor-type="wp-page"] > .elementor-top-section');
        if (head) {
            var hs = head.querySelectorAll('.elementor-heading-title');
            if (hs.length >= 2) {
                var h1 = hs[0], sub = hs[1];
                var a = clean(h1.textContent).toLowerCase(), b = clean(sub.textContent).toLowerCase();
                if (/^(other|publications)$/.test(a) && b) {
                    h1.textContent = clean(sub.textContent);
                    sub.closest('.elementor-widget').style.display = 'none';
                } else if (a === b) {
                    sub.closest('.elementor-widget').style.display = 'none';
                }
            }
        }
    }

    /* ---- 3. Snap every heading onto the five-step scale. ---- */
    var skip = [
        '.tl-doorway-sign', '.tl-home-titles', '.page-id-140 .elementor-top-section',
        '.tl-studio-detail [data-elementor-type="wp-page"] > .elementor-top-section:first-child',
        '.page-id-1527', '.site-header', '.site-footer'
    ].join(',');
    document.querySelectorAll('.elementor-heading-title').forEach(function (h) {
        if (h.closest(skip)) return;
        var cs = getComputedStyle(h);
        var px = parseFloat(cs.fontSize);
        var weight = parseInt(cs.fontWeight, 10) || 400;
        var tag = h.tagName;
        var role;
        if (px >= 40) role = 'display';
        else if (px >= 25) role = 'title';
        else if (px >= 19) role = 'subhead';
        else if (px >= 15) role = 'label';
        else if (tag === 'H6' || weight <= 300 || cs.fontStyle === 'italic') role = 'meta';
        else role = 'caption';
        h.setAttribute('data-tl-role', role);
    });
    /* A lone page's first big heading is its title; make it the display step. */
    var firstTitle = document.querySelector('[data-elementor-type="wp-page"] [data-tl-role="title"], [data-elementor-type="wp-page"] [data-tl-role="display"]');
    if (firstTitle && !body.classList.contains('page-id-10')) firstTitle.setAttribute('data-tl-role', 'display');

    /* ---- 4. Eyebrow: every detail page says which section it's in. ---- */
    var sections = [
        ['tl-studio-detail', 'In the Studio', '/in-the-studio/'],
        ['tl-bookshelf-detail', 'Bookshelf', '/bookshelf/'],
        ['tl-exhibition-detail', 'Art in a Broader Context', '/art-in-a-broader-context/'],
        ['tl-project-detail', 'Beyond the Studio', '/beyond-the-studio/']
    ];
    sections.some(function (s) {
        if (!body.classList.contains(s[0]) || document.querySelector('.tl-eyebrow')) return false;
        var link = document.createElement('a');
        link.className = 'tl-eyebrow';
        link.href = s[2];
        link.textContent = s[1];
        if (s[0] === 'tl-studio-detail') {
            var box = document.querySelector('[data-elementor-type="wp-page"] > .elementor-top-section:first-child > .elementor-container');
            if (box) box.insertBefore(link, box.firstChild);
        } else if (firstTitle) {
            var widget = firstTitle.closest('.elementor-widget');
            if (widget) widget.parentNode.insertBefore(link, widget);
        }
        return true;
    });
})();

</script>
    <?php
}
