// Generated by kidlisp-to-pd.mjs
// Do not edit - regenerate from source

#include <stdio.h>
#include <stdlib.h>
#include "pd_api.h"
#include "kidlisp.h"

// Temp string buffer for number display
static char temp_str[32];

// Forward declarations
static int update(void* userdata);

// === Variables ===

// === Main Loop ===
static void kidlisp_main(void) {
    kl_scroll(0, 0);
    kl_blur(5);
    kl_ink(KL_BLACK);
    kl_line(kl_random(400), kl_random(240), kl_random(400), kl_random(240));
    kl_line(kl_random(400), kl_random(240), kl_random(400), kl_random(240));
    kl_line(kl_random(400), kl_random(240), kl_random(400), kl_random(240));
}

// Playdate event handler
#ifdef _WINDLL
__declspec(dllexport)
#endif
int eventHandler(PlaydateAPI* pd, PDSystemEvent event, uint32_t arg) {
    (void)arg;
    
    if (event == kEventInit) {
        kl_init(pd);
        pd->system->setUpdateCallback(update, pd);
    }
    
    return 0;
}

// Frame update
static int update(void* userdata) {
    (void)userdata;
    kl_update();
    kidlisp_main();
    return 1;
}
