; Fía's Birthday
; fia-birthday, 2025.6.25.0.272

(label)
(ink (... blue pink gray))
(mask 0 22 width height-22)
(repeat width/16 i (ink (0.05s... gray purple blue pink)) (box i*16 0 4 height))
(scroll frame -frame)
(spin (* 30 (sin)))
(stamp "@jeffrey/2025.6.24.01.45.17.910" width/2 height/2
  (/ (min width height) (+ 300 (* 50 (sin)))) (* 15 (sin))
)
(mask 0 0 width 6)
(0.5s (wipe (... purple brown)))
(mask 0 6 width 23)
(0.5s (wipe (... navy black)))
(unmask)
(ink (... yellow green white rainbow) 200)
(write "Celebrate Fía's Birthday Celebrate Fia's Birthday"
  (mod (mul frame/1 -1) (+ 12 (* 24 12))) 2 no 2
)
(ink (0.1s... white yellow blue))
(write "July 5th in Echo Park" 10 30 black)
(ink (2s... pink orange))
(write "8pm-2am" width-88 41 black 2)
(ink (0.15s... red orange yellow lime green))
(write (0.45s... "Karaoke & Dance" "K a r a o k e & D a n c e")
        center (+ height-50 (* 12 amplitude)) (0.5s... black blue gray indigo purple))
(pan 10 4)
(ink (choose blue indigo purple))
(write (0.2s... "INVITE ONLY" "invite only") width-90 height-30 white)
(ink orange)
(write "+1s welcome" width-80 height-19 (0.3s... brown red))
(unpan)
(ink (0.1s... blue white))
(write " BYOB" -10 height-17 red 2)

(if (speaker)
  (melody "4d.4d.4e4d4g4fs-_4d.4d.4e4d4a4g-_4d.4d.5d4b4g4fs4e_5c5c4b4g4a4g-"
    180 "3/4" "waltz")
)

(not (speaker)
  (ink purple 190)
  (box 0 0 width height)
  (ink white)
  (shape (- (/ width 2) 8) (- (/ height 2) 8) 
         (+ (/ width 2) 8) (/ height 2)
         (- (/ width 2) 8) (+ (/ height 2) 8))
  (blur 16)
  (repeat 30 i
    (ink (choose red pink purple brown))
    (write (choose "*" "+" "x" "o" "Fía") 
           (mod (+ (* i 67) (* (sin (* i 0.3)) 20) (* frame 0.5)) width)
           (mod (+ (* i 89) (* frame (+ 2 (mod i 3)))) height)))
  (ink (0.11s... white yellow pink))
  (shape (- (/ width 2) 8) (- (/ height 2) 8) 
         (+ (/ width 2) 8) (/ height 2)
         (- (/ width 2) 8) (+ (/ height 2) 8))
  (ink red 128)
  (shape (- (/ width 2) 8) (- (/ height 2) 8) 
         (+ (/ width 2) 8) (/ height 2)
         (- (/ width 2) 8) (+ (/ height 2) 8) "outline")
  (pan 0 18)
  (ink white 200)
  (write "Play" center center)
  (unpan)
)