import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire('/Users/aesthetic/aesthetic-computer/package.json');
const root='/Users/aesthetic/Developer/ac-builds/tom-closeout-20261005';
const browser=await require('puppeteer-core').connect({browserWSEndpoint:JSON.parse(await fs.readFile(root+'/browser.json')).ws,defaultViewport:null});
const preview=process.argv.includes('--preview');
const out=root+'/'+(preview?'interaction-preview':'interaction-live');await fs.mkdir(out,{recursive:true});
const page=await browser.newPage();
const result=[];
const check=(name,value)=>{assert.ok(value,name);result.push({name,pass:true});console.log('PASS '+name);};
async function open(path,width=390){
  await page.setViewport({width,height:844,isMobile:width<600,hasTouch:width<600,deviceScaleFactor:1});
  await page.goto('https://www.thomaslawson.com'+path,{waitUntil:'networkidle2',timeout:60000});
  await page.waitForSelector('#tl-site-header');
  if(preview){await page.addStyleTag({path:root+'/quality.css'});await page.addScriptTag({path:root+'/quality.js'});}
}
try{
  await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);
  await open('/');
  await page.waitForFunction(()=>document.querySelector('.tl-feature img')?.naturalWidth>0);
  check('Mobile opens a portrait without cropping',await page.evaluate(()=>{const img=document.querySelector('.tl-feature img');return img.naturalHeight>img.naturalWidth&&getComputedStyle(img).objectFit==='contain';}));
  const initial=await page.$eval('.tl-feature-carousel',e=>e.dataset.title);
  await page.tap('.tl-feature-controls button[aria-label="Next work"]');
  check('Touch next changes the artwork',await page.$eval('.tl-feature-carousel',(e,title)=>e.dataset.title!==title,initial));
  await page.focus('.tl-feature-controls button[aria-label="Next work"]');await page.keyboard.press('ArrowLeft');
  check('Keyboard arrows navigate carousel',await page.$eval('.tl-feature-carousel',(e,title)=>e.dataset.title===title,initial));
  const point=await page.$eval('.tl-feature-art',e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width*.8,y:r.y+r.height*.4,end:r.x+r.width*.2};});
  const cdp=await page.createCDPSession();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:point.x,y:point.y}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:point.end,y:point.y}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  check('Horizontal touch swipe changes artwork without navigation',await page.$eval('.tl-feature-carousel',(e,title)=>e.dataset.title!==title,initial));
  await page.tap('.tl-quality-play');
  check('Slideshow can be started',await page.$eval('.tl-quality-play',e=>e.textContent==='Pause'));
  const beforeRotation=await page.$eval('.tl-feature-carousel',e=>e.dataset.title);
  await page.waitForFunction(title=>document.querySelector('.tl-feature-carousel').dataset.title!==title,{timeout:12000},beforeRotation);
  check('Slideshow advances automatically after seven seconds',true);
  await page.keyboard.press('Tab');
  check('Keyboard focus pauses slideshow',await page.$eval('.tl-quality-play',e=>e.textContent==='Play'));
  await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);
  await page.waitForFunction(()=>document.querySelector('.tl-quality-play').hidden);
  check('Reduced motion keeps automatic rotation off',await page.$eval('.tl-quality-play',e=>e.hidden&&e.textContent==='Play'));
  await page.tap('.tl-header-menu');
  check('Touch menu opens',await page.$eval('#tl-menu-panel',e=>e.open));
  await page.keyboard.press('Escape');
  check('Menu closes and restores focus',await page.evaluate(()=>!document.querySelector('#tl-menu-panel').open&&document.activeElement.matches('.tl-header-menu')));
  await page.tap('.tl-header-search');
  check('Search receives focus',await page.evaluate(()=>document.activeElement.id==='tl-search-input'));
  await page.type('#tl-search-input','Candlelight');await page.waitForSelector('.tl-search-card');
  check('Search returns the requested artwork',await page.$eval('.tl-search-title',e=>e.textContent==='Candlelight'));
  await page.keyboard.press('Escape');
  check('Search closes and restores focus',await page.evaluate(()=>!document.querySelector('#tl-search-panel').open&&document.activeElement.matches('.tl-header-search')));
  await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:out+'/home-mobile.png'});
  await open('/',1440);
  await page.waitForFunction(()=>document.querySelector('.tl-feature img')?.naturalWidth>0);
  check('Desktop keeps Candlelight as its opening work',await page.$eval('.tl-feature-carousel',e=>e.dataset.title==='Candlelight'));
  await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:out+'/home-desktop.png'});
  await open('/about/');
  const imgButton=await page.$('.tl-quality-image-button');assert.ok(imgButton,'Native image button exists');
  await imgButton.focus();await page.keyboard.press('Enter');
  check('Image viewer opens from the keyboard',await page.$eval('.tl-quality-viewer',e=>e.open));
  await page.keyboard.press('Tab');
  check('Image viewer contains keyboard focus',await page.evaluate(()=>document.activeElement.closest('.tl-quality-viewer')!==null));
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.querySelector('.tl-quality-viewer')&&document.activeElement.matches('.tl-quality-image-button'));
  check('Image viewer Escape restores the opener',await page.evaluate(()=>!document.querySelector('.tl-quality-viewer')&&document.activeElement.matches('.tl-quality-image-button')));
  await open('/inthestudio_2010-2015/');
  await page.focus('.tl-quality-image-button');await page.keyboard.press('Enter');
  check('Legacy gallery image opens with a native keyboard control',await page.$eval('.tl-quality-viewer',e=>e.open));
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.querySelector('.tl-quality-viewer')&&document.activeElement.matches('.tl-quality-image-button'));
  check('Legacy gallery viewer restores keyboard focus',true);
  await open('/beyond-the-studio-portraits-of-new-york/');
  await page.click('.tl-portrait-play');await page.waitForSelector('#tl-portrait-film iframe');
  const frame=await (await page.$('#tl-portrait-film iframe')).contentFrame();
  await frame.waitForFunction(()=>document.readyState==='complete',{timeout:30000}).catch(()=>{});
  await frame.waitForFunction(()=>[...document.querySelectorAll('video')].some(v=>v.currentTime>0)||/sorry|unavailable|verify|log in|blocked/i.test(document.body.innerText),{timeout:15000}).catch(()=>{});
  const media=await frame.evaluate(()=>({title:document.title,text:document.body.innerText.slice(0,1000),videos:[...document.querySelectorAll('video')].map(v=>({paused:v.paused,readyState:v.readyState,time:v.currentTime,error:v.error?.message}))}));
  result.push({name:'Vimeo player state',...media});console.log(JSON.stringify({vimeo:media}));
}catch(error){result.push({name:'failure',message:error.message});console.error(error.stack);process.exitCode=1;}
await fs.writeFile(out+'/results.json',JSON.stringify(result,null,2));
await page.close();await browser.disconnect();process.exit(process.exitCode||0);
