# Get the latest fedora version.
FROM fedora:latest
# Update all packages.
# RUN dnf update -y
# 
# RUN dnf install -y which tree procps-ng coreutils xclip xsel unzip jq bat
# RUN dnf install -y git gh gcc clang python3 python3-pip emacs-nox fish util-linux-user
# RUN dnf install -y qemu-kvm qemu-img
# RUN dnf install -y openssl awscli redis
# RUN dnf install -y dnf-plugins-core