// loner-chart.h — GENERATED by bin/halo3.py; do not edit.
// The v4 beat chart: per phrase, its lead-in (consonant runway before
// beat 0), length in beats, and per word unit its slot, length, and
// semitone above TONIC (237 Hz) — measured from Camille's own take, so
// any instrument reading this plays HER melody.
#pragma once

#define CHART_BPM 122.0
#define CHART_TONIC 237.0

typedef struct { double beat, dur; int st; } ChartNote;
typedef struct { const char *name; double leadIn; double beats;
                 int n; const ChartNote *notes; } ChartPhrase;

static const ChartNote w_whole_line_notes[] = {
    { 0.00, 4.50, 7 },
    { 4.50, 2.50, 3 },
    { 7.00, 3.50, 2 },
    { 10.50, 0.50, 0 },
    { 11.00, 1.50, 0 },
    { 12.50, 3.50, 5 },
    { 16.00, 0.50, -2 },
    { 16.50, 3.50, -2 },
    { 20.00, 1.50, 12 },
    { 21.50, 1.00, 12 },
    { 22.50, 6.50, 6 },
    { 29.00, 3.50, 2 },
    { 32.50, 4.00, 3 },
    { 36.50, 3.50, 0 },
    { 40.00, 5.50, 5 },
    { 45.50, 2.00, 5 },
    { 47.50, 3.50, 7 },
    { 51.00, 4.00, 3 },
    { 55.00, 4.00, 3 },
};
static const ChartNote w_sitting_curled_notes[] = {
    { 0.00, 3.00, 7 },
    { 3.00, 1.50, 3 },
    { 4.50, 2.00, 2 },
    { 6.50, 0.50, 0 },
    { 7.00, 1.00, 0 },
    { 8.00, 3.00, 5 },
};
static const ChartNote w_i_think_notes[] = {
    { 0.00, 0.50, -2 },
    { 0.50, 3.00, -2 },
};
static const ChartNote w_of_a_stone_notes[] = {
    { 0.00, 1.50, 12 },
    { 1.50, 1.00, 12 },
    { 2.50, 5.50, 6 },
};
static const ChartNote w_just_waiting_notes[] = {
    { 0.00, 3.00, 2 },
    { 3.00, 3.50, 3 },
};
static const ChartNote w_very_patiently_notes[] = {
    { 0.00, 3.50, 0 },
    { 3.50, 5.00, 5 },
};
static const ChartNote w_for_time_to_pass_notes[] = {
    { 0.00, 2.00, 5 },
    { 2.00, 3.50, 7 },
    { 5.50, 3.50, 3 },
    { 9.00, 4.00, 3 },
};
static const ChartNote w_n_getting_curled_notes[] = {
    { 0.00, 2.50, 5 },
    { 2.50, 1.00, 2 },
    { 3.50, 1.00, 0 },
    { 4.50, 0.50, 0 },
    { 5.00, 0.50, 5 },
    { 5.50, 2.00, 2 },
    { 7.50, 0.50, -2 },
    { 8.00, 2.00, -2 },
};
static const ChartNote w_n_stone_waiting_notes[] = {
    { 0.00, 1.00, 12 },
    { 1.00, 0.50, 12 },
    { 1.50, 2.50, 9 },
    { 4.00, 2.00, 5 },
    { 6.00, 3.50, 3 },
    { 9.50, 2.00, 2 },
    { 11.50, 4.50, 5 },
};
static const ChartNote w_n_for_time_to_pass_notes[] = {
    { 0.00, 1.50, 7 },
    { 1.50, 2.00, 7 },
    { 3.50, 1.00, 3 },
    { 4.50, 2.00, 3 },
};

static const ChartPhrase CHART[] = {
    { "w-whole-line", 0.050, 59.00, 19, w_whole_line_notes },
    { "w-sitting-curled", 0.050, 11.00, 6, w_sitting_curled_notes },
    { "w-i-think", 0.060, 3.50, 2, w_i_think_notes },
    { "w-of-a-stone", 0.060, 8.00, 3, w_of_a_stone_notes },
    { "w-just-waiting", 0.075, 6.50, 2, w_just_waiting_notes },
    { "w-very-patiently", 0.030, 8.50, 2, w_very_patiently_notes },
    { "w-for-time-to-pass", 0.040, 13.00, 4, w_for_time_to_pass_notes },
    { "w-n-getting-curled", 0.060, 10.00, 8, w_n_getting_curled_notes },
    { "w-n-stone-waiting", 0.060, 16.00, 7, w_n_stone_waiting_notes },
    { "w-n-for-time-to-pass", 0.060, 6.50, 4, w_n_for_time_to_pass_notes },
};
#define CHART_N 10
