// loner-chart.h — GENERATED by bin/halo3.py; do not edit.
// The v4 beat chart: per phrase, its lead-in (consonant runway before
// beat 0), length in beats, and per word unit its slot, length, and
// semitone above TONIC (237 Hz) — measured from Camille's own take, so
// any instrument reading this plays HER melody.
#pragma once

#define CHART_BPM 122.0
#define CHART_TONIC 237.0

typedef struct { double beat, dur; int st; } ChartNote;
typedef struct { const char *name; double leadIn; double beats;
                 int n; const ChartNote *notes; } ChartPhrase;

static const ChartNote w_whole_line_notes[] = {
    { 0.00, 2.00, 7 },
    { 2.00, 2.00, 7 },
    { 4.00, 2.50, 3 },
    { 6.50, 1.50, 2 },
    { 8.50, 2.50, 0 },
    { 11.00, 2.00, 5 },
    { 13.00, 2.00, 5 },
    { 15.00, 3.00, -2 },
    { 18.00, 1.00, -5 },
    { 19.00, 4.00, 12 },
    { 23.00, 2.00, 10 },
    { 25.00, 3.00, 5 },
    { 29.00, 3.50, 2 },
    { 32.50, 3.50, 3 },
    { 36.00, 4.00, 0 },
    { 40.00, 5.00, 7 },
    { 45.00, 5.00, 3 },
    { 50.00, 2.50, 7 },
    { 52.50, 5.50, 3 },
    { 58.00, 3.50, 3 },
};
static const ChartNote w_sitting_curled_notes[] = {
    { 0.00, 3.00, 6 },
    { 3.00, 2.00, 3 },
    { 5.00, 1.50, 2 },
    { 6.50, 1.50, 0 },
    { 8.00, 3.00, 5 },
};
static const ChartNote w_i_think_notes[] = {
    { 0.00, 2.00, -2 },
    { 2.00, 1.50, -5 },
};
static const ChartNote w_of_a_stone_notes[] = {
    { 0.00, 4.00, 12 },
    { 4.00, 2.00, 10 },
    { 6.00, 2.00, 5 },
};
static const ChartNote w_just_waiting_notes[] = {
    { 0.00, 3.50, 2 },
    { 3.50, 3.00, 3 },
};
static const ChartNote w_very_patiently_notes[] = {
    { 0.00, 5.00, 0 },
    { 5.00, 3.50, 7 },
};
static const ChartNote w_for_time_to_pass_notes[] = {
    { 0.00, 2.00, 5 },
    { 2.00, 2.50, 7 },
    { 4.50, 4.00, 3 },
    { 8.50, 4.00, 3 },
};
static const ChartNote w_n_getting_curled_notes[] = {
    { 0.00, 1.50, 5 },
    { 1.50, 2.50, 3 },
    { 4.00, 0.50, 2 },
    { 4.50, 1.50, 0 },
    { 6.00, 2.50, 4 },
    { 8.50, 2.00, -2 },
    { 10.50, 0.50, -5 },
};
static const ChartNote w_n_stone_waiting_notes[] = {
    { 0.00, 2.00, 12 },
    { 2.00, 2.00, 9 },
    { 4.00, 4.00, 4 },
    { 8.00, 4.00, 3 },
    { 12.00, 3.00, 0 },
    { 15.00, 2.00, 6 },
};
static const ChartNote w_n_for_time_to_pass_notes[] = {
    { 0.00, 0.50, 5 },
    { 0.50, 1.00, 7 },
    { 1.50, 2.50, 3 },
    { 4.00, 1.50, 3 },
};

static const ChartPhrase CHART[] = {
    { "w-whole-line", 0.490, 61.50, 20, w_whole_line_notes },
    { "w-sitting-curled", 0.020, 11.00, 5, w_sitting_curled_notes },
    { "w-i-think", 0.020, 3.50, 2, w_i_think_notes },
    { "w-of-a-stone", 0.000, 8.00, 3, w_of_a_stone_notes },
    { "w-just-waiting", 0.075, 6.50, 2, w_just_waiting_notes },
    { "w-very-patiently", 0.000, 8.50, 2, w_very_patiently_notes },
    { "w-for-time-to-pass", 0.035, 12.50, 4, w_for_time_to_pass_notes },
    { "w-n-getting-curled", 0.000, 11.00, 7, w_n_getting_curled_notes },
    { "w-n-stone-waiting", 0.000, 17.00, 6, w_n_stone_waiting_notes },
    { "w-n-for-time-to-pass", 0.000, 5.50, 4, w_n_for_time_to_pass_notes },
};
#define CHART_N 10
