// Auto-generated book data for Game Boy Color
// James Joyce - Ulysses (from Project Gutenberg)
// Total pages: 300

#ifndef BOOK_DATA_H
#define BOOK_DATA_H

#define TOTAL_PAGES 300
#define CHARS_PER_LINE 18
#define LINES_PER_PAGE 16

// Page data
const char* const book_pages[] = {
    "[Illustration]\n\nUlysses\n\nby James Joyce\n\nContents\n\n-- I --\n\n[ 1 ]  [ 2 ]  [ 3\n]\n\n-- II --\n\n[ 4 ]  [ 5 ]  [ 6",  // Page 1
    "]  [ 7 ]  [ 8 ]  [\n9 ]  [ 10 ]  [ 11\n]  [ 12 ]  [ 13 ]\n[ 14 ]  [ 15 ]\n\n-- III --\n\n[ 16 ]  [ 17 ]  [\n18 ]\n\n-- I --\n\n[ 1 ]\n\nStately, plump\nBuck Mulligan came",  // Page 2
    "from the\nstairhead, bearing\na bowl of lather\non which a mirror\nand a razor lay\ncrossed. A yellow\ndressinggown,\nungirdled, was\nsustained gently\nbehind him on the\nmild morning air.\nHe held the bowl\naloft and intoned:\n\n--_Introibo ad\naltare Dei_.",  // Page 3
    "Halted, he peered\ndown the dark\nwinding stairs and\ncalled out\ncoarsely:\n\n--Come up, Kinch!\nCome up, you\nfearful jesuit!\n\nSolemnly he came\nforward and\nmounted the round\ngunrest. He faced\nabout and blessed\ngravely thrice the",  // Page 4
    "tower, the\nsurrounding land\nand the awaking\nmountains. Then,\ncatching sight of\nStephen Dedalus,\nhe bent towards\nhim and made rapid\ncrosses in the\nair, gurgling in\nhis throat and\nshaking his head.\nStephen Dedalus,\ndispleased and\nsleepy, leaned his\narms on the top of",  // Page 5
    "the staircase and\nlooked coldly at\nthe shaking\ngurgling face that\nblessed him,\nequine in its\nlength, and at the\nlight untonsured\nhair, grained and\nhued like pale\noak.\n\nBuck Mulligan\npeeped an instant\nunder the mirror\nand then covered",  // Page 6
    "the bowl smartly.\n\n--Back to\nbarracks! he said\nsternly.\n\nHe added in a\npreacher s tone:\n\n--For this, O\ndearly beloved, is\nthe genuine\nChristine: body\nand soul and blood\nand ouns. Slow\nmusic, please.",  // Page 7
    "Shut your eyes,\ngents. One moment.\nA little trouble\nabout those white\ncorpuscles.\nSilence, all.\n\nHe peered sideways\nup and gave a long\nslow whistle of\ncall, then paused\nawhile in rapt\nattention, his\neven white teeth\nglistening here\nand there with",  // Page 8
    "gold points.\nChrysostomos. Two\nstrong shrill\nwhistles answered\nthrough the calm.\n\n--Thanks, old\nchap, he cried\nbriskly. That will\ndo nicely. Switch\noff the current,\nwill you?\n\nHe skipped off the\ngunrest and looked\ngravely at his",  // Page 9
    "watcher, gathering\nabout his legs the\nloose folds of his\ngown. The plump\nshadowed face and\nsullen oval jowl\nrecalled a\nprelate, patron of\narts in the middle\nages. A pleasant\nsmile broke\nquietly over his\nlips.\n\n--The mockery of\nit! he said gaily.",  // Page 10
    "Your absurd name,\nan ancient Greek!\n\nHe pointed his\nfinger in friendly\njest and went over\nto the parapet,\nlaughing to\nhimself. Stephen\nDedalus stepped\nup, followed him\nwearily halfway\nand sat down on\nthe edge of the\ngunrest, watching\nhim still as he",  // Page 11
    "propped his mirror\non the parapet,\ndipped the brush\nin the bowl and\nlathered cheeks\nand neck.\n\nBuck Mulligan s\ngay voice went on.\n\n--My name is\nabsurd too:\nMalachi Mulligan,\ntwo dactyls. But\nit has a Hellenic\nring, hasn t it?",  // Page 12
    "Tripping and sunny\nlike the buck\nhimself. We must\ngo to Athens. Will\nyou come if I can\nget the aunt to\nfork out twenty\nquid?\n\nHe laid the brush\naside and,\nlaughing with\ndelight, cried:\n\n--Will he come?\nThe jejune jesuit!",  // Page 13
    "Ceasing, he began\nto shave with\ncare.\n\n--Tell me,\nMulligan, Stephen\nsaid quietly.\n\n--Yes, my love?\n\n--How long is\nHaines going to\nstay in this\ntower?\n\nBuck Mulligan",  // Page 14
    "showed a shaven\ncheek over his\nright shoulder.\n\n--God, isn t he\ndreadful? he said\nfrankly. A\nponderous Saxon.\nHe thinks you re\nnot a gentleman.\nGod, these bloody\nEnglish! Bursting\nwith money and\nindigestion.\nBecause he comes\nfrom Oxford. You",  // Page 15
    "know, Dedalus, you\nhave the real\nOxford manner. He\ncan t make you\nout. O, my name\nfor you is the\nbest: Kinch, the\nknife-blade.\n\nHe shaved warily\nover his chin.\n\n--He was raving\nall night about a\nblack panther,\nStephen said.",  // Page 16
    "Where is his\nguncase?\n\n--A woful lunatic!\nMulligan said.\nWere you in a\nfunk?\n\n--I was, Stephen\nsaid with energy\nand growing fear.\nOut here in the\ndark with a man I\ndon t know raving\nand moaning to\nhimself about",  // Page 17
    "shooting a black\npanther. You saved\nmen from drowning.\nI m not a hero,\nhowever. If he\nstays on here I am\noff.\n\nBuck Mulligan\nfrowned at the\nlather on his\nrazorblade. He\nhopped down from\nhis perch and\nbegan to search\nhis trouser",  // Page 18
    "pockets hastily.\n\n--Scutter! he\ncried thickly.\n\nHe came over to\nthe gunrest and,\nthrusting a hand\ninto Stephen s\nupper pocket,\nsaid:\n\n--Lend us a loan\nof your noserag to\nwipe my razor.\nStephen suffered",  // Page 19
    "him to pull out\nand hold up on\nshow by its corner\na dirty crumpled\nhandkerchief. Buck\nMulligan wiped the\nrazorblade neatly.\nThen, gazing over\nthe handkerchief,\nhe said:\n\n--The bard s\nnoserag! A new art\ncolour for our\nIrish poets:\nsnotgreen. You can",  // Page 20
    "almost taste it,\ncan t you?\n\nHe mounted to the\nparapet again and\ngazed out over\nDublin bay, his\nfair oakpale hair\nstirring slightly.\n\n--God! he said\nquietly. Isn t the\nsea what Algy\ncalls it: a great\nsweet mother? The\nsnotgreen sea. The",  // Page 21
    "scrotumtightening\nsea. _Epi oinopa\nponton_. Ah,\nDedalus, the\nGreeks! I must\nteach you. You\nmust read them in\nthe original.\n_Thalatta!\nThalatta!_ She is\nour great sweet\nmother. Come and\nlook.\n\nStephen stood up\nand went over to",  // Page 22
    "the parapet.\nLeaning on it he\nlooked down on the\nwater and on the\nmailboat clearing\nthe harbourmouth\nof Kingstown.\n\n--Our mighty\nmother! Buck\nMulligan said.\n\nHe turned abruptly\nhis grey searching\neyes from the sea\nto Stephen s face.",  // Page 23
    "--The aunt thinks\nyou killed your\nmother, he said.\nThat s why she won\nt let me have\nanything to do\nwith you.\n\n--Someone killed\nher, Stephen said\ngloomily.\n\n--You could have\nknelt down, damn\nit, Kinch, when\nyour dying mother",  // Page 24
    "asked you, Buck\nMulligan said. I m\nhyperborean as\nmuch as you. But\nto think of your\nmother begging you\nwith her last\nbreath to kneel\ndown and pray for\nher. And you\nrefused. There is\nsomething sinister\nin you....\n\nHe broke off and\nlathered again",  // Page 25
    "lightly his\nfarther cheek. A\ntolerant smile\ncurled his lips.\n\n--But a lovely\nmummer! he\nmurmured to\nhimself. Kinch,\nthe loveliest\nmummer of them\nall!\n\nHe shaved evenly\nand with care, in\nsilence,",  // Page 26
    "seriously.\n\nStephen, an elbow\nrested on the\njagged granite,\nleaned his palm\nagainst his brow\nand gazed at the\nfraying edge of\nhis shiny black\ncoat-sleeve. Pain,\nthat was not yet\nthe pain of love,\nfretted his heart.\nSilently, in a\ndream she had come",  // Page 27
    "to him after her\ndeath, her wasted\nbody within its\nloose brown\ngraveclothes\ngiving off an\nodour of wax and\nrosewood, her\nbreath, that had\nbent upon him,\nmute, reproachful,\na faint odour of\nwetted ashes.\nAcross the\nthreadbare\ncuffedge he saw",  // Page 28
    "the sea hailed as\na great sweet\nmother by the\nwellfed voice\nbeside him. The\nring of bay and\nskyline held a\ndull green mass of\nliquid. A bowl of\nwhite china had\nstood beside her\ndeathbed holding\nthe green sluggish\nbile which she had\ntorn up from her\nrotting liver by",  // Page 29
    "fits of loud\ngroaning vomiting.\n\nBuck Mulligan\nwiped again his\nrazorblade.\n\n--Ah, poor\ndogsbody! he said\nin a kind voice. I\nmust give you a\nshirt and a few\nnoserags. How are\nthe secondhand\nbreeks?\n--They fit well",  // Page 30
    "enough, Stephen\nanswered.\n\nBuck Mulligan\nattacked the\nhollow beneath his\nunderlip.\n\n--The mockery of\nit, he said\ncontentedly.\nSecondleg they\nshould be. God\nknows what poxy\nbowsy left them\noff. I have a",  // Page 31
    "lovely pair with a\nhair stripe, grey.\nYou ll look\nspiffing in them.\nI m not joking,\nKinch. You look\ndamn well when you\nre dressed.\n\n--Thanks, Stephen\nsaid. I can t wear\nthem if they are\ngrey.\n\n--He can t wear\nthem, Buck",  // Page 32
    "Mulligan told his\nface in the\nmirror. Etiquette\nis etiquette. He\nkills his mother\nbut he can t wear\ngrey trousers.\n\nHe folded his\nrazor neatly and\nwith stroking\npalps of fingers\nfelt the smooth\nskin.\n\nStephen turned his",  // Page 33
    "gaze from the sea\nand to the plump\nface with its\nsmokeblue mobile\neyes.\n\n--That fellow I\nwas with in the\nShip last night,\nsaid Buck\nMulligan, says you\nhave g. p. i. He s\nup in Dottyville\nwith Connolly\nNorman. General\nparalysis of the",  // Page 34
    "insane!\n\nHe swept the\nmirror a half\ncircle in the air\nto flash the\ntidings abroad in\nsunlight now\nradiant on the\nsea. His curling\nshaven lips\nlaughed and the\nedges of his white\nglittering teeth.\nLaughter seized\nall his strong",  // Page 35
    "wellknit trunk.\n\n--Look at\nyourself, he said,\nyou dreadful bard!\n\nStephen bent\nforward and peered\nat the mirror held\nout to him, cleft\nby a crooked\ncrack. Hair on\nend. As he and\nothers see me. Who\nchose this face\nfor me? This",  // Page 36
    "dogsbody to rid of\nvermin. It asks me\ntoo.\n\n--I pinched it out\nof the skivvy s\nroom, Buck\nMulligan said. It\ndoes her all\nright. The aunt\nalways keeps\nplainlooking\nservants for\nMalachi. Lead him\nnot into\ntemptation. And",  // Page 37
    "her name is\nUrsula.\n\nLaughing again, he\nbrought the mirror\naway from Stephen\ns peering eyes.\n\n--The rage of\nCaliban at not\nseeing his face in\na mirror, he said.\nIf Wilde were only\nalive to see you!\n\nDrawing back and",  // Page 38
    "pointing, Stephen\nsaid with\nbitterness:\n\n--It is a symbol\nof Irish art. The\ncracked\nlookingglass of a\nservant.\n\nBuck Mulligan\nsuddenly linked\nhis arm in Stephen\ns and walked with\nhim round the\ntower, his razor",  // Page 39
    "and mirror\nclacking in the\npocket where he\nhad thrust them.\n\n--It s not fair to\ntease you like\nthat, Kinch, is\nit? he said\nkindly. God knows\nyou have more\nspirit than any of\nthem.\n\nParried again. He\nfears the lancet",  // Page 40
    "of my art as I\nfear that of his.\nThe cold steel\npen.\n\n--Cracked\nlookingglass of a\nservant! Tell that\nto the oxy chap\ndownstairs and\ntouch him for a\nguinea. He s\nstinking with\nmoney and thinks\nyou re not a\ngentleman. His old",  // Page 41
    "fellow made his\ntin by selling\njalap to Zulus or\nsome bloody\nswindle or other.\nGod, Kinch, if you\nand I could only\nwork together we\nmight do something\nfor the island.\nHellenise it.\n\nCranly s arm. His\narm.\n\n--And to think of",  // Page 42
    "your having to beg\nfrom these swine.\nI m the only one\nthat knows what\nyou are. Why don t\nyou trust me more?\nWhat have you up\nyour nose against\nme? Is it Haines?\nIf he makes any\nnoise here I ll\nbring down Seymour\nand we ll give him\na ragging worse\nthan they gave\nClive Kempthorpe.",  // Page 43
    "Young shouts of\nmoneyed voices in\nClive Kempthorpe s\nrooms. Palefaces:\nthey hold their\nribs with\nlaughter, one\nclasping another.\nO, I shall expire!\nBreak the news to\nher gently,\nAubrey! I shall\ndie! With slit\nribbons of his\nshirt whipping the\nair he hops and",  // Page 44
    "hobbles round the\ntable, with\ntrousers down at\nheels, chased by\nAdes of Magdalen\nwith the tailor s\nshears. A scared\ncalf s face gilded\nwith marmalade. I\ndon t want to be\ndebagged! Don t\nyou play the giddy\nox with me!\n\nShouts from the\nopen window",  // Page 45
    "startling evening\nin the quadrangle.\nA deaf gardener,\naproned, masked\nwith Matthew\nArnold s face,\npushes his mower\non the sombre lawn\nwatching narrowly\nthe dancing motes\nof grasshalms.\n\nTo ourselves...\nnew paganism...\nomphalos.\n--Let him stay,",  // Page 46
    "Stephen said.\nThere s nothing\nwrong with him\nexcept at night.\n\n--Then what is it?\nBuck Mulligan\nasked impatiently.\nCough it up. I m\nquite frank with\nyou. What have you\nagainst me now?\n\nThey halted,\nlooking towards\nthe blunt cape of",  // Page 47
    "Bray Head that lay\non the water like\nthe snout of a\nsleeping whale.\nStephen freed his\narm quietly.\n\n--Do you wish me\nto tell you? he\nasked.\n\n--Yes, what is it?\nBuck Mulligan\nanswered. I don t\nremember anything.\nHe looked in",  // Page 48
    "Stephen s face as\nhe spoke. A light\nwind passed his\nbrow, fanning\nsoftly his fair\nuncombed hair and\nstirring silver\npoints of anxiety\nin his eyes.\n\nStephen, depressed\nby his own voice,\nsaid:\n\n--Do you remember\nthe first day I",  // Page 49
    "went to your house\nafter my mother s\ndeath?\n\nBuck Mulligan\nfrowned quickly\nand said:\n\n--What? Where? I\ncan t remember\nanything. I\nremember only\nideas and\nsensations. Why?\nWhat happened in\nthe name of God?",  // Page 50
    "--You were making\ntea, Stephen said,\nand went across\nthe landing to get\nmore hot water.\nYour mother and\nsome visitor came\nout of the\ndrawingroom. She\nasked you who was\nin your room.\n\n--Yes? Buck\nMulligan said.\nWhat did I say? I\nforget.",  // Page 51
    "--You said,\nStephen answered,\n_O, it s only\nDedalus whose\nmother is beastly\ndead._\n\nA flush which made\nhim seem younger\nand more engaging\nrose to Buck\nMulligan s cheek.\n\n--Did I say that?\nhe asked. Well?\nWhat harm is that?",  // Page 52
    "He shook his\nconstraint from\nhim nervously.\n\n--And what is\ndeath, he asked,\nyour mother s or\nyours or my own?\nYou saw only your\nmother die. I see\nthem pop off every\nday in the Mater\nand Richmond and\ncut up into tripes\nin the\ndissectingroom. It",  // Page 53
    "s a beastly thing\nand nothing else.\nIt simply doesn t\nmatter. You wouldn\nt kneel down to\npray for your\nmother on her\ndeathbed when she\nasked you. Why?\nBecause you have\nthe cursed jesuit\nstrain in you,\nonly it s injected\nthe wrong way. To\nme it s all a\nmockery and",  // Page 54
    "beastly. Her\ncerebral lobes are\nnot functioning.\nShe calls the\ndoctor sir Peter\nTeazle and picks\nbuttercups off the\nquilt. Humour her\ntill it s over.\nYou crossed her\nlast wish in death\nand yet you sulk\nwith me because I\ndon t whinge like\nsome hired mute\nfrom Lalouette s.",  // Page 55
    "Absurd! I suppose\nI did say it. I\ndidn t mean to\noffend the memory\nof your mother.\n\nHe had spoken\nhimself into\nboldness. Stephen,\nshielding the\ngaping wounds\nwhich the words\nhad left in his\nheart, said very\ncoldly:\n--I am not",  // Page 56
    "thinking of the\noffence to my\nmother.\n\n--Of what then?\nBuck Mulligan\nasked.\n\n--Of the offence\nto me, Stephen\nanswered.\n\nBuck Mulligan\nswung round on his\nheel.\n--O, an impossible",  // Page 57
    "person! he\nexclaimed.\n\nHe walked off\nquickly round the\nparapet. Stephen\nstood at his post,\ngazing over the\ncalm sea towards\nthe headland. Sea\nand headland now\ngrew dim. Pulses\nwere beating in\nhis eyes, veiling\ntheir sight, and\nhe felt the fever",  // Page 58
    "of his cheeks.\n\nA voice within the\ntower called\nloudly:\n\n--Are you up\nthere, Mulligan?\n\n--I m coming, Buck\nMulligan answered.\n\nHe turned towards\nStephen and said:\n\n--Look at the sea.",  // Page 59
    "What does it care\nabout offences?\nChuck Loyola,\nKinch, and come on\ndown. The\nSassenach wants\nhis morning\nrashers.\n\nHis head halted\nagain for a moment\nat the top of the\nstaircase, level\nwith the roof:\n\n--Don t mope over",  // Page 60
    "it all day, he\nsaid. I m\ninconsequent. Give\nup the moody\nbrooding.\n\nHis head vanished\nbut the drone of\nhis descending\nvoice boomed out\nof the stairhead:\n\nAnd no more turn\naside and brood\nUpon love s bitter\nmystery  For",  // Page 61
    "Fergus rules the\nbrazen cars.\n\nWoodshadows\nfloated silently\nby through the\nmorning peace from\nthe stairhead\nseaward where he\ngazed. Inshore and\nfarther out the\nmirror of water\nwhitened, spurned\nby lightshod\nhurrying feet.\nWhite breast of",  // Page 62
    "the dim sea. The\ntwining stresses,\ntwo by two. A hand\nplucking the\nharpstrings,\nmerging their\ntwining chords.\nWavewhite wedded\nwords shimmering\non the dim tide.\n\nA cloud began to\ncover the sun\nslowly, wholly,\nshadowing the bay\nin deeper green.",  // Page 63
    "It lay beneath\nhim, a bowl of\nbitter waters.\nFergus  song: I\nsang it alone in\nthe house, holding\ndown the long dark\nchords. Her door\nwas open: she\nwanted to hear my\nmusic. Silent with\nawe and pity I\nwent to her\nbedside. She was\ncrying in her\nwretched bed. For",  // Page 64
    "those words,\nStephen: love s\nbitter mystery.\n\nWhere now?\n\nHer secrets: old\nfeatherfans,\ntasselled\ndancecards,\npowdered with\nmusk, a gaud of\namber beads in her\nlocked drawer. A\nbirdcage hung in\nthe sunny window",  // Page 65
    "of her house when\nshe was a girl.\nShe heard old\nRoyce sing in the\npantomime of Turko\nthe Terrible and\nlaughed with\nothers when he\nsang:\n\nI am the boy  That\ncan enjoy\nInvisibility.\n\nPhantasmal mirth,\nfolded away:",  // Page 66
    "muskperfumed.\n\nAnd no more turn\naside and brood.\n\nFolded away in the\nmemory of nature\nwith her toys.\nMemories beset his\nbrooding brain.\nHer glass of water\nfrom the kitchen\ntap when she had\napproached the\nsacrament. A cored\napple, filled with",  // Page 67
    "brown sugar,\nroasting for her\nat the hob on a\ndark autumn\nevening. Her\nshapely\nfingernails\nreddened by the\nblood of squashed\nlice from the\nchildren s shirts.\n\nIn a dream,\nsilently, she had\ncome to him, her\nwasted body within",  // Page 68
    "its loose\ngraveclothes\ngiving off an\nodour of wax and\nrosewood, her\nbreath, bent over\nhim with mute\nsecret words, a\nfaint odour of\nwetted ashes.\n\nHer glazing eyes,\nstaring out of\ndeath, to shake\nand bend my soul.\nOn me alone. The",  // Page 69
    "ghostcandle to\nlight her agony.\nGhostly light on\nthe tortured face.\nHer hoarse loud\nbreath rattling in\nhorror, while all\nprayed on their\nknees. Her eyes on\nme to strike me\ndown. _Liliata\nrutilantium te\nconfessorum turma\ncircumdet:\niubilantium te\nvirginum chorus",  // Page 70
    "excipiat._\n\nGhoul! Chewer of\ncorpses!\n\nNo, mother! Let me\nbe and let me\nlive.\n\n--Kinch ahoy!\n\nBuck Mulligan s\nvoice sang from\nwithin the tower.\nIt came nearer up\nthe staircase,",  // Page 71
    "calling again.\nStephen, still\ntrembling at his\nsoul s cry, heard\nwarm running\nsunlight and in\nthe air behind him\nfriendly words.\n\n--Dedalus, come\ndown, like a good\nmosey. Breakfast\nis ready. Haines\nis apologising for\nwaking us last\nnight. It s all",  // Page 72
    "right.\n\n--I m coming,\nStephen said,\nturning.\n\n--Do, for Jesus\nsake, Buck\nMulligan said. For\nmy sake and for\nall our sakes.\n\nHis head\ndisappeared and\nreappeared.\n--I told him your",  // Page 73
    "symbol of Irish\nart. He says it s\nvery clever. Touch\nhim for a quid,\nwill you? A\nguinea, I mean.\n\n--I get paid this\nmorning, Stephen\nsaid.\n\n--The school kip?\nBuck Mulligan\nsaid. How much?\nFour quid? Lend us\none.",  // Page 74
    "--If you want it,\nStephen said.\n\n--Four shining\nsovereigns, Buck\nMulligan cried\nwith delight. We\nll have a glorious\ndrunk to astonish\nthe druidy druids.\nFour omnipotent\nsovereigns.\n\nHe flung up his\nhands and tramped\ndown the stone",  // Page 75
    "stairs, singing\nout of tune with a\nCockney accent:\n\nO, won t we have a\nmerry time,\nDrinking whisky,\nbeer and wine!  On\ncoronation,\nCoronation day!\nO, won t we have a\nmerry time  On\ncoronation day!\n\nWarm sunshine\nmerrying over the",  // Page 76
    "sea. The nickel\nshavingbowl shone,\nforgotten, on the\nparapet. Why\nshould I bring it\ndown? Or leave it\nthere all day,\nforgotten\nfriendship?\n\nHe went over to\nit, held it in his\nhands awhile,\nfeeling its\ncoolness, smelling\nthe clammy slaver",  // Page 77
    "of the lather in\nwhich the brush\nwas stuck. So I\ncarried the boat\nof incense then at\nClongowes. I am\nanother now and\nyet the same. A\nservant too. A\nserver of a\nservant.\n\nIn the gloomy\ndomed livingroom\nof the tower Buck\nMulligan s gowned",  // Page 78
    "form moved briskly\nto and fro about\nthe hearth, hiding\nand revealing its\nyellow glow. Two\nshafts of soft\ndaylight fell\nacross the flagged\nfloor from the\nhigh barbacans:\nand at the meeting\nof their rays a\ncloud of coalsmoke\nand fumes of fried\ngrease floated,\nturning.",  // Page 79
    "--We ll be choked,\nBuck Mulligan\nsaid. Haines, open\nthat door, will\nyou?\n\nStephen laid the\nshavingbowl on the\nlocker. A tall\nfigure rose from\nthe hammock where\nit had been\nsitting, went to\nthe doorway and\npulled open the\ninner doors.",  // Page 80
    "--Have you the\nkey? a voice\nasked.\n\n--Dedalus has it,\nBuck Mulligan\nsaid. Janey Mack,\nI m choked!\n\nHe howled, without\nlooking up from\nthe fire:\n\n--Kinch!\n\n--It s in the",  // Page 81
    "lock, Stephen\nsaid, coming\nforward.\n\nThe key scraped\nround harshly\ntwice and, when\nthe heavy door had\nbeen set ajar,\nwelcome light and\nbright air\nentered. Haines\nstood at the\ndoorway, looking\nout. Stephen haled\nhis upended valise",  // Page 82
    "to the table and\nsat down to wait.\nBuck Mulligan\ntossed the fry on\nto the dish beside\nhim. Then he\ncarried the dish\nand a large teapot\nover to the table,\nset them down\nheavily and sighed\nwith relief.\n\n--I m melting, he\nsaid, as the\ncandle remarked",  // Page 83
    "when... But, hush!\nNot a word more on\nthat subject!\nKinch, wake up!\nBread, butter,\nhoney. Haines,\ncome in. The grub\nis ready. Bless\nus, O Lord, and\nthese thy gifts.\nWhere s the sugar?\nO, jay, there s no\nmilk.\n\nStephen fetched\nthe loaf and the",  // Page 84
    "pot of honey and\nthe buttercooler\nfrom the locker.\nBuck Mulligan sat\ndown in a sudden\npet.\n\n--What sort of a\nkip is this? he\nsaid. I told her\nto come after\neight.\n\n--We can drink it\nblack, Stephen\nsaid thirstily.",  // Page 85
    "There s a lemon in\nthe locker.\n\n--O, damn you and\nyour Paris fads!\nBuck Mulligan\nsaid. I want\nSandycove milk.\n\nHaines came in\nfrom the doorway\nand said quietly:\n\n--That woman is\ncoming up with the\nmilk.",  // Page 86
    "--The blessings of\nGod on you! Buck\nMulligan cried,\njumping up from\nhis chair. Sit\ndown. Pour out the\ntea there. The\nsugar is in the\nbag. Here, I can t\ngo fumbling at the\ndamned eggs.\n\nHe hacked through\nthe fry on the\ndish and slapped\nit out on three",  // Page 87
    "plates, saying:\n\n--_In nomine\nPatris et Filii et\nSpiritus Sancti._\n\nHaines sat down to\npour out the tea.\n\n--I m giving you\ntwo lumps each, he\nsaid. But, I say,\nMulligan, you do\nmake strong tea,\ndon t you?\nBuck Mulligan,",  // Page 88
    "hewing thick\nslices from the\nloaf, said in an\nold woman s\nwheedling voice:\n\n--When I makes tea\nI makes tea, as\nold mother Grogan\nsaid. And when I\nmakes water I\nmakes water.\n\n--By Jove, it is\ntea, Haines said.\nBuck Mulligan went",  // Page 89
    "on hewing and\nwheedling:\n\n--_So I do, Mrs\nCahill,_ says she.\n_Begob, ma am,_\nsays Mrs Cahill,\n_God send you don\nt make them in the\none pot._\n\nHe lunged towards\nhis messmates in\nturn a thick slice\nof bread, impaled\non his knife.",  // Page 90
    "--That s folk, he\nsaid very\nearnestly, for\nyour book, Haines.\nFive lines of text\nand ten pages of\nnotes about the\nfolk and the\nfishgods of\nDundrum. Printed\nby the weird\nsisters in the\nyear of the big\nwind.\n\nHe turned to",  // Page 91
    "Stephen and asked\nin a fine puzzled\nvoice, lifting his\nbrows:\n\n--Can you recall,\nbrother, is mother\nGrogan s tea and\nwater pot spoken\nof in the\nMabinogion or is\nit in the\nUpanishads?\n\n--I doubt it, said\nStephen gravely.",  // Page 92
    "--Do you now? Buck\nMulligan said in\nthe same tone.\nYour reasons,\npray?\n\n--I fancy, Stephen\nsaid as he ate, it\ndid not exist in\nor out of the\nMabinogion. Mother\nGrogan was, one\nimagines, a\nkinswoman of Mary\nAnn.\nBuck Mulligan s",  // Page 93
    "face smiled with\ndelight.\n\n--Charming! he\nsaid in a finical\nsweet voice,\nshowing his white\nteeth and blinking\nhis eyes\npleasantly. Do you\nthink she was?\nQuite charming!\n\nThen, suddenly\noverclouding all\nhis features, he",  // Page 94
    "growled in a\nhoarsened rasping\nvoice as he hewed\nagain vigorously\nat the loaf:\n\n_--For old Mary\nAnn\n\nShe doesn t care a\ndamn.\n\nBut, hising up her\npetticoats..._\n\nHe crammed his",  // Page 95
    "mouth with fry and\nmunched and\ndroned.\n\nThe doorway was\ndarkened by an\nentering form.\n\n--The milk, sir!\n\n--Come in, ma am,\nMulligan said.\nKinch, get the\njug.\n\nAn old woman came",  // Page 96
    "forward and stood\nby Stephen s\nelbow.\n\n--That s a lovely\nmorning, sir, she\nsaid. Glory be to\nGod.\n\n--To whom?\nMulligan said,\nglancing at her.\nAh, to be sure!\n\nStephen reached\nback and took the",  // Page 97
    "milkjug from the\nlocker.\n\n--The islanders,\nMulligan said to\nHaines casually,\nspeak frequently\nof the collector\nof prepuces.\n\n--How much, sir?\nasked the old\nwoman.\n\n--A quart, Stephen\nsaid.",  // Page 98
    "He watched her\npour into the\nmeasure and thence\ninto the jug rich\nwhite milk, not\nhers. Old shrunken\npaps. She poured\nagain a measureful\nand a tilly. Old\nand secret she had\nentered from a\nmorning world,\nmaybe a messenger.\nShe praised the\ngoodness of the\nmilk, pouring it",  // Page 99
    "out. Crouching by\na patient cow at\ndaybreak in the\nlush field, a\nwitch on her\ntoadstool, her\nwrinkled fingers\nquick at the\nsquirting dugs.\nThey lowed about\nher whom they\nknew, dewsilky\ncattle. Silk of\nthe kine and poor\nold woman, names\ngiven her in old",  // Page 100
    "times. A wandering\ncrone, lowly form\nof an immortal\nserving her\nconqueror and her\ngay betrayer,\ntheir common\ncuckquean, a\nmessenger from the\nsecret morning. To\nserve or to\nupbraid, whether\nhe could not tell:\nbut scorned to beg\nher favour.\n--It is indeed, ma",  // Page 101
    "am, Buck Mulligan\nsaid, pouring milk\ninto their cups.\n\n--Taste it, sir,\nshe said.\n\nHe drank at her\nbidding.\n\n--If we could live\non good food like\nthat, he said to\nher somewhat\nloudly, we wouldn\nt have the country",  // Page 102
    "full of rotten\nteeth and rotten\nguts. Living in a\nbogswamp, eating\ncheap food and the\nstreets paved with\ndust, horsedung\nand consumptives\nspits.\n\n--Are you a\nmedical student,\nsir? the old woman\nasked.\n\n--I am, ma am,",  // Page 103
    "Buck Mulligan\nanswered.\n\n--Look at that\nnow, she said.\n\nStephen listened\nin scornful\nsilence. She bows\nher old head to a\nvoice that speaks\nto her loudly, her\nbonesetter, her\nmedicineman: me\nshe slights. To\nthe voice that",  // Page 104
    "will shrive and\noil for the grave\nall there is of\nher but her woman\ns unclean loins,\nof man s flesh\nmade not in God s\nlikeness, the\nserpent s prey.\nAnd to the loud\nvoice that now\nbids her be silent\nwith wondering\nunsteady eyes.\n\n--Do you",  // Page 105
    "understand what he\nsays? Stephen\nasked her.\n\n--Is it French you\nare talking, sir?\nthe old woman said\nto Haines.\n\nHaines spoke to\nher again a longer\nspeech,\nconfidently.\n\n--Irish, Buck\nMulligan said. Is",  // Page 106
    "there Gaelic on\nyou?\n\n--I thought it was\nIrish, she said,\nby the sound of\nit. Are you from\nthe west, sir?\n\n--I am an\nEnglishman, Haines\nanswered.\n\n--He s English,\nBuck Mulligan\nsaid, and he",  // Page 107
    "thinks we ought to\nspeak Irish in\nIreland.\n\n--Sure we ought\nto, the old woman\nsaid, and I m\nashamed I don t\nspeak the language\nmyself. I m told\nit s a grand\nlanguage by them\nthat knows.\n\n--Grand is no name\nfor it, said Buck",  // Page 108
    "Mulligan.\nWonderful\nentirely. Fill us\nout some more tea,\nKinch. Would you\nlike a cup, ma am?\n\n--No, thank you,\nsir, the old woman\nsaid, slipping the\nring of the\nmilkcan on her\nforearm and about\nto go.\n\nHaines said to",  // Page 109
    "her:\n\n--Have you your\nbill? We had\nbetter pay her,\nMulligan, hadn t\nwe?\n\nStephen filled\nagain the three\ncups.\n\n--Bill, sir? she\nsaid, halting.\nWell, it s seven\nmornings a pint at",  // Page 110
    "twopence is seven\ntwos is a shilling\nand twopence over\nand these three\nmornings a quart\nat fourpence is\nthree quarts is a\nshilling. That s a\nshilling and one\nand two is two and\ntwo, sir.\n\nBuck Mulligan\nsighed and, having\nfilled his mouth\nwith a crust",  // Page 111
    "thickly buttered\non both sides,\nstretched forth\nhis legs and began\nto search his\ntrouser pockets.\n\n--Pay up and look\npleasant, Haines\nsaid to him,\nsmiling.\n\nStephen filled a\nthird cup, a\nspoonful of tea\ncolouring faintly",  // Page 112
    "the thick rich\nmilk. Buck\nMulligan brought\nup a florin,\ntwisted it round\nin his fingers and\ncried:\n\n--A miracle!\n\nHe passed it along\nthe table towards\nthe old woman,\nsaying:\n\n--Ask nothing more",  // Page 113
    "of me, sweet. All\nI can give you I\ngive.\n\nStephen laid the\ncoin in her\nuneager hand.\n\n--We ll owe\ntwopence, he said.\n\n--Time enough,\nsir, she said,\ntaking the coin.\nTime enough. Good\nmorning, sir.",  // Page 114
    "She curtseyed and\nwent out, followed\nby Buck Mulligan s\ntender chant:\n\n_--Heart of my\nheart, were it\nmore,\n\nMore would be laid\nat your feet._\n\nHe turned to\nStephen and said:\n\n--Seriously,",  // Page 115
    "Dedalus. I m\nstony. Hurry out\nto your school kip\nand bring us back\nsome money. Today\nthe bards must\ndrink and junket.\nIreland expects\nthat every man\nthis day will do\nhis duty.\n\n--That reminds me,\nHaines said,\nrising, that I\nhave to visit your",  // Page 116
    "national library\ntoday.\n\n--Our swim first,\nBuck Mulligan\nsaid.\n\nHe turned to\nStephen and asked\nblandly:\n\n--Is this the day\nfor your monthly\nwash, Kinch?\n\nThen he said to",  // Page 117
    "Haines:\n\n--The unclean bard\nmakes a point of\nwashing once a\nmonth.\n\n--All Ireland is\nwashed by the\ngulfstream,\nStephen said as he\nlet honey trickle\nover a slice of\nthe loaf.\n\nHaines from the",  // Page 118
    "corner where he\nwas knotting\neasily a scarf\nabout the loose\ncollar of his\ntennis shirt\nspoke:\n\n--I intend to make\na collection of\nyour sayings if\nyou will let me.\n\nSpeaking to me.\nThey wash and tub\nand scrub.",  // Page 119
    "Agenbite of inwit.\nConscience. Yet\nhere s a spot.\n\n--That one about\nthe cracked\nlookingglass of a\nservant being the\nsymbol of Irish\nart is deuced\ngood.\n\nBuck Mulligan\nkicked Stephen s\nfoot under the\ntable and said",  // Page 120
    "with warmth of\ntone:\n\n--Wait till you\nhear him on\nHamlet, Haines.\n\n--Well, I mean it,\nHaines said, still\nspeaking to\nStephen. I was\njust thinking of\nit when that poor\nold creature came\nin.\n--Would I make any",  // Page 121
    "money by it?\nStephen asked.\n\nHaines laughed\nand, as he took\nhis soft grey hat\nfrom the holdfast\nof the hammock,\nsaid:\n\n--I don t know, I\nm sure.\n\nHe strolled out to\nthe doorway. Buck\nMulligan bent",  // Page 122
    "across to Stephen\nand said with\ncoarse vigour:\n\n--You put your\nhoof in it now.\nWhat did you say\nthat for?\n\n--Well? Stephen\nsaid. The problem\nis to get money.\nFrom whom? From\nthe milkwoman or\nfrom him. It s a\ntoss up, I think.",  // Page 123
    "--I blow him out\nabout you, Buck\nMulligan said, and\nthen you come\nalong with your\nlousy leer and\nyour gloomy jesuit\njibes.\n\n--I see little\nhope, Stephen\nsaid, from her or\nfrom him.\n\nBuck Mulligan\nsighed tragically",  // Page 124
    "and laid his hand\non Stephen s arm.\n\n--From me, Kinch,\nhe said.\n\nIn a suddenly\nchanged tone he\nadded:\n\n--To tell you the\nGod s truth I\nthink you re\nright. Damn all\nelse they are good\nfor. Why don t you",  // Page 125
    "play them as I do?\nTo hell with them\nall. Let us get\nout of the kip.\n\nHe stood up,\ngravely ungirdled\nand disrobed\nhimself of his\ngown, saying\nresignedly:\n\n--Mulligan is\nstripped of his\ngarments.\nHe emptied his",  // Page 126
    "pockets on to the\ntable.\n\n--There s your\nsnotrag, he said.\n\nAnd putting on his\nstiff collar and\nrebellious tie he\nspoke to them,\nchiding them, and\nto his dangling\nwatchchain. His\nhands plunged and\nrummaged in his\ntrunk while he",  // Page 127
    "called for a clean\nhandkerchief. God,\nwe ll simply have\nto dress the\ncharacter. I want\npuce gloves and\ngreen boots.\nContradiction. Do\nI contradict\nmyself? Very well\nthen, I contradict\nmyself. Mercurial\nMalachi. A limp\nblack missile flew\nout of his talking\nhands.",  // Page 128
    "--And there s your\nLatin quarter hat,\nhe said.\n\nStephen picked it\nup and put it on.\nHaines called to\nthem from the\ndoorway:\n\n--Are you coming,\nyou fellows?\n\n--I m ready, Buck\nMulligan answered,\ngoing towards the",  // Page 129
    "door. Come out,\nKinch. You have\neaten all we left,\nI suppose.\nResigned he passed\nout with grave\nwords and gait,\nsaying, wellnigh\nwith sorrow:\n\n--And going forth\nhe met Butterly.\n\nStephen, taking\nhis ashplant from\nits leaningplace,",  // Page 130
    "followed them out\nand, as they went\ndown the ladder,\npulled to the slow\niron door and\nlocked it. He put\nthe huge key in\nhis inner pocket.\n\nAt the foot of the\nladder Buck\nMulligan asked:\n\n--Did you bring\nthe key?\n--I have it,",  // Page 131
    "Stephen said,\npreceding them.\n\nHe walked on.\nBehind him he\nheard Buck\nMulligan club with\nhis heavy\nbathtowel the\nleader shoots of\nferns or grasses.\n\n--Down, sir! How\ndare you, sir!\n\nHaines asked:",  // Page 132
    "--Do you pay rent\nfor this tower?\n\n--Twelve quid,\nBuck Mulligan\nsaid.\n\n--To the secretary\nof state for war,\nStephen added over\nhis shoulder.\n\nThey halted while\nHaines surveyed\nthe tower and said\nat last:",  // Page 133
    "--Rather bleak in\nwintertime, I\nshould say.\nMartello you call\nit?\n\n--Billy Pitt had\nthem built, Buck\nMulligan said,\nwhen the French\nwere on the sea.\nBut ours is the\n_omphalos_.\n\n--What is your\nidea of Hamlet?",  // Page 134
    "Haines asked\nStephen.\n\n--No, no, Buck\nMulligan shouted\nin pain. I m not\nequal to Thomas\nAquinas and the\nfiftyfive reasons\nhe has made out to\nprop it up. Wait\ntill I have a few\npints in me first.\n\nHe turned to\nStephen, saying,",  // Page 135
    "as he pulled down\nneatly the peaks\nof his primrose\nwaistcoat:\n\n--You couldn t\nmanage it under\nthree pints,\nKinch, could you?\n\n--It has waited so\nlong, Stephen said\nlistlessly, it can\nwait longer.\n\n--You pique my",  // Page 136
    "curiosity, Haines\nsaid amiably. Is\nit some paradox?\n\n--Pooh! Buck\nMulligan said. We\nhave grown out of\nWilde and\nparadoxes. It s\nquite simple. He\nproves by algebra\nthat Hamlet s\ngrandson is\nShakespeare s\ngrandfather and\nthat he himself is",  // Page 137
    "the ghost of his\nown father.\n\n--What? Haines\nsaid, beginning to\npoint at Stephen.\nHe himself?\n\nBuck Mulligan\nslung his towel\nstolewise round\nhis neck and,\nbending in loose\nlaughter, said to\nStephen s ear:\n--O, shade of",  // Page 138
    "Kinch the elder!\nJaphet in search\nof a father!\n\n--We re always\ntired in the\nmorning, Stephen\nsaid to Haines.\nAnd it is rather\nlong to tell.\n\nBuck Mulligan,\nwalking forward\nagain, raised his\nhands.\n--The sacred pint",  // Page 139
    "alone can unbind\nthe tongue of\nDedalus, he said.\n\n--I mean to say,\nHaines explained\nto Stephen as they\nfollowed, this\ntower and these\ncliffs here remind\nme somehow of\nElsinore. _That\nbeetles o er his\nbase into the\nsea,_ isn t it?\nBuck Mulligan",  // Page 140
    "turned suddenly\nfor an instant\ntowards Stephen\nbut did not speak.\nIn the bright\nsilent instant\nStephen saw his\nown image in cheap\ndusty mourning\nbetween their gay\nattires.\n\n--It s a wonderful\ntale, Haines said,\nbringing them to\nhalt again.",  // Page 141
    "Eyes, pale as the\nsea the wind had\nfreshened, paler,\nfirm and prudent.\nThe seas ruler, he\ngazed southward\nover the bay,\nempty save for the\nsmokeplume of the\nmailboat vague on\nthe bright skyline\nand a sail tacking\nby the Muglins.\n\n--I read a\ntheological",  // Page 142
    "interpretation of\nit somewhere, he\nsaid bemused. The\nFather and the Son\nidea. The Son\nstriving to be\natoned with the\nFather.\n\nBuck Mulligan at\nonce put on a\nblithe broadly\nsmiling face. He\nlooked at them,\nhis wellshaped\nmouth open",  // Page 143
    "happily, his eyes,\nfrom which he had\nsuddenly withdrawn\nall shrewd sense,\nblinking with mad\ngaiety. He moved a\ndoll s head to and\nfro, the brims of\nhis Panama hat\nquivering, and\nbegan to chant in\na quiet happy\nfoolish voice:\n\n_--I m the\nqueerest young",  // Page 144
    "fellow that ever\nyou heard. My\nmother s a jew, my\nfather s a bird.\nWith Joseph the\njoiner I cannot\nagree. So here s\nto disciples and\nCalvary._\n\nHe held up a\nforefinger of\nwarning.\n\n_--If anyone\nthinks that I amn",  // Page 145
    "t divine He ll get\nno free drinks\nwhen I m making\nthe wine But have\nto drink water and\nwish it were plain\nThat I make when\nthe wine becomes\nwater again._\n\nHe tugged swiftly\nat Stephen s\nashplant in\nfarewell and,\nrunning forward to\na brow of the",  // Page 146
    "cliff, fluttered\nhis hands at his\nsides like fins or\nwings of one about\nto rise in the\nair, and chanted:\n\n_--Goodbye, now,\ngoodbye! Write\ndown all I said\nAnd tell Tom, Dick\nand Harry I rose\nfrom the dead.\nWhat s bred in the\nbone cannot fail\nme to fly And",  // Page 147
    "Olivet s breezy...\nGoodbye, now,\ngoodbye!_\n\nHe capered before\nthem down towards\nthe fortyfoot\nhole, fluttering\nhis winglike\nhands, leaping\nnimbly, Mercury s\nhat quivering in\nthe fresh wind\nthat bore back to\nthem his brief\nbirdsweet cries.",  // Page 148
    "Haines, who had\nbeen laughing\nguardedly, walked\non beside Stephen\nand said:\n\n--We oughtn t to\nlaugh, I suppose.\nHe s rather\nblasphemous. I m\nnot a believer\nmyself, that is to\nsay. Still his\ngaiety takes the\nharm out of it\nsomehow, doesn t",  // Page 149
    "it? What did he\ncall it? Joseph\nthe Joiner?\n\n--The ballad of\njoking Jesus,\nStephen answered.\n\n--O, Haines said,\nyou have heard it\nbefore?\n\n--Three times a\nday, after meals,\nStephen said\ndrily.",  // Page 150
    "--You re not a\nbeliever, are you?\nHaines asked. I\nmean, a believer\nin the narrow\nsense of the word.\nCreation from\nnothing and\nmiracles and a\npersonal God.\n\n--There s only one\nsense of the word,\nit seems to me,\nStephen said.\nHaines stopped to",  // Page 151
    "take out a smooth\nsilver case in\nwhich twinkled a\ngreen stone. He\nsprang it open\nwith his thumb and\noffered it.\n\n--Thank you,\nStephen said,\ntaking a\ncigarette.\n\nHaines helped\nhimself and\nsnapped the case",  // Page 152
    "to. He put it back\nin his sidepocket\nand took from his\nwaistcoatpocket a\nnickel tinderbox,\nsprang it open\ntoo, and, having\nlit his cigarette,\nheld the flaming\nspunk towards\nStephen in the\nshell of his\nhands.\n\n--Yes, of course,\nhe said, as they",  // Page 153
    "went on again.\nEither you believe\nor you don t, isn\nt it? Personally I\ncouldn t stomach\nthat idea of a\npersonal God. You\ndon t stand for\nthat, I suppose?\n\n--You behold in\nme, Stephen said\nwith grim\ndispleasure, a\nhorrible example\nof free thought.",  // Page 154
    "He walked on,\nwaiting to be\nspoken to,\ntrailing his\nashplant by his\nside. Its ferrule\nfollowed lightly\non the path,\nsquealing at his\nheels. My\nfamiliar, after\nme, calling, Steee\neeeeeeeeephen! A\nwavering line\nalong the path.\nThey will walk on",  // Page 155
    "it tonight, coming\nhere in the dark.\nHe wants that key.\nIt is mine. I paid\nthe rent. Now I\neat his salt\nbread. Give him\nthe key too. All.\nHe will ask for\nit. That was in\nhis eyes.\n\n--After all,\nHaines began...\n\nStephen turned and",  // Page 156
    "saw that the cold\ngaze which had\nmeasured him was\nnot all unkind.\n\n--After all, I\nshould think you\nare able to free\nyourself. You are\nyour own master,\nit seems to me.\n\n--I am a servant\nof two masters,\nStephen said, an\nEnglish and an",  // Page 157
    "Italian.\n\n--Italian? Haines\nsaid.\n\nA crazy queen, old\nand jealous. Kneel\ndown before me.\n\n--And a third,\nStephen said,\nthere is who wants\nme for odd jobs.\n\n--Italian? Haines\nsaid again. What",  // Page 158
    "do you mean?\n\n--The imperial\nBritish state,\nStephen answered,\nhis colour rising,\nand the holy Roman\ncatholic and\napostolic church.\n\nHaines detached\nfrom his underlip\nsome fibres of\ntobacco before he\nspoke.\n--I can quite",  // Page 159
    "understand that,\nhe said calmly. An\nIrishman must\nthink like that, I\ndaresay. We feel\nin England that we\nhave treated you\nrather unfairly.\nIt seems history\nis to blame.\n\nThe proud potent\ntitles clanged\nover Stephen s\nmemory the triumph\nof their brazen",  // Page 160
    "bells: _et unam\nsanctam catholicam\net apostolicam\necclesiam:_ the\nslow growth and\nchange of rite and\ndogma like his own\nrare thoughts, a\nchemistry of\nstars. Symbol of\nthe apostles in\nthe mass for pope\nMarcellus, the\nvoices blended,\nsinging alone loud\nin affirmation:",  // Page 161
    "and behind their\nchant the vigilant\nangel of the\nchurch militant\ndisarmed and\nmenaced her\nheresiarchs. A\nhorde of heresies\nfleeing with\nmitres awry:\nPhotius and the\nbrood of mockers\nof whom Mulligan\nwas one, and\nArius, warring his\nlife long upon the",  // Page 162
    "consubstantiality\nof the Son with\nthe Father, and\nValentine,\nspurning Christ s\nterrene body, and\nthe subtle African\nheresiarch\nSabellius who held\nthat the Father\nwas Himself His\nown Son. Words\nMulligan had\nspoken a moment\nsince in mockery\nto the stranger.",  // Page 163
    "Idle mockery. The\nvoid awaits surely\nall them that\nweave the wind: a\nmenace, a\ndisarming and a\nworsting from\nthose embattled\nangels of the\nchurch, Michael s\nhost, who defend\nher ever in the\nhour of conflict\nwith their lances\nand their shields.\nHear, hear!",  // Page 164
    "Prolonged\napplause. _Zut!\nNom de Dieu!_\n\n--Of course I m a\nBritisher, Haines\ns voice said, and\nI feel as one. I\ndon t want to see\nmy country fall\ninto the hands of\nGerman jews\neither. That s our\nnational problem,\nI m afraid, just\nnow.",  // Page 165
    "Two men stood at\nthe verge of the\ncliff, watching:\nbusinessman,\nboatman.\n\n--She s making for\nBullock harbour.\n\nThe boatman nodded\ntowards the north\nof the bay with\nsome disdain.\n\n--There s five\nfathoms out there,",  // Page 166
    "he said. It ll be\nswept up that way\nwhen the tide\ncomes in about\none. It s nine\ndays today.\n\nThe man that was\ndrowned. A sail\nveering about the\nblank bay waiting\nfor a swollen\nbundle to bob up,\nroll over to the\nsun a puffy face,\nsaltwhite. Here I",  // Page 167
    "am.\n\nThey followed the\nwinding path down\nto the creek. Buck\nMulligan stood on\na stone, in\nshirtsleeves, his\nunclipped tie\nrippling over his\nshoulder. A young\nman clinging to a\nspur of rock near\nhim, moved slowly\nfrogwise his green\nlegs in the deep",  // Page 168
    "jelly of the\nwater.\n\n--Is the brother\nwith you, Malachi?\n\n--Down in\nWestmeath. With\nthe Bannons.\n\n--Still there? I\ngot a card from\nBannon. Says he\nfound a sweet\nyoung thing down\nthere. Photo girl",  // Page 169
    "he calls her.\n\n--Snapshot, eh?\nBrief exposure.\n\nBuck Mulligan sat\ndown to unlace his\nboots. An elderly\nman shot up near\nthe spur of rock a\nblowing red face.\nHe scrambled up by\nthe stones, water\nglistening on his\npate and on its\ngarland of grey",  // Page 170
    "hair, water\nrilling over his\nchest and paunch\nand spilling jets\nout of his black\nsagging loincloth.\n\nBuck Mulligan made\nway for him to\nscramble past and,\nglancing at Haines\nand Stephen,\ncrossed himself\npiously with his\nthumbnail at brow\nand lips and",  // Page 171
    "breastbone.\n\n--Seymour s back\nin town, the young\nman said, grasping\nagain his spur of\nrock. Chucked\nmedicine and going\nin for the army.\n\n--Ah, go to God!\nBuck Mulligan\nsaid.\n\n--Going over next\nweek to stew. You",  // Page 172
    "know that red\nCarlisle girl,\nLily?\n\n--Yes.\n\n--Spooning with\nhim last night on\nthe pier. The\nfather is rotto\nwith money.\n\n--Is she up the\npole?\n\n--Better ask",  // Page 173
    "Seymour that.\n\n--Seymour a\nbleeding officer!\nBuck Mulligan\nsaid.\n\nHe nodded to\nhimself as he drew\noff his trousers\nand stood up,\nsaying tritely:\n\n--Redheaded women\nbuck like goats.\nHe broke off in",  // Page 174
    "alarm, feeling his\nside under his\nflapping shirt.\n\n--My twelfth rib\nis gone, he cried.\nI m the _\nbermensch._\nToothless Kinch\nand I, the\nsupermen.\n\nHe struggled out\nof his shirt and\nflung it behind\nhim to where his",  // Page 175
    "clothes lay.\n\n--Are you going in\nhere, Malachi?\n\n--Yes. Make room\nin the bed.\n\nThe young man\nshoved himself\nbackward through\nthe water and\nreached the middle\nof the creek in\ntwo long clean\nstrokes. Haines",  // Page 176
    "sat down on a\nstone, smoking.\n\n--Are you not\ncoming in? Buck\nMulligan asked.\n\n--Later on, Haines\nsaid. Not on my\nbreakfast.\n\nStephen turned\naway.\n\n--I m going,\nMulligan, he said.",  // Page 177
    "--Give us that\nkey, Kinch, Buck\nMulligan said, to\nkeep my chemise\nflat.\n\nStephen handed him\nthe key. Buck\nMulligan laid it\nacross his heaped\nclothes.\n\n--And twopence, he\nsaid, for a pint.\nThrow it there.\nStephen threw two",  // Page 178
    "pennies on the\nsoft heap.\nDressing,\nundressing. Buck\nMulligan erect,\nwith joined hands\nbefore him, said\nsolemnly:\n\n--He who stealeth\nfrom the poor\nlendeth to the\nLord. Thus spake\nZarathustra.\n\nHis plump body",  // Page 179
    "plunged.\n\n--We ll see you\nagain, Haines\nsaid, turning as\nStephen walked up\nthe path and\nsmiling at wild\nIrish.\n\nHorn of a bull,\nhoof of a horse,\nsmile of a Saxon.\n\n--The Ship, Buck\nMulligan cried.",  // Page 180
    "Half twelve.\n\n--Good, Stephen\nsaid.\n\nHe walked along\nthe upwardcurving\npath.\n\nLiliata\nrutilantium.\nTurma circumdet.\nIubilantium te\nvirginum.\n\nThe priest s grey",  // Page 181
    "nimbus in a niche\nwhere he dressed\ndiscreetly. I will\nnot sleep here\ntonight. Home also\nI cannot go.\n\nA voice,\nsweettoned and\nsustained, called\nto him from the\nsea. Turning the\ncurve he waved his\nhand. It called\nagain. A sleek\nbrown head, a seal",  // Page 182
    "s, far out on the\nwater, round.\n\nUsurper.\n\n[ 2 ]\n\n--You, Cochrane,\nwhat city sent for\nhim?\n\n--Tarentum, sir.\n\n--Very good. Well?\n\n--There was a",  // Page 183
    "battle, sir.\n\n--Very good.\nWhere?\n\nThe boy s blank\nface asked the\nblank window.\n\nFabled by the\ndaughters of\nmemory. And yet it\nwas in some way if\nnot as memory\nfabled it. A\nphrase, then, of",  // Page 184
    "impatience, thud\nof Blake s wings\nof excess. I hear\nthe ruin of all\nspace, shattered\nglass and toppling\nmasonry, and time\none livid final\nflame. What s left\nus then?\n\n--I forget the\nplace, sir. 279 B.\nC.\n\n--Asculum, Stephen",  // Page 185
    "said, glancing at\nthe name and date\nin the gorescarred\nbook.\n\n--Yes, sir. And he\nsaid: _Another\nvictory like that\nand we are done\nfor._\n\nThat phrase the\nworld had\nremembered. A dull\nease of the mind.\nFrom a hill above",  // Page 186
    "a corpsestrewn\nplain a general\nspeaking to his\nofficers, leaned\nupon his spear.\nAny general to any\nofficers. They\nlend ear.\n\n--You, Armstrong,\nStephen said. What\nwas the end of\nPyrrhus?\n\n--End of Pyrrhus,\nsir?",  // Page 187
    "--I know, sir. Ask\nme, sir, Comyn\nsaid.\n\n--Wait. You,\nArmstrong. Do you\nknow anything\nabout Pyrrhus?\n\nA bag of figrolls\nlay snugly in\nArmstrong s\nsatchel. He curled\nthem between his\npalms at whiles\nand swallowed them",  // Page 188
    "softly. Crumbs\nadhered to the\ntissue of his\nlips. A sweetened\nboy s breath.\nWelloff people,\nproud that their\neldest son was in\nthe navy. Vico\nRoad, Dalkey.\n\n--Pyrrhus, sir?\nPyrrhus, a pier.\n\nAll laughed.\nMirthless high",  // Page 189
    "malicious\nlaughter.\nArmstrong looked\nround at his\nclassmates, silly\nglee in profile.\nIn a moment they\nwill laugh more\nloudly, aware of\nmy lack of rule\nand of the fees\ntheir papas pay.\n\n--Tell me now,\nStephen said,\npoking the boy s",  // Page 190
    "shoulder with the\nbook, what is a\npier.\n\n--A pier, sir,\nArmstrong said. A\nthing out in the\nwater. A kind of a\nbridge. Kingstown\npier, sir.\n\nSome laughed\nagain: mirthless\nbut with meaning.\nTwo in the back\nbench whispered.",  // Page 191
    "Yes. They knew:\nhad never learned\nnor ever been\ninnocent. All.\nWith envy he\nwatched their\nfaces: Edith,\nEthel, Gerty,\nLily. Their likes:\ntheir breaths,\ntoo, sweetened\nwith tea and jam,\ntheir bracelets\ntittering in the\nstruggle.\n--Kingstown pier,",  // Page 192
    "Stephen said. Yes,\na disappointed\nbridge.\n\nThe words troubled\ntheir gaze.\n\n--How, sir? Comyn\nasked. A bridge is\nacross a river.\n\nFor Haines s\nchapbook. No-one\nhere to hear.\nTonight deftly\namid wild drink",  // Page 193
    "and talk, to\npierce the\npolished mail of\nhis mind. What\nthen? A jester at\nthe court of his\nmaster, indulged\nand disesteemed,\nwinning a clement\nmaster s praise.\nWhy had they\nchosen all that\npart? Not wholly\nfor the smooth\ncaress. For them\ntoo history was a",  // Page 194
    "tale like any\nother too often\nheard, their land\na pawnshop.\n\nHad Pyrrhus not\nfallen by a beldam\ns hand in Argos or\nJulius Caesar not\nbeen knifed to\ndeath. They are\nnot to be thought\naway. Time has\nbranded them and\nfettered they are\nlodged in the room",  // Page 195
    "of the infinite\npossibilities they\nhave ousted. But\ncan those have\nbeen possible\nseeing that they\nnever were? Or was\nthat only possible\nwhich came to\npass? Weave,\nweaver of the\nwind.\n\n--Tell us a story,\nsir.\n--O, do, sir. A",  // Page 196
    "ghoststory.\n\n--Where do you\nbegin in this?\nStephen asked,\nopening another\nbook.\n\n--_Weep no more,_\nComyn said.\n\n--Go on then,\nTalbot.\n\n--And the story,\nsir?",  // Page 197
    "--After, Stephen\nsaid. Go on,\nTalbot.\n\nA swarthy boy\nopened a book and\npropped it nimbly\nunder the\nbreastwork of his\nsatchel. He\nrecited jerks of\nverse with odd\nglances at the\ntext:\n\n_--Weep no more,",  // Page 198
    "woful shepherds,\nweep no more For\nLycidas, your\nsorrow, is not\ndead, Sunk though\nhe be beneath the\nwatery floor..._\n\nIt must be a\nmovement then, an\nactuality of the\npossible as\npossible.\nAristotle s phrase\nformed itself\nwithin the gabbled",  // Page 199
    "verses and floated\nout into the\nstudious silence\nof the library of\nSaint Genevieve\nwhere he had read,\nsheltered from the\nsin of Paris,\nnight by night. By\nhis elbow a\ndelicate Siamese\nconned a handbook\nof strategy. Fed\nand feeding brains\nabout me: under\nglowlamps,",  // Page 200
    "impaled, with\nfaintly beating\nfeelers: and in my\nmind s darkness a\nsloth of the\nunderworld,\nreluctant, shy of\nbrightness,\nshifting her\ndragon scaly\nfolds. Thought is\nthe thought of\nthought. Tranquil\nbrightness. The\nsoul is in a\nmanner all that",  // Page 201
    "is: the soul is\nthe form of forms.\nTranquility\nsudden, vast,\ncandescent: form\nof forms.\n\nTalbot repeated:\n\n_--Through the\ndear might of Him\nthat walked the\nwaves,\n\nThrough the dear\nmight..._",  // Page 202
    "--Turn over,\nStephen said\nquietly. I don t\nsee anything.\n\n--What, sir?\nTalbot asked\nsimply, bending\nforward.\n\nHis hand turned\nthe page over. He\nleaned back and\nwent on again,\nhaving just\nremembered. Of him",  // Page 203
    "that walked the\nwaves. Here also\nover these craven\nhearts his shadow\nlies and on the\nscoffer s heart\nand lips and on\nmine. It lies upon\ntheir eager faces\nwho offered him a\ncoin of the\ntribute. To Caesar\nwhat is Caesar s,\nto God what is God\ns. A long look\nfrom dark eyes, a",  // Page 204
    "riddling sentence\nto be woven and\nwoven on the\nchurch s looms.\nAy.\n\nRiddle me, riddle\nme, randy ro.  My\nfather gave me\nseeds to sow.\n\nTalbot slid his\nclosed book into\nhis satchel.\n\n--Have I heard",  // Page 205
    "all? Stephen\nasked.\n\n--Yes, sir. Hockey\nat ten, sir.\n\n--Half day, sir.\nThursday.\n\n--Who can answer a\nriddle? Stephen\nasked.\n\nThey bundled their\nbooks away,\npencils clacking,",  // Page 206
    "pages rustling.\nCrowding together\nthey strapped and\nbuckled their\nsatchels, all\ngabbling gaily:\n\n--A riddle, sir?\nAsk me, sir.\n\n--O, ask me, sir.\n\n--A hard one, sir.\n\n--This is the\nriddle, Stephen",  // Page 207
    "said:\n\nThe cock crew,\nThe sky was blue:\nThe bells in\nheaven  Were\nstriking eleven.\nTis time for this\npoor soul  To go\nto heaven.\n\nWhat is that?\n\n--What, sir?\n\n--Again, sir. We",  // Page 208
    "didn t hear.\n\nTheir eyes grew\nbigger as the\nlines were\nrepeated. After a\nsilence Cochrane\nsaid:\n\n--What is it, sir?\nWe give it up.\n\nStephen, his\nthroat itching,\nanswered:\n--The fox burying",  // Page 209
    "his grandmother\nunder a hollybush.\n\nHe stood up and\ngave a shout of\nnervous laughter\nto which their\ncries echoed\ndismay.\n\nA stick struck the\ndoor and a voice\nin the corridor\ncalled:\n\n--Hockey!",  // Page 210
    "They broke\nasunder, sidling\nout of their\nbenches, leaping\nthem. Quickly they\nwere gone and from\nthe lumberroom\ncame the rattle of\nsticks and clamour\nof their boots and\ntongues.\n\nSargent who alone\nhad lingered came\nforward slowly,\nshowing an open",  // Page 211
    "copybook. His\ntangled hair and\nscraggy neck gave\nwitness of\nunreadiness and\nthrough his misty\nglasses weak eyes\nlooked up\npleading. On his\ncheek, dull and\nbloodless, a soft\nstain of ink lay,\ndateshaped, recent\nand damp as a\nsnail s bed.\nHe held out his",  // Page 212
    "copybook. The word\n_Sums_ was written\non the headline.\nBeneath were\nsloping figures\nand at the foot a\ncrooked signature\nwith blind loops\nand a blot. Cyril\nSargent: his name\nand seal.\n\n--Mr Deasy told me\nto write them out\nall again, he\nsaid, and show",  // Page 213
    "them to you, sir.\n\nStephen touched\nthe edges of the\nbook. Futility.\n\n--Do you\nunderstand how to\ndo them now? he\nasked.\n\n--Numbers eleven\nto fifteen,\nSargent answered.\nMr Deasy said I\nwas to copy them",  // Page 214
    "off the board,\nsir.\n\n--Can you do them\nyourself? Stephen\nasked.\n\n--No, sir.\n\nUgly and futile:\nlean neck and\ntangled hair and a\nstain of ink, a\nsnail s bed. Yet\nsomeone had loved\nhim, borne him in",  // Page 215
    "her arms and in\nher heart. But for\nher the race of\nthe world would\nhave trampled him\nunderfoot, a\nsquashed boneless\nsnail. She had\nloved his weak\nwatery blood\ndrained from her\nown. Was that then\nreal? The only\ntrue thing in\nlife? His mother s\nprostrate body the",  // Page 216
    "fiery Columbanus\nin holy zeal\nbestrode. She was\nno more: the\ntrembling skeleton\nof a twig burnt in\nthe fire, an odour\nof rosewood and\nwetted ashes. She\nhad saved him from\nbeing trampled\nunderfoot and had\ngone, scarcely\nhaving been. A\npoor soul gone to\nheaven: and on a",  // Page 217
    "heath beneath\nwinking stars a\nfox, red reek of\nrapine in his fur,\nwith merciless\nbright eyes\nscraped in the\nearth, listened,\nscraped up the\nearth, listened,\nscraped and\nscraped.\n\nSitting at his\nside Stephen\nsolved out the",  // Page 218
    "problem. He proves\nby algebra that\nShakespeare s\nghost is Hamlet s\ngrandfather.\nSargent peered\naskance through\nhis slanted\nglasses.\nHockeysticks\nrattled in the\nlumberroom: the\nhollow knock of a\nball and calls\nfrom the field.\nAcross the page",  // Page 219
    "the symbols moved\nin grave morrice,\nin the mummery of\ntheir letters,\nwearing quaint\ncaps of squares\nand cubes. Give\nhands, traverse,\nbow to partner:\nso: imps of fancy\nof the Moors. Gone\ntoo from the\nworld, Averroes\nand Moses\nMaimonides, dark\nmen in mien and",  // Page 220
    "movement, flashing\nin their mocking\nmirrors the\nobscure soul of\nthe world, a\ndarkness shining\nin brightness\nwhich brightness\ncould not\ncomprehend.\n\n--Do you\nunderstand now?\nCan you work the\nsecond for\nyourself?",  // Page 221
    "--Yes, sir.\n\nIn long shaky\nstrokes Sargent\ncopied the data.\nWaiting always for\na word of help his\nhand moved\nfaithfully the\nunsteady symbols,\na faint hue of\nshame flickering\nbehind his dull\nskin. _Amor\nmatris:_\nsubjective and",  // Page 222
    "objective\ngenitive. With her\nweak blood and\nwheysour milk she\nhad fed him and\nhid from sight of\nothers his\nswaddling bands.\n\nLike him was I,\nthese sloping\nshoulders, this\ngracelessness. My\nchildhood bends\nbeside me. Too far\nfor me to lay a",  // Page 223
    "hand there once or\nlightly. Mine is\nfar and his secret\nas our eyes.\nSecrets, silent,\nstony sit in the\ndark palaces of\nboth our hearts:\nsecrets weary of\ntheir tyranny:\ntyrants, willing\nto be dethroned.\n\nThe sum was done.\n\n--It is very",  // Page 224
    "simple, Stephen\nsaid as he stood\nup.\n\n--Yes, sir.\nThanks, Sargent\nanswered.\n\nHe dried the page\nwith a sheet of\nthin blottingpaper\nand carried his\ncopybook back to\nhis bench.\n\n--You had better",  // Page 225
    "get your stick and\ngo out to the\nothers, Stephen\nsaid as he\nfollowed towards\nthe door the boy s\ngraceless form.\n\n--Yes, sir.\n\nIn the corridor\nhis name was\nheard, called from\nthe playfield.\n\n--Sargent!",  // Page 226
    "--Run on, Stephen\nsaid. Mr Deasy is\ncalling you.\n\nHe stood in the\nporch and watched\nthe laggard hurry\ntowards the\nscrappy field\nwhere sharp voices\nwere in strife.\nThey were sorted\nin teams and Mr\nDeasy came away\nstepping over\nwisps of grass",  // Page 227
    "with gaitered\nfeet. When he had\nreached the\nschoolhouse voices\nagain contending\ncalled to him. He\nturned his angry\nwhite moustache.\n\n--What is it now?\nhe cried\ncontinually\nwithout listening.\n\n--Cochrane and\nHalliday are on",  // Page 228
    "the same side,\nsir, Stephen said.\n\n--Will you wait in\nmy study for a\nmoment, Mr Deasy\nsaid, till I\nrestore order\nhere.\n\nAnd as he stepped\nfussily back\nacross the field\nhis old man s\nvoice cried\nsternly:",  // Page 229
    "--What is the\nmatter? What is it\nnow?\n\nTheir sharp voices\ncried about him on\nall sides: their\nmany forms closed\nround him, the\ngarish sunshine\nbleaching the\nhoney of his\nilldyed head.\n\nStale smoky air\nhung in the study",  // Page 230
    "with the smell of\ndrab abraded\nleather of its\nchairs. As on the\nfirst day he\nbargained with me\nhere. As it was in\nthe beginning, is\nnow. On the\nsideboard the tray\nof Stuart coins,\nbase treasure of a\nbog: and ever\nshall be. And snug\nin their spooncase\nof purple plush,",  // Page 231
    "faded, the twelve\napostles having\npreached to all\nthe gentiles:\nworld without end.\n\nA hasty step over\nthe stone porch\nand in the\ncorridor. Blowing\nout his rare\nmoustache Mr Deasy\nhalted at the\ntable.\n\n--First, our",  // Page 232
    "little financial\nsettlement, he\nsaid.\n\nHe brought out of\nhis coat a\npocketbook bound\nby a leather\nthong. It slapped\nopen and he took\nfrom it two notes,\none of joined\nhalves, and laid\nthem carefully on\nthe table.\n--Two, he said,",  // Page 233
    "strapping and\nstowing his\npocketbook away.\n\nAnd now his\nstrongroom for the\ngold. Stephen s\nembarrassed hand\nmoved over the\nshells heaped in\nthe cold stone\nmortar: whelks and\nmoney cowries and\nleopard shells:\nand this, whorled\nas an emir s",  // Page 234
    "turban, and this,\nthe scallop of\nsaint James. An\nold pilgrim s\nhoard, dead\ntreasure, hollow\nshells.\n\nA sovereign fell,\nbright and new, on\nthe soft pile of\nthe tablecloth.\n\n--Three, Mr Deasy\nsaid, turning his\nlittle savingsbox",  // Page 235
    "about in his hand.\nThese are handy\nthings to have.\nSee. This is for\nsovereigns. This\nis for shillings.\nSixpences,\nhalfcrowns. And\nhere crowns. See.\n\nHe shot from it\ntwo crowns and two\nshillings.\n\n--Three twelve, he\nsaid. I think you",  // Page 236
    "ll find that s\nright.\n\n--Thank you, sir,\nStephen said,\ngathering the\nmoney together\nwith shy haste and\nputting it all in\na pocket of his\ntrousers.\n\n--No thanks at\nall, Mr Deasy\nsaid. You have\nearned it.",  // Page 237
    "Stephen s hand,\nfree again, went\nback to the hollow\nshells. Symbols\ntoo of beauty and\nof power. A lump\nin my pocket:\nsymbols soiled by\ngreed and misery.\n\n--Don t carry it\nlike that, Mr\nDeasy said. You ll\npull it out\nsomewhere and lose\nit. You just buy",  // Page 238
    "one of these\nmachines. You ll\nfind them very\nhandy.\n\nAnswer something.\n\n--Mine would be\noften empty,\nStephen said.\n\nThe same room and\nhour, the same\nwisdom: and I the\nsame. Three times\nnow. Three nooses",  // Page 239
    "round me here.\nWell? I can break\nthem in this\ninstant if I will.\n\n--Because you don\nt save, Mr Deasy\nsaid, pointing his\nfinger. You don t\nknow yet what\nmoney is. Money is\npower. When you\nhave lived as long\nas I have. I know,\nI know. If youth\nbut knew. But what",  // Page 240
    "does Shakespeare\nsay? _Put but\nmoney in thy\npurse._\n\n--Iago, Stephen\nmurmured.\n\nHe lifted his gaze\nfrom the idle\nshells to the old\nman s stare.\n\n--He knew what\nmoney was, Mr\nDeasy said. He",  // Page 241
    "made money. A\npoet, yes, but an\nEnglishman too. Do\nyou know what is\nthe pride of the\nEnglish? Do you\nknow what is the\nproudest word you\nwill ever hear\nfrom an Englishman\ns mouth?\n\nThe seas ruler.\nHis seacold eyes\nlooked on the\nempty bay: it",  // Page 242
    "seems history is\nto blame: on me\nand on my words,\nunhating.\n\n--That on his\nempire, Stephen\nsaid, the sun\nnever sets.\n\n--Ba! Mr Deasy\ncried. That s not\nEnglish. A French\nCelt said that. He\ntapped his\nsavingsbox against",  // Page 243
    "his thumbnail.\n\n--I will tell you,\nhe said solemnly,\nwhat is his\nproudest boast. _I\npaid my way._\n\nGood man, good\nman.\n\n_--I paid my way.\nI never borrowed a\nshilling in my\nlife._ Can you\nfeel that? _I owe",  // Page 244
    "nothing._ Can you?\n\nMulligan, nine\npounds, three\npairs of socks,\none pair brogues,\nties. Curran, ten\nguineas. McCann,\none guinea. Fred\nRyan, two\nshillings. Temple,\ntwo lunches.\nRussell, one\nguinea, Cousins,\nten shillings, Bob\nReynolds, half a",  // Page 245
    "guinea, Koehler,\nthree guineas, Mrs\nMacKernan, five\nweeks board. The\nlump I have is\nuseless.\n\n--For the moment,\nno, Stephen\nanswered.\n\nMr Deasy laughed\nwith rich delight,\nputting back his\nsavingsbox.\n--I knew you",  // Page 246
    "couldn t, he said\njoyously. But one\nday you must feel\nit. We are a\ngenerous people\nbut we must also\nbe just.\n\n--I fear those big\nwords, Stephen\nsaid, which make\nus so unhappy.\n\nMr Deasy stared\nsternly for some\nmoments over the",  // Page 247
    "mantelpiece at the\nshapely bulk of a\nman in tartan\nfillibegs: Albert\nEdward, prince of\nWales.\n\n--You think me an\nold fogey and an\nold tory, his\nthoughtful voice\nsaid. I saw three\ngenerations since\nO Connell s time.\nI remember the\nfamine in 46. Do",  // Page 248
    "you know that the\norange lodges\nagitated for\nrepeal of the\nunion twenty years\nbefore O Connell\ndid or before the\nprelates of your\ncommunion\ndenounced him as a\ndemagogue? You\nfenians forget\nsome things.\n\nGlorious, pious\nand immortal",  // Page 249
    "memory. The lodge\nof Diamond in\nArmagh the\nsplendid behung\nwith corpses of\npapishes. Hoarse,\nmasked and armed,\nthe planters\ncovenant. The\nblack north and\ntrue blue bible.\nCroppies lie down.\n\nStephen sketched a\nbrief gesture.\n--I have rebel",  // Page 250
    "blood in me too,\nMr Deasy said. On\nthe spindle side.\nBut I am descended\nfrom sir John\nBlackwood who\nvoted for the\nunion. We are all\nIrish, all kings\nsons.\n\n--Alas, Stephen\nsaid.\n\n--_Per vias\nrectas_, Mr Deasy",  // Page 251
    "said firmly, was\nhis motto. He\nvoted for it and\nput on his\ntopboots to ride\nto Dublin from the\nArds of Down to do\nso.\n\nLal the ral the ra\nThe rocky road to\nDublin.\n\nA gruff squire on\nhorseback with\nshiny topboots.",  // Page 252
    "Soft day, sir\nJohn! Soft day,\nyour honour!...\nDay!... Day!...\nTwo topboots jog\ndangling on to\nDublin. Lal the\nral the ra. Lal\nthe ral the raddy.\n\n--That reminds me,\nMr Deasy said. You\ncan do me a\nfavour, Mr\nDedalus, with some\nof your literary",  // Page 253
    "friends. I have a\nletter here for\nthe press. Sit\ndown a moment. I\nhave just to copy\nthe end.\n\nHe went to the\ndesk near the\nwindow, pulled in\nhis chair twice\nand read off some\nwords from the\nsheet on the drum\nof his typewriter.\n--Sit down. Excuse",  // Page 254
    "me, he said over\nhis shoulder, _the\ndictates of common\nsense._ Just a\nmoment.\n\nHe peered from\nunder his shaggy\nbrows at the\nmanuscript by his\nelbow and,\nmuttering, began\nto prod the stiff\nbuttons of the\nkeyboard slowly,\nsometimes blowing",  // Page 255
    "as he screwed up\nthe drum to erase\nan error.\n\nStephen seated\nhimself\nnoiselessly before\nthe princely\npresence. Framed\naround the walls\nimages of vanished\nhorses stood in\nhomage, their meek\nheads poised in\nair: lord Hastings\n_Repulse_, the",  // Page 256
    "duke of\nWestminster s\n_Shotover_, the\nduke of Beaufort s\n_Ceylon_, _prix de\nParis_, 1866.\nElfin riders sat\nthem, watchful of\na sign. He saw\ntheir speeds,\nbacking king s\ncolours, and\nshouted with the\nshouts of vanished\ncrowds.\n--Full stop, Mr",  // Page 257
    "Deasy bade his\nkeys. _But prompt\nventilation of\nthis allimportant\nquestion..._\n\nWhere Cranly led\nme to get rich\nquick, hunting his\nwinners among the\nmudsplashed\nbrakes, amid the\nbawls of bookies\non their pitches\nand reek of the\ncanteen, over the",  // Page 258
    "motley slush. Even\nmoney _Fair\nRebel._ Ten to one\nthe field. Dicers\nand thimbleriggers\nwe hurried by\nafter the hoofs,\nthe vying caps and\njackets and past\nthe meatfaced\nwoman, a butcher s\ndame, nuzzling\nthirstily her\nclove of orange.\n\nShouts rang shrill",  // Page 259
    "from the boys\nplayfield and a\nwhirring whistle.\n\nAgain: a goal. I\nam among them,\namong their\nbattling bodies in\na medley, the\njoust of life. You\nmean that\nknockkneed mother\ns darling who\nseems to be\nslightly crawsick?\nJousts. Time",  // Page 260
    "shocked rebounds,\nshock by shock.\nJousts, slush and\nuproar of battles,\nthe frozen\ndeathspew of the\nslain, a shout of\nspearspikes baited\nwith men s\nbloodied guts.\n\n--Now then, Mr\nDeasy said,\nrising.\n\nHe came to the",  // Page 261
    "table, pinning\ntogether his\nsheets. Stephen\nstood up.\n\n--I have put the\nmatter into a\nnutshell, Mr Deasy\nsaid. It s about\nthe foot and mouth\ndisease. Just look\nthrough it. There\ncan be no two\nopinions on the\nmatter.\nMay I trespass on",  // Page 262
    "your valuable\nspace. That\ndoctrine of\n_laissez faire_\nwhich so often in\nour history. Our\ncattle trade. The\nway of all our old\nindustries.\nLiverpool ring\nwhich jockeyed the\nGalway harbour\nscheme. European\nconflagration.\nGrain supplies\nthrough the narrow",  // Page 263
    "waters of the\nchannel. The\npluterperfect\nimperturbability\nof the department\nof agriculture.\nPardoned a\nclassical\nallusion.\nCassandra. By a\nwoman who was no\nbetter than she\nshould be. To come\nto the point at\nissue.\n--I don t mince",  // Page 264
    "words, do I? Mr\nDeasy asked as\nStephen read on.\n\nFoot and mouth\ndisease. Known as\nKoch s\npreparation. Serum\nand virus.\nPercentage of\nsalted horses.\nRinderpest.\nEmperor s horses\nat M rzsteg, lower\nAustria.\nVeterinary",  // Page 265
    "surgeons. Mr Henry\nBlackwood Price.\nCourteous offer a\nfair trial.\nDictates of common\nsense.\nAllimportant\nquestion. In every\nsense of the word\ntake the bull by\nthe horns.\nThanking you for\nthe hospitality of\nyour columns.\n\n--I want that to",  // Page 266
    "be printed and\nread, Mr Deasy\nsaid. You will see\nat the next\noutbreak they will\nput an embargo on\nIrish cattle. And\nit can be cured.\nIt is cured. My\ncousin, Blackwood\nPrice, writes to\nme it is regularly\ntreated and cured\nin Austria by\ncattledoctors\nthere. They offer",  // Page 267
    "to come over here.\nI am trying to\nwork up influence\nwith the\ndepartment. Now I\nm going to try\npublicity. I am\nsurrounded by\ndifficulties,\nby... intrigues\nby... backstairs\ninfluence by...\n\nHe raised his\nforefinger and\nbeat the air oldly",  // Page 268
    "before his voice\nspoke.\n\n--Mark my words,\nMr Dedalus, he\nsaid. England is\nin the hands of\nthe jews. In all\nthe highest\nplaces: her\nfinance, her\npress. And they\nare the signs of a\nnation s decay.\nWherever they\ngather they eat up",  // Page 269
    "the nation s vital\nstrength. I have\nseen it coming\nthese years. As\nsure as we are\nstanding here the\njew merchants are\nalready at their\nwork of\ndestruction. Old\nEngland is dying.\n\nHe stepped swiftly\noff, his eyes\ncoming to blue\nlife as they",  // Page 270
    "passed a broad\nsunbeam. He faced\nabout and back\nagain.\n\n--Dying, he said\nagain, if not dead\nby now.\n\nThe harlot s cry\nfrom street to\nstreet  Shall\nweave old England\ns windingsheet.\n\nHis eyes open wide",  // Page 271
    "in vision stared\nsternly across the\nsunbeam in which\nhe halted.\n\n--A merchant,\nStephen said, is\none who buys cheap\nand sells dear,\njew or gentile, is\nhe not?\n\n--They sinned\nagainst the light,\nMr Deasy said\ngravely. And you",  // Page 272
    "can see the\ndarkness in their\neyes. And that is\nwhy they are\nwanderers on the\nearth to this day.\n\nOn the steps of\nthe Paris stock\nexchange the\ngoldskinned men\nquoting prices on\ntheir gemmed\nfingers. Gabble of\ngeese. They\nswarmed loud,",  // Page 273
    "uncouth about the\ntemple, their\nheads\nthickplotting\nunder maladroit\nsilk hats. Not\ntheirs: these\nclothes, this\nspeech, these\ngestures. Their\nfull slow eyes\nbelied the words,\nthe gestures eager\nand unoffending,\nbut knew the\nrancours massed",  // Page 274
    "about them and\nknew their zeal\nwas vain. Vain\npatience to heap\nand hoard. Time\nsurely would\nscatter all. A\nhoard heaped by\nthe roadside:\nplundered and\npassing on. Their\neyes knew their\nyears of wandering\nand, patient, knew\nthe dishonours of\ntheir flesh.",  // Page 275
    "--Who has not?\nStephen said.\n\n--What do you\nmean? Mr Deasy\nasked.\n\nHe came forward a\npace and stood by\nthe table. His\nunderjaw fell\nsideways open\nuncertainly. Is\nthis old wisdom?\nHe waits to hear\nfrom me.",  // Page 276
    "--History, Stephen\nsaid, is a\nnightmare from\nwhich I am trying\nto awake.\n\nFrom the playfield\nthe boys raised a\nshout. A whirring\nwhistle: goal.\nWhat if that\nnightmare gave you\na back kick?\n\n--The ways of the\nCreator are not",  // Page 277
    "our ways, Mr Deasy\nsaid. All human\nhistory moves\ntowards one great\ngoal, the\nmanifestation of\nGod.\n\nStephen jerked his\nthumb towards the\nwindow, saying:\n\n--That is God.\n\nHooray! Ay!\nWhrrwhee!",  // Page 278
    "--What? Mr Deasy\nasked.\n\n--A shout in the\nstreet, Stephen\nanswered,\nshrugging his\nshoulders.\n\nMr Deasy looked\ndown and held for\nawhile the wings\nof his nose\ntweaked between\nhis fingers.\nLooking up again",  // Page 279
    "he set them free.\n\n--I am happier\nthan you are, he\nsaid. We have\ncommitted many\nerrors and many\nsins. A woman\nbrought sin into\nthe world. For a\nwoman who was no\nbetter than she\nshould be, Helen,\nthe runaway wife\nof Menelaus, ten\nyears the Greeks",  // Page 280
    "made war on Troy.\nA faithless wife\nfirst brought the\nstrangers to our\nshore here,\nMacMurrough s wife\nand her leman, O\nRourke, prince of\nBreffni. A woman\ntoo brought\nParnell low. Many\nerrors, many\nfailures but not\nthe one sin. I am\na struggler now at\nthe end of my",  // Page 281
    "days. But I will\nfight for the\nright till the\nend.\n\nFor Ulster will\nfight  And Ulster\nwill be right.\n\nStephen raised the\nsheets in his\nhand.\n\n--Well, sir, he\nbegan.\n--I foresee, Mr",  // Page 282
    "Deasy said, that\nyou will not\nremain here very\nlong at this work.\nYou were not born\nto be a teacher, I\nthink. Perhaps I\nam wrong.\n\n--A learner\nrather, Stephen\nsaid.\n\nAnd here what will\nyou learn more?\nMr Deasy shook his",  // Page 283
    "head.\n\n--Who knows? he\nsaid. To learn one\nmust be humble.\nBut life is the\ngreat teacher.\n\nStephen rustled\nthe sheets again.\n\n--As regards\nthese, he began.\n\n--Yes, Mr Deasy\nsaid. You have two",  // Page 284
    "copies there. If\nyou can have them\npublished at once.\n\n_ Telegraph. Irish\nHomestead._\n\n--I will try,\nStephen said, and\nlet you know\ntomorrow. I know\ntwo editors\nslightly.\n\n--That will do, Mr\nDeasy said",  // Page 285
    "briskly. I wrote\nlast night to Mr\nField, M.P. There\nis a meeting of\nthe cattletraders\nassociation today\nat the City Arms\nhotel. I asked him\nto lay my letter\nbefore the\nmeeting. You see\nif you can get it\ninto your two\npapers. What are\nthey?\n_--The Evening",  // Page 286
    "Telegraph..._\n\n--That will do, Mr\nDeasy said. There\nis no time to\nlose. Now I have\nto answer that\nletter from my\ncousin.\n\n--Good morning,\nsir, Stephen said,\nputting the sheets\nin his pocket.\nThank you.\n--Not at all, Mr",  // Page 287
    "Deasy said as he\nsearched the\npapers on his\ndesk. I like to\nbreak a lance with\nyou, old as I am.\n\n--Good morning,\nsir, Stephen said\nagain, bowing to\nhis bent back.\n\nHe went out by the\nopen porch and\ndown the gravel\npath under the",  // Page 288
    "trees, hearing the\ncries of voices\nand crack of\nsticks from the\nplayfield. The\nlions couchant on\nthe pillars as he\npassed out through\nthe gate:\ntoothless terrors.\nStill I will help\nhim in his fight.\nMulligan will dub\nme a new name: the\nbullockbefriending\nbard.",  // Page 289
    "--Mr Dedalus!\n\nRunning after me.\nNo more letters, I\nhope.\n\n--Just one moment.\n\n--Yes, sir,\nStephen said,\nturning back at\nthe gate.\n\nMr Deasy halted,\nbreathing hard and\nswallowing his",  // Page 290
    "breath.\n\n--I just wanted to\nsay, he said.\nIreland, they say,\nhas the honour of\nbeing the only\ncountry which\nnever persecuted\nthe jews. Do you\nknow that? No. And\ndo you know why?\n\nHe frowned sternly\non the bright air.\n--Why, sir?",  // Page 291
    "Stephen asked,\nbeginning to\nsmile.\n\n--Because she\nnever let them in,\nMr Deasy said\nsolemnly.\n\nA coughball of\nlaughter leaped\nfrom his throat\ndragging after it\na rattling chain\nof phlegm. He\nturned back",  // Page 292
    "quickly, coughing,\nlaughing, his\nlifted arms waving\nto the air.\n\n--She never let\nthem in, he cried\nagain through his\nlaughter as he\nstamped on\ngaitered feet over\nthe gravel of the\npath. That s why.\n\nOn his wise\nshoulders through",  // Page 293
    "the checkerwork of\nleaves the sun\nflung spangles,\ndancing coins.\n\n[ 3 ]\n\nIneluctable\nmodality of the\nvisible: at least\nthat if no more,\nthought through my\neyes. Signatures\nof all things I am\nhere to read,\nseaspawn and",  // Page 294
    "seawrack, the\nnearing tide, that\nrusty boot.\nSnotgreen,\nbluesilver, rust:\ncoloured signs.\nLimits of the\ndiaphane. But he\nadds: in bodies.\nThen he was aware\nof them bodies\nbefore of them\ncoloured. How? By\nknocking his\nsconce against\nthem, sure. Go",  // Page 295
    "easy. Bald he was\nand a millionaire,\n_maestro di color\nche sanno_. Limit\nof the diaphane\nin. Why in?\nDiaphane,\nadiaphane. If you\ncan put your five\nfingers through it\nit is a gate, if\nnot a door. Shut\nyour eyes and see.\n\nStephen closed his\neyes to hear his",  // Page 296
    "boots crush\ncrackling wrack\nand shells. You\nare walking\nthrough it\nhowsomever. I am,\na stride at a\ntime. A very short\nspace of time\nthrough very short\ntimes of space.\nFive, six: the\n_nacheinander_.\nExactly: and that\nis the ineluctable\nmodality of the",  // Page 297
    "audible. Open your\neyes. No. Jesus!\nIf I fell over a\ncliff that beetles\no er his base,\nfell through the\n_nebeneinander_\nineluctably! I am\ngetting on nicely\nin the dark. My\nash sword hangs at\nmy side. Tap with\nit: they do. My\ntwo feet in his\nboots are at the\nends of his legs,",  // Page 298
    "_nebeneinander_.\nSounds solid: made\nby the mallet of\n_Los Demiurgos_.\nAm I walking into\neternity along\nSandymount strand?\nCrush, crack,\ncrick, crick. Wild\nsea money. Dominie\nDeasy kens them a\n.\n\nWon t you come to\nSandymount,\nMadeline the mare?",  // Page 299
    "Rhythm begins, you\nsee. I hear. A\ncatalectic\ntetrameter of\niambs marching.\nNo, agallop:\n_deline the mare_.\n\nOpen your eyes\nnow. I will. One\nmoment. Has all\nvanished since? If\nI open and am for\never in the black\nadiaphane.\n_Basta!_ I will"  // Page 300
};

#endif // BOOK_DATA_H
