// Auto-generated Ulysses book data
// James Joyce - Project Gutenberg

#ifndef BOOK_DATA_H
#define BOOK_DATA_H

#define TOTAL_PAGES 50

const char* const book_pages[] = {
    "[Illustration]\nUlysses by James\nJoyce Contents - I -\n[ 1 ] [ 2 ] [ 3 ] -\nII - [ 4 ] [ 5 ] [ 6\n] [ 7 ] [ 8 ] [ 9 ]\n[ 10 ] [ 11 ] [ 12 ]\n[ 13 ] [ 14 ] [ 15 ]\n- III - [ 16 ] [ 17\n] [ 18 ] - I - [ 1 ]\nStately, plump Buck\nMulligan came from\nthe stairhead,\nbearing a bowl of\nlather on which a\nmirror and a razor\nlay crossed. A",  // Page 1
    "yellow dressinggown,\nungirdled, was\nsustained gently\nbehind him on the\nmild morning air. He\nheld the bowl aloft\nand intoned:\n-_Introibo ad altare\nDei_. Halted, he\npeered down the dark\nwinding stairs and\ncalled out coarsely:\n-Come up, Kinch!\nCome up, you fearful\njesuit! Solemnly he\ncame forward and\nmounted the round",  // Page 2
    "gunrest. He faced\nabout and blessed\ngravely thrice the\ntower, the\nsurrounding land and\nthe awaking\nmountains. Then,\ncatching sight of\nStephen Dedalus, he\nbent towards him and\nmade rapid crosses\nin the air, gurgling\nin his throat and\nshaking his head.\nStephen Dedalus,\ndispleased and\nsleepy, leaned his",  // Page 3
    "arms on the top of\nthe staircase and\nlooked coldly at the\nshaking gurgling\nface that blessed\nhim, equine in its\nlength, and at the\nlight untonsured\nhair, grained and\nhued like pale oak.\nBuck Mulligan peeped\nan instant under the\nmirror and then\ncovered the bowl\nsmartly. -Back to\nbarracks! he said\nsternly. He added in",  // Page 4
    "a preacher's tone:\n-For this, O dearly\nbeloved, is the\ngenuine Christine:\nbody and soul and\nblood and ouns. Slow\nmusic, please. Shut\nyour eyes, gents.\nOne moment. A little\ntrouble about those\nwhite corpuscles.\nSilence, all. He\npeered sideways up\nand gave a long slow\nwhistle of call,\nthen paused awhile\nin rapt attention,",  // Page 5
    "his even white teeth\nglistening here and\nthere with gold\npoints.\nChrysostomos. Two\nstrong shrill\nwhistles answered\nthrough the calm.\n-Thanks, old chap,\nhe cried briskly.\nThat will do nicely.\nSwitch off the\ncurrent, will you?\nHe skipped off the\ngunrest and looked\ngravely at his\nwatcher, gathering",  // Page 6
    "about his legs the\nloose folds of his\ngown. The plump\nshadowed face and\nsullen oval jowl\nrecalled a prelate,\npatron of arts in\nthe middle ages. A\npleasant smile broke\nquietly over his\nlips. -The mockery\nof it! he said\ngaily. Your absurd\nname, an ancient\nGreek! He pointed\nhis finger in\nfriendly jest and",  // Page 7
    "went over to the\nparapet, laughing to\nhimself. Stephen\nDedalus stepped up,\nfollowed him wearily\nhalfway and sat down\non the edge of the\ngunrest, watching\nhim still as he\npropped his mirror\non the parapet,\ndipped the brush in\nthe bowl and\nlathered cheeks and\nneck. Buck\nMulligan's gay voice\nwent on. -My name is",  // Page 8
    "absurd too: Malachi\nMulligan, two\ndactyls. But it has\na Hellenic ring,\nhasn't it? Tripping\nand sunny like the\nbuck himself. We\nmust go to Athens.\nWill you come if I\ncan get the aunt to\nfork out twenty\nquid? He laid the\nbrush aside and,\nlaughing with\ndelight, cried:\n-Will he come? The\njejune jesuit!",  // Page 9
    "Ceasing, he began to\nshave with care.\n-Tell me, Mulligan,\nStephen said\nquietly. -Yes, my\nlove? -How long is\nHaines going to stay\nin this tower? Buck\nMulligan showed a\nshaven cheek over\nhis right shoulder.\n-God, isn't he\ndreadful? he said\nfrankly. A ponderous\nSaxon. He thinks\nyou're not a\ngentleman. God,",  // Page 10
    "these bloody\nEnglish! Bursting\nwith money and\nindigestion. Because\nhe comes from\nOxford. You know,\nDedalus, you have\nthe real Oxford\nmanner. He can't\nmake you out. O, my\nname for you is the\nbest: Kinch, the\nknife-blade. He\nshaved warily over\nhis chin. -He was\nraving all night\nabout a black",  // Page 11
    "panther, Stephen\nsaid. Where is his\nguncase? -A woful\nlunatic! Mulligan\nsaid. Were you in a\nfunk? -I was,\nStephen said with\nenergy and growing\nfear. Out here in\nthe dark with a man\nI don't know raving\nand moaning to\nhimself about\nshooting a black\npanther. You saved\nmen from drowning.\nI'm not a hero,",  // Page 12
    "however. If he stays\non here I am off.\nBuck Mulligan\nfrowned at the\nlather on his\nrazorblade. He\nhopped down from his\nperch and began to\nsearch his trouser\npockets hastily.\n-Scutter! he cried\nthickly. He came\nover to the gunrest\nand, thrusting a\nhand into Stephen's\nupper pocket, said:\n-Lend us a loan of",  // Page 13
    "your noserag to wipe\nmy razor. Stephen\nsuffered him to pull\nout and hold up on\nshow by its corner a\ndirty crumpled\nhandkerchief. Buck\nMulligan wiped the\nrazorblade neatly.\nThen, gazing over\nthe handkerchief, he\nsaid: -The bard's\nnoserag! A new art\ncolour for our Irish\npoets: snotgreen.\nYou can almost taste\nit, can't you? He",  // Page 14
    "mounted to the\nparapet again and\ngazed out over\nDublin bay, his fair\noakpale hair\nstirring slightly.\n-God! he said\nquietly. Isn't the\nsea what Algy calls\nit: a great sweet\nmother? The\nsnotgreen sea. The\nscrotumtightening\nsea. _Epi oinopa\nponton_. Ah,\nDedalus, the Greeks!\nI must teach you.",  // Page 15
    "You must read them\nin the original.\n_Thalatta!\nThalatta!_ She is\nour great sweet\nmother. Come and\nlook. Stephen stood\nup and went over to\nthe parapet. Leaning\non it he looked down\non the water and on\nthe mailboat\nclearing the\nharbourmouth of\nKingstown. -Our\nmighty mother! Buck\nMulligan said. He",  // Page 16
    "turned abruptly his\ngrey searching eyes\nfrom the sea to\nStephen's face. -The\naunt thinks you\nkilled your mother,\nhe said. That's why\nshe won't let me\nhave anything to do\nwith you. -Someone\nkilled her, Stephen\nsaid gloomily. -You\ncould have knelt\ndown, damn it,\nKinch, when your\ndying mother asked\nyou, Buck Mulligan",  // Page 17
    "said. I'm\nhyperborean as much\nas you. But to think\nof your mother\nbegging you with her\nlast breath to kneel\ndown and pray for\nher. And you\nrefused. There is\nsomething sinister\nin you.... He broke\noff and lathered\nagain lightly his\nfarther cheek. A\ntolerant smile\ncurled his lips.\n-But a lovely",  // Page 18
    "mummer! he murmured\nto himself. Kinch,\nthe loveliest mummer\nof them all! He\nshaved evenly and\nwith care, in\nsilence, seriously.\nStephen, an elbow\nrested on the jagged\ngranite, leaned his\npalm against his\nbrow and gazed at\nthe fraying edge of\nhis shiny black\ncoat-sleeve. Pain,\nthat was not yet the\npain of love,",  // Page 19
    "fretted his heart.\nSilently, in a dream\nshe had come to him\nafter her death, her\nwasted body within\nits loose brown\ngraveclothes giving\noff an odour of wax\nand rosewood, her\nbreath, that had\nbent upon him, mute,\nreproachful, a faint\nodour of wetted\nashes. Across the\nthreadbare cuffedge\nhe saw the sea\nhailed as a great",  // Page 20
    "sweet mother by the\nwellfed voice beside\nhim. The ring of bay\nand skyline held a\ndull green mass of\nliquid. A bowl of\nwhite china had\nstood beside her\ndeathbed holding the\ngreen sluggish bile\nwhich she had torn\nup from her rotting\nliver by fits of\nloud groaning\nvomiting. Buck\nMulligan wiped again\nhis razorblade. -Ah,",  // Page 21
    "poor dogsbody! he\nsaid in a kind\nvoice. I must give\nyou a shirt and a\nfew noserags. How\nare the secondhand\nbreeks? -They fit\nwell enough, Stephen\nanswered. Buck\nMulligan attacked\nthe hollow beneath\nhis underlip. -The\nmockery of it, he\nsaid contentedly.\nSecondleg they\nshould be. God knows\nwhat poxy bowsy left",  // Page 22
    "them off. I have a\nlovely pair with a\nhair stripe, grey.\nYou'll look spiffing\nin them. I'm not\njoking, Kinch. You\nlook damn well when\nyou're dressed.\n-Thanks, Stephen\nsaid. I can't wear\nthem if they are\ngrey. -He can't wear\nthem, Buck Mulligan\ntold his face in the\nmirror. Etiquette is\netiquette. He kills\nhis mother but he",  // Page 23
    "can't wear grey\ntrousers. He folded\nhis razor neatly and\nwith stroking palps\nof fingers felt the\nsmooth skin. Stephen\nturned his gaze from\nthe sea and to the\nplump face with its\nsmokeblue mobile\neyes. -That fellow I\nwas with in the Ship\nlast night, said\nBuck Mulligan, says\nyou have g. p. i.\nHe's up in\nDottyville with",  // Page 24
    "Connolly Norman.\nGeneral paralysis of\nthe insane! He swept\nthe mirror a half\ncircle in the air to\nflash the tidings\nabroad in sunlight\nnow radiant on the\nsea. His curling\nshaven lips laughed\nand the edges of his\nwhite glittering\nteeth. Laughter\nseized all his\nstrong wellknit\ntrunk. -Look at\nyourself, he said,",  // Page 25
    "you dreadful bard!\nStephen bent forward\nand peered at the\nmirror held out to\nhim, cleft by a\ncrooked crack. Hair\non end. As he and\nothers see me. Who\nchose this face for\nme? This dogsbody to\nrid of vermin. It\nasks me too. -I\npinched it out of\nthe skivvy's room,\nBuck Mulligan said.\nIt does her all\nright. The aunt",  // Page 26
    "always keeps\nplainlooking\nservants for\nMalachi. Lead him\nnot into temptation.\nAnd her name is\nUrsula. Laughing\nagain, he brought\nthe mirror away from\nStephen's peering\neyes. -The rage of\nCaliban at not\nseeing his face in a\nmirror, he said. If\nWilde were only\nalive to see you!\nDrawing back and",  // Page 27
    "pointing, Stephen\nsaid with\nbitterness: -It is a\nsymbol of Irish art.\nThe cracked\nlookingglass of a\nservant. Buck\nMulligan suddenly\nlinked his arm in\nStephen's and walked\nwith him round the\ntower, his razor and\nmirror clacking in\nthe pocket where he\nhad thrust them.\n-It's not fair to\ntease you like that,",  // Page 28
    "Kinch, is it? he\nsaid kindly. God\nknows you have more\nspirit than any of\nthem. Parried again.\nHe fears the lancet\nof my art as I fear\nthat of his. The\ncold steel pen.\n-Cracked\nlookingglass of a\nservant! Tell that\nto the oxy chap\ndownstairs and touch\nhim for a guinea.\nHe's stinking with\nmoney and thinks",  // Page 29
    "you're not a\ngentleman. His old\nfellow made his tin\nby selling jalap to\nZulus or some bloody\nswindle or other.\nGod, Kinch, if you\nand I could only\nwork together we\nmight do something\nfor the island.\nHellenise it.\nCranly's arm. His\narm. -And to think\nof your having to\nbeg from these\nswine. I'm the only",  // Page 30
    "one that knows what\nyou are. Why don't\nyou trust me more?\nWhat have you up\nyour nose against\nme? Is it Haines? If\nhe makes any noise\nhere I'll bring down\nSeymour and we'll\ngive him a ragging\nworse than they gave\nClive Kempthorpe.\nYoung shouts of\nmoneyed voices in\nClive Kempthorpe's\nrooms. Palefaces:\nthey hold their ribs",  // Page 31
    "with laughter, one\nclasping another. O,\nI shall expire!\nBreak the news to\nher gently, Aubrey!\nI shall die! With\nslit ribbons of his\nshirt whipping the\nair he hops and\nhobbles round the\ntable, with trousers\ndown at heels,\nchased by Ades of\nMagdalen with the\ntailor's shears. A\nscared calf's face\ngilded with",  // Page 32
    "marmalade. I don't\nwant to be debagged!\nDon't you play the\ngiddy ox with me!\nShouts from the open\nwindow startling\nevening in the\nquadrangle. A deaf\ngardener, aproned,\nmasked with Matthew\nArnold's face,\npushes his mower on\nthe sombre lawn\nwatching narrowly\nthe dancing motes of\ngrasshalms. To\nourselves... new",  // Page 33
    "paganism...\nomphalos. -Let him\nstay, Stephen said.\nThere's nothing\nwrong with him\nexcept at night.\n-Then what is it?\nBuck Mulligan asked\nimpatiently. Cough\nit up. I'm quite\nfrank with you. What\nhave you against me\nnow? They halted,\nlooking towards the\nblunt cape of Bray\nHead that lay on the\nwater like the snout",  // Page 34
    "of a sleeping whale.\nStephen freed his\narm quietly. -Do you\nwish me to tell you?\nhe asked. -Yes, what\nis it? Buck Mulligan\nanswered. I don't\nremember anything.\nHe looked in\nStephen's face as he\nspoke. A light wind\npassed his brow,\nfanning softly his\nfair uncombed hair\nand stirring silver\npoints of anxiety in\nhis eyes. Stephen,",  // Page 35
    "depressed by his own\nvoice, said: -Do you\nremember the first\nday I went to your\nhouse after my\nmother's death? Buck\nMulligan frowned\nquickly and said:\n-What? Where? I\ncan't remember\nanything. I remember\nonly ideas and\nsensations. Why?\nWhat happened in the\nname of God? -You\nwere making tea,\nStephen said, and",  // Page 36
    "went across the\nlanding to get more\nhot water. Your\nmother and some\nvisitor came out of\nthe drawingroom. She\nasked you who was in\nyour room. -Yes?\nBuck Mulligan said.\nWhat did I say? I\nforget. -You said,\nStephen answered,\n_O, it's only\nDedalus whose mother\nis beastly dead._ A\nflush which made him\nseem younger and",  // Page 37
    "more engaging rose\nto Buck Mulligan's\ncheek. -Did I say\nthat? he asked.\nWell? What harm is\nthat? He shook his\nconstraint from him\nnervously. -And what\nis death, he asked,\nyour mother's or\nyours or my own? You\nsaw only your mother\ndie. I see them pop\noff every day in the\nMater and Richmond\nand cut up into\ntripes in the",  // Page 38
    "dissectingroom. It's\na beastly thing and\nnothing else. It\nsimply doesn't\nmatter. You wouldn't\nkneel down to pray\nfor your mother on\nher deathbed when\nshe asked you. Why?\nBecause you have the\ncursed jesuit strain\nin you, only it's\ninjected the wrong\nway. To me it's all\na mockery and\nbeastly. Her\ncerebral lobes are",  // Page 39
    "not functioning. She\ncalls the doctor sir\nPeter Teazle and\npicks buttercups off\nthe quilt. Humour\nher till it's over.\nYou crossed her last\nwish in death and\nyet you sulk with me\nbecause I don't\nwhinge like some\nhired mute from\nLalouette's. Absurd!\nI suppose I did say\nit. I didn't mean to\noffend the memory of\nyour mother. He had",  // Page 40
    "spoken himself into\nboldness. Stephen,\nshielding the gaping\nwounds which the\nwords had left in\nhis heart, said very\ncoldly: -I am not\nthinking of the\noffence to my\nmother. -Of what\nthen? Buck Mulligan\nasked. -Of the\noffence to me,\nStephen answered.\nBuck Mulligan swung\nround on his heel.\n-O, an impossible",  // Page 41
    "person! he\nexclaimed. He walked\noff quickly round\nthe parapet. Stephen\nstood at his post,\ngazing over the calm\nsea towards the\nheadland. Sea and\nheadland now grew\ndim. Pulses were\nbeating in his eyes,\nveiling their sight,\nand he felt the\nfever of his cheeks.\nA voice within the\ntower called loudly:\n-Are you up there,",  // Page 42
    "Mulligan? -I'm\ncoming, Buck\nMulligan answered.\nHe turned towards\nStephen and said:\n-Look at the sea.\nWhat does it care\nabout offences?\nChuck Loyola, Kinch,\nand come on down.\nThe Sassenach wants\nhis morning rashers.\nHis head halted\nagain for a moment\nat the top of the\nstaircase, level\nwith the roof:",  // Page 43
    "-Don't mope over it\nall day, he said.\nI'm inconsequent.\nGive up the moody\nbrooding. His head\nvanished but the\ndrone of his\ndescending voice\nboomed out of the\nstairhead: And no\nmore turn aside and\nbrood Upon love's\nbitter mystery For\nFergus rules the\nbrazen cars.\nWoodshadows floated\nsilently by through",  // Page 44
    "the morning peace\nfrom the stairhead\nseaward where he\ngazed. Inshore and\nfarther out the\nmirror of water\nwhitened, spurned by\nlightshod hurrying\nfeet. White breast\nof the dim sea. The\ntwining stresses,\ntwo by two. A hand\nplucking the\nharpstrings, merging\ntheir twining\nchords. Wavewhite\nwedded words",  // Page 45
    "shimmering on the\ndim tide. A cloud\nbegan to cover the\nsun slowly, wholly,\nshadowing the bay in\ndeeper green. It lay\nbeneath him, a bowl\nof bitter waters.\nFergus' song: I sang\nit alone in the\nhouse, holding down\nthe long dark\nchords. Her door was\nopen: she wanted to\nhear my music.\nSilent with awe and\npity I went to her",  // Page 46
    "bedside. She was\ncrying in her\nwretched bed. For\nthose words,\nStephen: love's\nbitter mystery.\nWhere now? Her\nsecrets: old\nfeatherfans,\ntasselled\ndancecards, powdered\nwith musk, a gaud of\namber beads in her\nlocked drawer. A\nbirdcage hung in the\nsunny window of her\nhouse when she was a",  // Page 47
    "girl. She heard old\nRoyce sing in the\npantomime of Turko\nthe Terrible and\nlaughed with others\nwhen he sang: I am\nthe boy That can\nenjoy Invisibility.\nPhantasmal mirth,\nfolded away:\nmuskperfumed. And no\nmore turn aside and\nbrood. Folded away\nin the memory of\nnature with her\ntoys. Memories beset\nhis brooding brain.",  // Page 48
    "Her glass of water\nfrom the kitchen tap\nwhen she had\napproached the\nsacrament. A cored\napple, filled with\nbrown sugar,\nroasting for her at\nthe hob on a dark\nautumn evening. Her\nshapely fingernails\nreddened by the\nblood of squashed\nlice from the\nchildren's shirts.\nIn a dream,\nsilently, she had",  // Page 49
    "come to him, her\nwasted body within\nits loose\ngraveclothes giving\noff an odour of wax\nand rosewood, her\nbreath, bent over\nhim with mute secret\nwords, a faint odour\nof wetted ashes. Her\nglazing eyes,\nstaring out of\ndeath, to shake and\nbend my soul. On me\nalone. The\nghostcandle to light\nher agony. Ghostly"  // Page 50
};

#endif // BOOK_DATA_H
