// Vendored AC Line proposal contract, verbatim from disks/line.mjs.
// Generated by bin/build-picture-tools.mjs. Seed helpers from lib/nopaint-proposals.mjs.
export const nopaintProposal = Object.freeze({
  version: 1,
  slug: "line",
  label: "Line",
  compatible: true,
  parameters: Object.freeze({
    color: Object.freeze({ type: "rgba", alpha: [24, 192] }),
    thickness: Object.freeze({ type: "integer", min: 1, max: 50 }),
    points: Object.freeze({ type: "path", min: 4, max: 18 }),
    durationFrames: Object.freeze({ type: "integer", min: 24, max: 120 }),
  }),
  generate({ random, width, height, base }) {
    const pointCount = 4 + Math.floor(random() * 15);
    const start = { x: base.x, y: base.y };
    const end = {
      x: Math.min(width - 1, base.x + base.w),
      y: Math.min(height - 1, base.y + base.h),
    };
    const points = Array.from({ length: pointCount }, (_, index) => {
      const t = pointCount === 1 ? 0 : index / (pointCount - 1);
      const sway = Math.sin(t * Math.PI * (1 + Math.floor(random() * 4))) * base.drift;
      return Object.freeze({
        x: Math.max(0, Math.min(width - 1,
          Math.round(start.x + (end.x - start.x) * t + sway))),
        y: Math.max(0, Math.min(height - 1,
          Math.round(start.y + (end.y - start.y) * t - sway * 0.65))),
      });
    });
    const shortSide = Math.min(width, height);
    const maxThickness = Math.max(1, Math.min(50, Math.floor(shortSide * 0.12)));
    const thickness = 1 + Math.floor(random() * maxThickness);
    // Keep the whole stroke visible, including rounded caps and a little
    // breathing room. Scale the path inward so it keeps its shape at edges.
    const inset = Math.min(Math.floor((shortSide - 1) / 2),
      Math.ceil(thickness / 2) + Math.max(2, Math.round(shortSide * 0.04)));
    const insetPoints = points.map(({ x, y }) => Object.freeze({
      x: Math.round(inset + x / Math.max(1, width - 1) * (width - 1 - inset * 2)),
      y: Math.round(inset + y / Math.max(1, height - 1) * (height - 1 - inset * 2)),
    }));
    const alpha = 24 + Math.floor(random() * 169);
    const color = Object.freeze([base.color[0], base.color[1], base.color[2], alpha]);
    const durationFrames = 24 + Math.floor(random() * 97);
    return Object.freeze({
      ...base,
      color,
      thickness,
      points: Object.freeze(insetPoints),
      brush: Object.freeze({
        slug: "line",
        params: Object.freeze(color.map(String)),
        colon: Object.freeze([String(thickness)]),
        parameters: Object.freeze({ thickness, alpha, pointCount, durationFrames }),
      }),
    });
  },
  render({ ink }, score, frame) {
    const duration = score.brush.parameters.durationFrames;
    const visible = Math.max(2, Math.ceil(score.points.length * Math.min(1, frame / duration)));
    for (let index = 1; index < visible; index += 1) {
      const from = score.points[index - 1];
      const to = score.points[index];
      ink(score.color).line(from.x, from.y, to.x, to.y, score.thickness);
    }
  },
});

export function seedFrom(value) {
  const text = String(value ?? "nopaint");
  let hash = 2166136261;
  for (let i = 0; i < text.length; i += 1) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0 || 1;
}

export function seededRandom(seed) {
  let state = seedFrom(seed);
  return () => {
    state += 0x6d2b79f5;
    let value = state;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
}
