// Famous melodies for notepat testing
// Format: array of {note, octave, duration} objects
// Notes: c, d, e, f, g, a, b, h, i, j, k, l, m, n (c-b in octave 4, c-b in octave 5)

export const melodies = {
  // Children's Songs
  'twinkle': [
    {note: 'c', octave: 4, duration: 400},
    {note: 'c', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 800},
    {note: 'f', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'd', octave: 4, duration: 400},
    {note: 'd', octave: 4, duration: 400},
    {note: 'c', octave: 4, duration: 800},
  ],
  
  "mary": [
    {note: 'e', octave: 4, duration: 200},
    {note: 'd', octave: 4, duration: 200},
    {note: 'c', octave: 4, duration: 200},
    {note: 'd', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 400},
    {note: 'd', octave: 4, duration: 200},
    {note: 'd', octave: 4, duration: 200},
    {note: 'd', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 200},
    {note: 'g', octave: 4, duration: 200},
    {note: 'g', octave: 4, duration: 400},
  ],
  
  // Folk & Traditional
  'old-macdonald': [
    {note: 'g', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 600},
    {note: 'b', octave: 4, duration: 300},
    {note: 'b', octave: 4, duration: 300},
    {note: 'a', octave: 4, duration: 300},
    {note: 'a', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 600},
  ],
  
  'yankee-doodle': [
    {note: 'c', octave: 4, duration: 250},
    {note: 'c', octave: 4, duration: 250},
    {note: 'd', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'c', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'd', octave: 4, duration: 500},
    {note: 'c', octave: 4, duration: 250},
    {note: 'c', octave: 4, duration: 250},
    {note: 'd', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'c', octave: 4, duration: 500},
  ],
  
  'frere-jacques': [
    {note: 'c', octave: 4, duration: 350},
    {note: 'd', octave: 4, duration: 350},
    {note: 'e', octave: 4, duration: 350},
    {note: 'c', octave: 4, duration: 350},
    {note: 'c', octave: 4, duration: 350},
    {note: 'd', octave: 4, duration: 350},
    {note: 'e', octave: 4, duration: 350},
    {note: 'c', octave: 4, duration: 350},
    {note: 'e', octave: 4, duration: 350},
    {note: 'f', octave: 4, duration: 350},
    {note: 'g', octave: 4, duration: 700},
  ],
  
  'london-bridge': [
    {note: 'g', octave: 4, duration: 300},
    {note: 'a', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'f', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 300},
    {note: 'f', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 600},
    {note: 'd', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 300},
    {note: 'f', octave: 4, duration: 600},
    {note: 'e', octave: 4, duration: 300},
    {note: 'f', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 600},
  ],
  
  'row-row-row': [
    {note: 'c', octave: 4, duration: 350},
    {note: 'c', octave: 4, duration: 250},
    {note: 'c', octave: 4, duration: 200},
    {note: 'd', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 600},
    {note: 'e', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 300},
    {note: 'f', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 900},
  ],
  
  'skip-to-my-lou': [
    {note: 'c', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 600},
    {note: 'e', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 600},
    {note: 'e', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 300},
    {note: 'c', octave: 4, duration: 600},
  ],
  
  'camptown-races': [
    {note: 'g', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'g', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'c', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'g', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'g', octave: 4, duration: 250},
    {note: 'g', octave: 4, duration: 250},
    {note: 'e', octave: 4, duration: 250},
    {note: 'c', octave: 4, duration: 500},
  ],
  
  'oh-susanna': [
    {note: 'c', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'a', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 600},
    {note: 'e', octave: 4, duration: 300},
    {note: 'c', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 300},
    {note: 'c', octave: 4, duration: 600},
  ],
  
  'amazing-grace': [
    {note: 'g', octave: 4, duration: 500},
    {note: 'c', octave: 5, duration: 350},
    {note: 'c', octave: 5, duration: 350},
    {note: 'c', octave: 5, duration: 350},
    {note: 'e', octave: 5, duration: 350},
    {note: 'c', octave: 5, duration: 700},
    {note: 'c', octave: 5, duration: 350},
    {note: 'a', octave: 4, duration: 350},
    {note: 'g', octave: 4, duration: 700},
    {note: 'e', octave: 4, duration: 350},
    {note: 'g', octave: 4, duration: 350},
    {note: 'g', octave: 4, duration: 350},
    {note: 'e', octave: 4, duration: 350},
    {note: 'c', octave: 4, duration: 1000},
  ],
  
  'auld-lang-syne': [
    {note: 'g', octave: 4, duration: 500},
    {note: 'c', octave: 5, duration: 350},
    {note: 'c', octave: 5, duration: 350},
    {note: 'c', octave: 5, duration: 350},
    {note: 'e', octave: 5, duration: 350},
    {note: 'd', octave: 5, duration: 500},
    {note: 'c', octave: 5, duration: 350},
    {note: 'd', octave: 5, duration: 350},
    {note: 'e', octave: 5, duration: 350},
    {note: 'd', octave: 5, duration: 500},
    {note: 'c', octave: 5, duration: 350},
    {note: 'c', octave: 5, duration: 350},
    {note: 'a', octave: 4, duration: 700},
  ],
  
  'shenandoah': [
    {note: 'c', octave: 4, duration: 500},
    {note: 'f', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 600},
    {note: 'g', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'd', octave: 4, duration: 600},
    {note: 'c', octave: 4, duration: 400},
    {note: 'd', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 800},
  ],
  
  'home-on-the-range': [
    {note: 'c', octave: 4, duration: 600},
    {note: 'e', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 600},
    {note: 'a', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 600},
    {note: 'c', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 800},
  ],
  
  'red-river-valley': [
    {note: 'c', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'c', octave: 5, duration: 800},
    {note: 'a', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 800},
  ],
  
  'scarborough-fair': [
    {note: 'a', octave: 4, duration: 600},
    {note: 'a', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 400},
    {note: 'b', octave: 4, duration: 400},
    {note: 'c', octave: 5, duration: 600},
    {note: 'b', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 800},
  ],
  
  'greensleeves': [
    {note: 'a', octave: 4, duration: 500},
    {note: 'c', octave: 5, duration: 300},
    {note: 'd', octave: 5, duration: 400},
    {note: 'e', octave: 5, duration: 300},
    {note: 'f', octave: 5, duration: 200},
    {note: 'e', octave: 5, duration: 400},
    {note: 'd', octave: 5, duration: 300},
    {note: 'b', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 300},
    {note: 'a', octave: 4, duration: 400},
    {note: 'b', octave: 4, duration: 300},
    {note: 'c', octave: 5, duration: 400},
    {note: 'a', octave: 4, duration: 800},
  ],
  
  'when-the-saints': [
    {note: 'c', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 800},
    {note: 'c', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 800},
    {note: 'c', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 400},
    {note: 'c', octave: 4, duration: 400},
    {note: 'd', octave: 4, duration: 800},
  ],
  
  'danny-boy': [
    {note: 'c', octave: 4, duration: 500},
    {note: 'e', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 600},
    {note: 'c', octave: 5, duration: 400},
    {note: 'a', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'f', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 600},
    {note: 'f', octave: 4, duration: 400},
    {note: 'g', octave: 4, duration: 400},
    {note: 'a', octave: 4, duration: 800},
  ],
  
  // Classical & Holiday
  "ode-to-joy": [
    {note: 'e', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 200},
    {note: 'f', octave: 4, duration: 200},
    {note: 'g', octave: 4, duration: 200},
    {note: 'g', octave: 4, duration: 200},
    {note: 'f', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 200},
    {note: 'd', octave: 4, duration: 200},
    {note: 'c', octave: 4, duration: 200},
    {note: 'c', octave: 4, duration: 200},
    {note: 'd', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 300},
    {note: 'd', octave: 4, duration: 100},
    {note: 'd', octave: 4, duration: 400},
  ],
  
  "jingle-bells": [
    {note: 'e', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 400},
    {note: 'e', octave: 4, duration: 200},
    {note: 'g', octave: 4, duration: 200},
    {note: 'c', octave: 4, duration: 200},
    {note: 'd', octave: 4, duration: 200},
    {note: 'e', octave: 4, duration: 800},
  ],
  
  "happy-birthday": [
    {note: 'c', octave: 4, duration: 150},
    {note: 'c', octave: 4, duration: 150},
    {note: 'd', octave: 4, duration: 300},
    {note: 'c', octave: 4, duration: 300},
    {note: 'f', octave: 4, duration: 300},
    {note: 'e', octave: 4, duration: 600},
    {note: 'c', octave: 4, duration: 150},
    {note: 'c', octave: 4, duration: 150},
    {note: 'd', octave: 4, duration: 300},
    {note: 'c', octave: 4, duration: 300},
    {note: 'g', octave: 4, duration: 300},
    {note: 'f', octave: 4, duration: 600},
  ]
};

// Map notepat keyboard keys to notes
// Octave 4: c d e f g a b
// Octave 5: h i j k l m n (same as c d e f g a b)
export function noteToKey(note, octave) {
  const noteMap = {
    'c': octave === 4 ? 'c' : 'h',
    'd': octave === 4 ? 'd' : 'i',
    'e': octave === 4 ? 'e' : 'j',
    'f': octave === 4 ? 'f' : 'k',
    'g': octave === 4 ? 'g' : 'l',
    'a': octave === 4 ? 'a' : 'm',
    'b': octave === 4 ? 'b' : 'n',
  };
  return noteMap[note] || 'c';
}
