[build]
  publish = "public"
[dev]
  framework = "#custom"
  command = "npm run local-dev-netlify"
  targetPort = 8080
  port = 443
[dev.https]
  certFile = "../ssl-dev/localhost.pem"
  keyFile = "../ssl-dev/localhost-key.pem"
[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"