// shared caption metadata, keyed by slug: [name, by, year, motif, register, note]
export const META = {
  // banks-finance
  "chase-octagon": ["Chase", "Chermayeff & Geismar", "1960", "octagon / vault aperture", "mid-century geometric", "first major US abstract bank mark — negative center reads as a vault"],
  "deutsche-bank-slash": ["Deutsche Bank", "Anton Stankowski", "1974", "slash in a square", "swiss constructivist", "growth (diagonal) held in a stable frame"],
  "hsbc-hexagon": ["HSBC", "Henry Steiner", "1983", "hexagon from St Andrew's cross", "heraldic→geometric", "from a 19th-c house flag; hexagon = containment"],
  "barclays-eagle": ["Barclays", "—", "—", "spread eagle", "heraldic, flattened", "centuries-old eagle modernized to flat"],
  "lloyds-black-horse": ["Lloyds Bank", "—", "1884", "black horse", "inherited shop-sign heraldry", "a goldsmith's shop sign become a brand"],
  "natwest-cubes": ["NatWest", "—", "1968", "three cubes / arrows", "swiss geometric", "money moving three directions"],
  "citi-arc": ["Citi", "Pentagram (Paula Scher)", "1998", "red arc over wordmark", "wordmark + gesture", "the arc as umbrella/protection"],
  "santander-flame": ["Santander", "—", "—", "flame / spark", "contemporary flat", "warmth + energy in red"],
  "mastercard-circles": ["Mastercard", "Pentagram (2016)", "1968", "two overlapping circles", "gestalt overlap", "intersection = exchange"],
  "amex-bluebox": ["American Express", "—", "1970s", "the Blue Box", "corporate trust blue", "the box as security / containment"],
  "ubs-keys": ["UBS", "—", "—", "three keys", "heraldic", "keys = confidence, security, discretion"],
  "ing-lion": ["ING", "—", "—", "lion", "dutch heraldic, flat", "heritage animal flattened to friendly"],
  "bbva-mark": ["BBVA", "Landor", "2019", "geometric wordmark", "contemporary sans", "softened modern banking"],
  "wells-fargo-stagecoach": ["Wells Fargo", "—", "—", "stagecoach", "americana heritage", "trust signalled through history"],
  "bank-of-america": ["Bank of America", "Lippincott", "1998", "abstract flag stripes", "patriotic geometric", "flag fragment = nation-scale trust"],
  "monte-paschi-siena": ["Monte dei Paschi di Siena", "—", "—", "heraldic shield", "italian heraldry", "the world's oldest surviving bank's arms"],
  // modernist-canon
  "rand-ibm": ["IBM", "Paul Rand", "1972", "8-bar striped letters", "rationalist", "stripes = scan-lines + unity"],
  "rand-ups": ["UPS (old)", "Paul Rand", "1961", "shield + package + bow", "heraldic-modern", "a parcel made into a coat of arms"],
  "rand-abc": ["ABC", "Paul Rand", "1962", "lowercase bauhaus circles", "bauhaus geometric", "minimal letterforms = quiet confidence"],
  "rand-westinghouse": ["Westinghouse", "Paul Rand", "1960", "circuit 'W'", "atomic-age", "a circuit board read as a monogram"],
  "rand-next": ["NeXT", "Paul Rand", "1986", "tilted cube", "playful-rational", "the famous $100k cube"],
  "cg-mobil": ["Mobil", "Chermayeff & Geismar", "1964", "red O wordmark", "minimalist", "the single red O does all the work"],
  "cg-nbc-peacock": ["NBC", "Chermayeff & Geismar", "1986", "six-feather peacock", "broadcast color", "color itself as the message"],
  "cg-pbs": ["PBS", "Chermayeff & Geismar", "1984", "P-head profiles", "figure-ground", "many faces = the public"],
  "cg-natgeo": ["National Geographic", "Chermayeff & Geismar", "—", "yellow rectangle", "portal", "the yellow frame as a window"],
  "bass-bell": ["Bell System", "Saul Bass", "1969", "bell in a circle", "simplification", "a century of marks reduced to one bell"],
  "bass-att-globe": ["AT&T", "Saul Bass", "1983", "striped globe", "line-network", "lines = the global network"],
  "bass-minolta": ["Minolta", "Saul Bass", "1978", "wordmark + curves", "japanese-modern", "soft motion in a tech wordmark"],
  "vignelli-american-airlines": ["American Airlines", "Massimo Vignelli", "1967", "AA + eagle", "helvetica + flag", "Helvetica discipline, lasted to 2013"],
  "vignelli-knoll": ["Knoll", "Massimo Vignelli", "—", "wordmark", "swiss typographic", "furniture as pure typography"],
  "lippincott-walmart-spark": ["Walmart", "Lippincott", "2008", "spark / sunburst", "friendly flat", "an asterisk of warmth"],
  "fedex-arrow": ["FedEx", "Lindon Leader (Landor)", "1994", "hidden arrow", "negative space", "the canonical negative-space mark"],
  "nike-swoosh": ["Nike", "Carolyn Davidson", "1971", "swoosh", "single gesture", "motion as a one-stroke mark"],
  "apple-logo": ["Apple", "Rob Janoff", "1977", "bitten apple", "friendly silhouette", "a bite for scale + recognizability"],
  "paul-rand-enron": ["Enron", "Paul Rand", "1996", "tilted color bars 'E'", "rand late-style", "Rand's last major mark"],
  // seals-monograms
  "us-treasury-seal": ["US Treasury", "—", "1789", "scales + chevron of stars", "engraved federal seal", "balance + key = fiscal authority"],
  "great-seal-us": ["Great Seal of the US", "—", "1782", "eagle + shield", "engraved heraldry", "the ur-seal of American officialdom"],
  "federal-reserve-seal": ["Federal Reserve", "—", "—", "eagle seal", "engraved", "monetary authority as engraved roundel"],
  "ul-mark": ["Underwriters Laboratories", "—", "1894", "UL in a circle", "certification roundel", "the literal safety-trust stamp"],
  "ce-mark": ["CE marking", "—", "1985", "geometric C+E", "conformity geometry", "constructed from circles — pure compliance form"],
  "bsi-kitemark": ["BSI Kitemark", "—", "1903", "kite shape", "british standard", "a monogram folded into a kite"],
  "fairtrade-mark": ["Fairtrade", "—", "2002", "yin-yang figure", "certification roundel", "a person + sky in a disc"],
  "usda-organic": ["USDA Organic", "—", "2002", "circular badge", "government certification", "trust via federal roundel"],
  "vw-monogram": ["Volkswagen", "—", "1939", "V over W in a circle", "geometric monogram", "two letters locked in a wheel"],
  "chanel-cc": ["Chanel", "Coco Chanel", "1925", "interlocking C's", "luxury monogram", "mirror symmetry = the locked seal of luxury"],
  "penny-black": ["Penny Black (stamp)", "—", "1840", "engraved profile", "intaglio portrait", "the first postage stamp — a state mark of paid trust"],
  "scotus-seal": ["US Supreme Court", "—", "—", "eagle seal", "engraved judicial", "the highest court's roundel"],
  "doj-seal": ["US Dept of Justice", "—", "—", "eagle + shield seal", "engraved federal", "justice rendered as an official stamp"],
  "wordpress-w": ["WordPress", "—", "—", "circled W", "open-source monogram", "a letter in a ring = an institution"],
  "yale-shield": ["Yale University", "—", "—", "shield + book", "academic heraldry", "knowledge bound in a coat of arms"],
  // surveillance-consent
  "norton-by-symantec": ["Norton", "—", "—", "yellow check in circle", "security yellow", "check in a ring = verified, protected"],
  "tor-onion": ["Tor", "—", "—", "onion", "activist flat", "layers = anonymity"],
  "signal-messenger": ["Signal", "—", "—", "speech bubble", "friendly privacy", "privacy made warm, not cold"],
  "eff": ["EFF", "—", "—", "wordmark", "digital-rights", "advocacy, not product"],
  "lets-encrypt": ["Let's Encrypt", "—", "2014", "open padlock", "open-security", "the lock made friendly + free"],
  "mozilla": ["Mozilla", "johnson banks", "2017", "moz://a wordmark", "wordmark-as-URL", "the protocol slashes built into the name"],
  "firefox": ["Firefox", "—", "—", "fox around a globe", "warm tech", "guardian animal wrapping the web"],
  "okta": ["Okta", "—", "—", "circular O", "identity SaaS blue", "the ring as gate / identity"],
  "openid": ["OpenID", "—", "—", "stylized ID", "standards mark", "decentralized identity, orange"],
  "w3c": ["W3C", "—", "—", "wordmark", "standards body", "the web's own authority mark"],
  "icann": ["ICANN", "—", "—", "globe / wordmark", "governance", "who governs the namespace"],
  "aadhaar": ["Aadhaar (UIDAI)", "—", "2010", "sun + fingerprint", "national-ID", "a billion-person identity mark"],
  "digicert": ["DigiCert", "—", "—", "checkmark", "certificate authority", "the CA that issues web trust"],
  "duckduckgo": ["DuckDuckGo", "—", "—", "duck in a circle", "friendly privacy-search", "an animal, not a padlock"],
  "fido-alliance": ["FIDO Alliance", "—", "—", "checkmark / wordmark", "passwordless standard", "the body behind passkeys"],
  "privacy-badger": ["Privacy Badger (EFF)", "—", "—", "badger", "activist mascot", "privacy as a scrappy animal"],
};
