import assert from 'node:assert/strict';
import {runnablePrefix,partialString,streamedEdits,streamedCode} from '../Resources/Web/stream-preview.mjs';
const paint='export function paint({wipe}) {wipe("pink");}';
assert.equal(runnablePrefix(paint+'\nexport function act({event}) {'),paint);
assert.equal(runnablePrefix('export function paint({wipe}) {wipe("pink");'), 'export function paint({wipe}) {wipe("pink");\n}');
assert.equal(runnablePrefix('const text="export function paint() {}";'),null);
assert.equal(runnablePrefix(paint+'\nconst x="unfinished'),paint);
assert.equal(runnablePrefix('export function boot() {}'),null);
assert.equal(runnablePrefix(paint),paint);
assert.equal(runnablePrefix('export function paint(){ const x="}";'), 'export function paint(){ const x="}";\n}');
assert.equal(runnablePrefix('export function paint({wipe}) {wipe("pink"); ink('), 'export function paint({wipe}) {wipe("pink");\n}');
assert.equal(runnablePrefix('export function paint({wipe}) {wipe("pink"); if (true) { circle('), 'export function paint({wipe}) {wipe("pink");\n}');
assert.equal(runnablePrefix('export function paint(){ const x="; }'), null);
assert.equal(runnablePrefix('export function paint(){ // wipe(0);'), null);
assert.equal(runnablePrefix('export function paint(){ let x ='), null);
assert.deepEqual(partialString('{"source":"ink(\\"pink\\");\\n'),{value:'ink("pink");\n',complete:false});
const edits={revision:'r1',edits:[{search:'pink',replace:'blue'},{search:'export function',replace:'export async function'}]};
const json=JSON.stringify(edits), first=json.indexOf('},{')+1;
assert.equal(streamedEdits(json.slice(0,first),paint,'r1'),paint.replace('pink','blue'));
assert.equal(streamedEdits(json.slice(0,first-2),paint,'r1'),null);
assert.equal(streamedEdits(json,paint,'stale'),null);
assert.equal(streamedEdits(json,paint,'r1'),paint.replace('pink','blue').replace('export function','export async function'));
assert.equal(streamedEdits(JSON.stringify({revision:'r1',edits:[{search:'no match',replace:''}]}),paint,'r1'),null);
console.log('PASS live paint statements and complete revision-checked edits; incomplete expressions, replacements and stale edits are withheld.');

assert.equal(streamedCode(json,'edit_piece'),'blue\nexport async function');
