#!/usr/bin/env python3
"""Reusable real-time loudness overlay for rendered music review videos."""

import bisect
import math
import re
import subprocess


def _db(amplitude):
    if amplitude is None or amplitude <= 0:
        return -120.0
    return 20.0 * math.log10(amplitude)


def analyze_loudness(audio_path, ffmpeg="ffmpeg"):
    """Return 10 Hz EBU R128 telemetry generated by ffmpeg for audio_path."""
    result = subprocess.run(
        [
            ffmpeg,
            "-hide_banner",
            "-nostats",
            "-i",
            audio_path,
            "-af",
            "ebur128=metadata=1:peak=true,ametadata=print:file=-",
            "-f",
            "null",
            "-",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    frames = []
    current = None
    for line in result.stdout.splitlines():
        match = re.match(r"frame:\d+\s+pts:\d+\s+pts_time:([\d.]+)", line)
        if match:
            if current is not None:
                frames.append(current)
            current = {"time": float(match.group(1))}
            continue
        if current is None or "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key.startswith("lavfi.r128."):
            try:
                current[key.removeprefix("lavfi.r128.")] = float(value)
            except ValueError:
                pass
    if current is not None:
        frames.append(current)
    if not frames:
        raise RuntimeError(f"No loudness telemetry produced for {audio_path}")
    return {"frames": frames, "times": [frame["time"] for frame in frames]}


def sample_loudness(telemetry, time_seconds):
    index = bisect.bisect_right(telemetry["times"], time_seconds) - 1
    frame = telemetry["frames"][max(0, min(index, len(telemetry["frames"]) - 1))]
    momentary = frame.get("M", -120.0)
    short_term = frame.get("S", -120.0)
    if short_term < -60.0:
        short_term = momentary
    integrated = frame.get("I", -70.0)
    return {
        "short_term": short_term,
        "integrated": integrated,
        "true_peak": _db(frame.get("true_peak")),
        "lra": frame.get("LRA", 0.0),
    }


def draw_loudness_meter(
    draw,
    telemetry,
    time_seconds,
    box,
    font,
    target_lufs=-10.5,
    target_tolerance=1.0,
    true_peak_ceiling=-2.0,
    spotify_target=-14.0,
    colors=None,
):
    """Draw live LUFS, target, true-peak, and normalization telemetry."""
    palette = {
        "background": (25, 25, 27),
        "outline": (96, 96, 102),
        "text": (236, 234, 225),
        "muted": (155, 154, 151),
        "track": (55, 55, 61),
        "target": (60, 176, 132),
        "short": (255, 211, 82),
        "integrated": (105, 176, 255),
        "warning": (244, 87, 92),
    }
    if colors:
        palette.update(colors)

    x0, y0, x1, y1 = box
    reading = sample_loudness(telemetry, time_seconds)
    short_term = reading["short_term"]
    integrated = reading["integrated"]
    true_peak = reading["true_peak"]
    normalization = spotify_target - integrated if integrated > -60 else None

    draw.rounded_rectangle(box, radius=8, fill=palette["background"],
                           outline=palette["outline"], width=1)
    label_y = y0 + 5

    def fmt(value, suffix=""):
        return f"{value:+.1f}{suffix}" if value > -60 else "--"

    draw.text((x0 + 12, label_y), f"S {fmt(short_term)}", font=font,
              fill=palette["short"])
    draw.text((x0 + 132, label_y), f"I {fmt(integrated)}", font=font,
              fill=palette["integrated"])
    peak_color = palette["warning"] if true_peak > true_peak_ceiling + 0.05 else palette["text"]
    draw.text((x0 + 252, label_y), f"TP {fmt(true_peak)}", font=font,
              fill=peak_color)
    norm_text = "--" if normalization is None else f"{normalization:+.1f} dB"
    draw.text((x0 + 388, label_y), f"STREAM {norm_text}", font=font,
              fill=palette["muted"])
    draw.text((x1 - 12, label_y), f"TARGET {target_lufs:.1f} LUFS", font=font,
              fill=palette["target"], anchor="ra")

    scale_min, scale_max = -24.0, -4.0
    bar_x0, bar_x1 = x0 + 12, x1 - 12
    bar_y0, bar_y1 = y1 - 10, y1 - 5

    def sx(value):
        unit = (max(scale_min, min(scale_max, value)) - scale_min) / (scale_max - scale_min)
        return int(round(bar_x0 + unit * (bar_x1 - bar_x0)))

    draw.rectangle((bar_x0, bar_y0, bar_x1, bar_y1), fill=palette["track"])
    draw.rectangle((sx(target_lufs - target_tolerance), bar_y0,
                    sx(target_lufs + target_tolerance), bar_y1), fill=palette["target"])
    tx = sx(target_lufs)
    draw.line((tx, bar_y0 - 2, tx, bar_y1 + 2), fill=palette["text"], width=1)
    if integrated > -60:
        ix = sx(integrated)
        draw.line((ix, bar_y0 - 3, ix, bar_y1 + 3), fill=palette["integrated"], width=2)
    if short_term > -60:
        mx = sx(short_term)
        draw.ellipse((mx - 4, bar_y0 - 4, mx + 4, bar_y1 + 4), fill=palette["short"])
    return reading
