// score.h — generated by c/bake.mjs. do not hand-edit.
#define SCORE_BPM 160
#define SCORE_SR 48000

#define N_ROLES 25
static const char *ROLE_NAME[N_ROLES] = {
  "taiko", "gong", "choir", "brass", "strings", "bass", "ghost", "hat", "ohat", "ride", "shaker", "sub", "reese", "lead", "pad", "kick", "snare", "animal", "wolf", "cowbell", "tom", "click", "rain", "jungle", "cricket"
};
static const char *ROLE_PATH[N_ROLES] = {
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/82712-taiko_drum_001_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/518292-gong_2_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/162168-aah2_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/820070-cm_orch_hit_3_infernal_dance_2_207s.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/758483-arc_c.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/560208-layered_bass_05_quick_synth_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/46567-ludwig_black_beauty_snare_ghost_notes_unprocesse.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/509971-hi_hat_closed_9_mp3.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/509984-hi_hat_open_1_mp3.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/799423-ride_bell_1_long.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/375636-shaker_shake5_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/6291-ppg_016_subfrequent_g_2_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/424432-angryreesebassf0160bpm_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/257363-overall_quality_of_single_note_flute_c4.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/46127-k_wstr_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/337827-kick_short_tail_174_bpm_02_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/118312-lr_sn_0029_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/571287-jaguar_growl_roar_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/429109-15_wolfcrying_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/75338-cowbell_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/581462-fractanimal_acoustic_drum_kit_mid_tom_2_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/375399-snare_sfx_click_wav.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/371710-raining.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/644989-jungle_forest_ambience.wav",
  "/Users/jas/aesthetic-computer-vault/personal/pop/freesound-cache/710399-landscape_nl_march_1131am_230302_0566.wav",
};
static const int ROLE_PITCHED[N_ROLES] = {
  0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0
};
// nominal root midi from kit.json (rateFor path); -1 = unpitched
static const int ROLE_NOMINAL[N_ROLES] = {
  -1, -1, 60, 48, 60, 36, -1, -1, -1, -1, -1, 24, 36, 60, 48, -1, -1, 48, 57, -1, -1, -1, -1, -1, -1
};

static const char *BELL_PATH = "/Users/jas/aesthetic-computer/pop/hellsine/samples/church-bell.wav";

#define N_SHOUTS 6
static const char *SHOUT_KEY[N_SHOUTS] = { "wake", "real", "hold", "let", "rabbit", "now" };
static const char *SHOUT_J[N_SHOUTS] = {
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/wake_up.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/it_s_real.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/hold_on.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/let_go.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/follow_the_white_rabbit.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/now.wav",
};
static const char *SHOUT_A[N_SHOUTS] = {
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/wake_up-say-sung.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/it_s_real-say-sung.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/hold_on-say-sung.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/let_go-say-sung.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/follow_the_white_rabbit-say-sung.wav",
  "/Users/jas/aesthetic-computer/pop/maytrax/out/shouts/now-say-sung.wav",
};

