# wasm-strip
# Autogenerated from man page /home/linuxbrew/.linuxbrew/share/man/man1/wasm-strip.1
complete -c wasm-strip -l help -d 'Print a help message'
complete -c wasm-strip -l version -d 'Print version information'
complete -c wasm-strip -s o -d 'output wasm binary file El EXAMPLES Remove all custom sections from test'

