# wasm-objdump
# Autogenerated from man page /home/linuxbrew/.linuxbrew/share/man/man1/wasm-objdump.1
complete -c wasm-objdump -l help -d 'Print a help message'
complete -c wasm-objdump -l version -d 'Print version information'
complete -c wasm-objdump -s h -d 'Print headers'
complete -c wasm-objdump -s j -d 'Select just one section'
complete -c wasm-objdump -s s -d 'Print raw section contents'
complete -c wasm-objdump -s d -d 'Disassemble function bodies'
complete -c wasm-objdump -l debug -d 'Print extra debug information'
complete -c wasm-objdump -s x -d 'Show section details'
complete -c wasm-objdump -s r -d 'Show relocations inline with disassembly'
complete -c wasm-objdump -l section-offsets -d 'Print section offsets instead of file offsets in code disassembly El EXAMPLES…'

